/****** Object:  View [promt].[dim_ent_promt_project_active_v]    Script Date: 5/3/2024 8:21:41 PM ******/
DROP VIEW [promt].[dim_ent_promt_project_active_v]
GO

CREATE VIEW [promt].[dim_ent_promt_project_active_v]
AS SELECT 
[dim_ent_promt_project_sk]
,[dim_ent_promt_project_nk]
,[t_project_id] as [Project ID]
,[project_no] as [Project Number]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[late_arrival_flag] as [Late Arrival Flag]
,[project_pc_code] as [Project Pc Code]
,[project_pc_code_description] as [Project Pc Code Description]
,[project_bid_project_id] as [Project Bid Project Id]
,[project_project_title] as [Project Project Title]
,[project_client_name] as [Project Client Name]
,[project_business_line] as [Project Business Line]
,[project_business_line_description] as [Project Business Line Description]
,[project_country] as [Project Country]
,[project_manager] as [Project Manager]
,[project_prom_lead] as [Project Prom Lead]
,[project_category] as [Project Category]
,[project_category_description] as [Project Category Description]
,[project_total_contract_value] as [Project Total Contract Value]
,[project_estimated_cost] as [Project Estimated Cost]
,[project_currency_code] as [Project Currency Code]
,[project_currency_code_description] as [Project Currency Code Description]	
,[project_contract_type] as [Project Contract Type]
,[project_contract_type_description] as [Project Contract Type Description]
,[project_total_duration] as [Project Total Duration]
,[project_document_revision_no] as [Project Document Revision No]
,[project_document_revision_date] as [Project Document Revision Date]
,[project_revisied_by] as [Project Revisied By]
,[project_approved_by] as [Project Approved By]
,[project_award_date] as [Project Award Date]
,[project_active_flag] as [Project Active Flag]
,[project_project_type] as [Project Project Type]
,[project_project_type_description] as [Project Project Type Description]
,[project_duration_type] as [Project Duration Type]
,[project_version_no] as [Project Version No]
,[project_status] as [Project Status]
,[project_status_description] as [Project Status Description]
,[closed_dtm] as [Closed Dtm]
,[archived] as [Archived]
,[rearchival_date] as [Rearchival Date]


FROM [promt].[dim_ent_promt_project]
where active = 1;
GO


--------------------------------------------------------------------

/****** Object:  View [promt].[dim_ent_promt_project_snapshot_active_v]    Script Date: 5/3/2024 8:23:10 PM ******/
DROP VIEW [promt].[dim_ent_promt_project_snapshot_active_v]
GO

CREATE VIEW [promt].[dim_ent_promt_project_snapshot_active_v]
AS SELECT 
[dim_ent_promt_project_sk]
,[dim_ent_promt_project_nk]
,[t_project_id] as [Project ID]
,[ss_id] as [SS ID]
,[project_no] as [Project Number]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[late_arrival_flag] as [Late Arrival Flag]
,[project_pc_code] as [Project Pc Code]
,[project_pc_code_description] as [Project Pc Code Description]
,[project_bid_project_id] as [Project Bid Project Id]
,[project_project_title] as [Project Project Title]
,[project_client_name] as [Project Client Name]
,[project_business_line] as [Project Business Line]
,[project_business_line_description] as [Project Business Line Description]
,[project_country] as [Project Country]
,[project_manager] as [Project Manager]
,[project_prom_lead] as [Project Prom Lead]
,[project_category] as [Project Category]
,[project_category_description] as [Project Category Description]
,[project_total_contract_value] as [Project Total Contract Value]
,[project_estimated_cost] as [Project Estimated Cost]
,[project_currency_code] as [Project Currency Code]
,[project_currency_code_description] as [Project Currency Code Description]	
,[project_contract_type] as [Project Contract Type]
,[project_contract_type_description] as [Project Contract Type Description]
,[project_total_duration] as [Project Total Duration]
,[project_document_revision_no] as [Project Document Revision No]
,[project_document_revision_date] as [Project Document Revision Date]
,[project_revisied_by] as [Project Revisied By]
,[project_approved_by] as [Project Approved By]
,[project_award_date] as [Project Award Date]
,[project_active_flag] as [Project Active Flag]
,[project_project_type] as [Project Project Type]
,[project_project_type_description] as [Project Project Type Description]
,[project_duration_type] as [Project Duration Type]
,[project_version_no] as [Project Version No]
,[project_status] as [Project Status]
,[project_status_description] as [Project Status Description]
,[closed_dtm] as [Closed Dtm]
,[archived] as [Archived]
,[rearchival_date] as [Rearchival Date]


FROM [promt].[dim_ent_promt_project_snapshot]
where active = 1;
GO


