CREATE TABLE [epr].[iDocs_Vendor_Data_Ruya13_D7506]
(
[DOC_ID]   varchar(200) NULL,
[DELIVERABLE]   varchar(200) NULL,
[OFFICE LOCATION]   varchar(4000) NULL,
[POREQNO]   varchar(200) NULL,
[PO DESCRIPTION]   varchar(200) NULL,
[SELLER]   varchar(200) NULL,
[ENGR/QA FOCAL]   varchar(200) NULL,
[DOCNUMBER]   varchar(200) NULL,
[COMPANY DOCUMENT NUMBER]   varchar(200) NULL,
[REVISION]   varchar(200) NULL,
[TITLE]   varchar(2000) NULL,
[DOCSTATUS]   varchar(200) NULL,
[LAST RTV STATUS]   varchar(200) NULL,
[DISTRIBUTION PURPOSE CLIENT]   varchar(200) NULL,
[DISTRIBUTION PURPOSE SUPPLIER]   varchar(4000) NULL,
[DISTRIBUTION PURPOSE EMPLOYEE]   varchar(200) NULL,
[Package Manager]   varchar(4000) NULL,
[VERSION]   varchar(200) NULL,
[VENDOR DISCIPLINE]   varchar(200) NULL,
[CLIENT DOC. TYPE]   varchar(200) NULL,
[CLIENT DISCIPLINE]   varchar(200) NULL,
[SYSTEM CODE]   varchar(200) NULL,
[SUB-SYSTEM]   varchar(200) NULL,
[COUNTRY]   varchar(200) NULL,
[SITE]   varchar(4000) NULL,
[SECTOR]   varchar(4000) NULL,
[ORIGINATOR]   varchar(2000) NULL,
[SEQUENTIAL NUMBER]   varchar(2000) NULL,
[PROJECT CODE]   varchar(2000) NULL,
[CONTRACTOR]   varchar(2000) NULL,
[DOCUMENT GROUP]   varchar(2000) NULL,
[SDR CODE]   varchar(2000) NULL,
[PRIORITY LEVEL]   varchar(2000) NULL,
[PRIORITY OVERRIDE]   varchar(2000) NULL,
[% COMPLETION]   varchar(2000) NULL,
[TOTAL PROGRESS]   varchar(2000) NULL,
[DOC WEIGHT]   varchar(2000) NULL,
[DATE RECEIVED RECEIPT]   varchar(2000) NULL,
[IFR Internal Review Plan]   varchar(2000) NULL,
[IFR Internal Review Forecast]   varchar(2000) NULL,
[IFR Internal Review Actual]   varchar(2000) NULL,
[IFR - Client Plan]   varchar(2000) NULL,
[IFR - Client Forecast]   varchar(2000) NULL,
[IFR - Client Actual]   varchar(2000) NULL,
[IFR - RCA Plan]   varchar(2000) NULL,
[IFR - RCA Forecast]   varchar(2000) NULL,
[IFR - RCA Actual]   varchar(2000) NULL,
[IFR - RTV Plan]   varchar(2000) NULL,
[IFR - RTV Forecast]   varchar(2000) NULL,
[IFR - RTV Actual]   varchar(2000) NULL,
[IFA Internal Review Plan]   varchar(2000) NULL,
[IFA Internal Review Forecast]   varchar(2000) NULL,
[IFA Internal Review Actual]   varchar(2000) NULL,
[IFA - Client Plan]   varchar(2000) NULL,
[IFA - Client Forecast]   varchar(2000) NULL,
[IFA - Client Actual]   varchar(2000) NULL,
[IFA - RCA Plan]   varchar(2000) NULL,
[IFA - RCA Forecast]   varchar(2000) NULL,
[IFA - RCA Actual]   varchar(2000) NULL,
[IFA - RTV Plan]   varchar(2000) NULL,
[IFA - RTV Forecast]   varchar(2000) NULL,
[IFA - RTV Actual]   varchar(2000) NULL,
[AFC Internal Review Plan]   varchar(2000) NULL,
[AFC Internal Review Forecast]   varchar(2000) NULL,
[AFC Internal Review Actual]   varchar(2000) NULL,
[AFC - Client Plan]   varchar(2000) NULL,
[AFC - Client Forecast]   varchar(2000) NULL,
[AFC - Client Actual]   varchar(2000) NULL,
[AFC - RCA Plan]   varchar(2000) NULL,
[AFC - RCA Forecast]   varchar(2000) NULL,
[AFC - RCA Actual]   varchar(2000) NULL,
[AFC - RTV Plan]   varchar(2000) NULL,
[AFC - RTV Forecast]   varchar(2000) NULL,
[AFC - RTV Actual]   varchar(2000) NULL,
[AB Internal Review Plan]   varchar(2000) NULL,
[AB Internal Review Forecast]   varchar(2000) NULL,
[AB Internal Review Actual]   varchar(2000) NULL,
[AB - Client Plan]   varchar(2000) NULL,
[AB - Client Forecast]   varchar(2000) NULL,
[AB - Client Actual]   varchar(2000) NULL,
[AB - RCA Plan]   varchar(2000) NULL,
[AB - RCA Forecast]   varchar(2000) NULL,
[AB - RCA Actual]   varchar(2000) NULL,
[AB - RTV Plan]   varchar(2000) NULL,
[AB - RTV Forecast]   varchar(2000) NULL,
[AB - RTV Actual]   varchar(2000) NULL,
[IFI Internal Review Plan]   varchar(2000) NULL,
[IFI Internal Review Forecast]   varchar(2000) NULL,
[IFI Internal Review Actual]   varchar(2000) NULL,
[IFI - Client Plan]   varchar(2000) NULL,
[IFI - Client Forecast]   varchar(2000) NULL,
[IFI - Client Actual]   varchar(2000) NULL,
[IFI - RCA Plan]   varchar(2000) NULL,
[IFI - RCA Forecast]   varchar(2000) NULL,
[IFI - RCA Actual]   varchar(2000) NULL,
[IFI - RTV Plan]   varchar(2000) NULL,
[IFI - RTV Forecast]   varchar(2000) NULL,
[IFI - RTV Actual]   varchar(2000) NULL,
[TRANSMITTAL NUMBER (E)]   varchar(2000) NULL,
[TRANSMITTAL DATE (E)]   varchar(2000) NULL,
[INTERNAL EXP DATE]   varchar(2000) NULL,
[DAYS OVERDUE (EMPLOYER)]   varchar(2000) NULL,
[CLIENT TRANSMITTAL NUMBER]   varchar(2000) NULL,
[CLIENT TRANSMITTAL DATE]   varchar(2000) NULL,
[CLIENT EXPECTED RETURN DATE]   varchar(2000) NULL,
[DAYS OVERDUE (CLIENT)]   varchar(2000) NULL,
[CLIENT TRANSNO (INCOMING)]   varchar(2000) NULL,
[CLIENT TRANSDATE (INCOMING)]   varchar(2000) NULL,
[CLIENT CODE]   varchar(2000) NULL,
[TRANSMITTAL NUMBER (S)/(X)]   varchar(2000) NULL,
[TRANSMITTAL Date (S)/(X)]   varchar(2000) NULL,
[RETURN DATE TO SUPPLIER]   varchar(2000) NULL,
[DAYS OVERDUE (S)]   varchar(2000) NULL,
[SUPPLIER DOCNUMBER]   varchar(2000) NULL,
[SUPPLIER REVISION]   varchar(2000) NULL,
[EXPEDITOR COMMENTS]   varchar(2000) NULL,
[REQORIGINATOR]   varchar(2000) NULL,
[EXPEDITOR]   varchar(2000) NULL,
[DELIVERABLE TYPE]   varchar(2000) NULL,
[DOCUMENT CLASSIFICATION]   varchar(2000) NULL,
[INITIAL PLAN SUBMITTAL DATE]   varchar(2000) NULL,
[INITIAL FORECAST SUBM DATE]   varchar(2000) NULL,
[OVERDUE DAYS]   varchar(2000) NULL,
[Native file req. Hand-over]   varchar(2000) NULL,
[3RD PARTY COMPANY]   varchar(2000) NULL,
[3RD PARTY TRANSMITTAL NO]   varchar(2000) NULL,
[3RD PARTY TRANSMITTAL DATE]   varchar(2000) NULL,
[TRANSMITTAL NUMBER (P)]   varchar(2000) NULL,
[TRANSMITTAL DATE (P)]   varchar(2000) NULL,
[RETURN DATE FROM PARTNER]   varchar(2000) NULL,
[DAYS OVERDUE (P)]   varchar(2000) NULL,
[FOLDER NUMBER]   varchar(8000) NULL,
[AS BUILT REQUIRED]   varchar(2000) NULL,
[Review Case]   varchar(2000) NULL,
[LAST CLIENT CODE RECEIVED]   varchar(2000) NULL,
[MME Review]   varchar(2000) NULL,
[Planned Start]   varchar(2000) NULL,
[Planned Finish]   varchar(2000) NULL,
[SD_Facility No.]   varchar(2000) NULL,
[Campaign Name]   varchar(2000) NULL,
[Assignment Number Code-Planning]   varchar(2000) NULL,
[MOPEX-Planning]   varchar(2000) NULL,
[Discipline-Planning]   varchar(2000) NULL,
[Priority Progress-Planning]   varchar(2000) NULL,
[Manhours Progress-Planning]   varchar(2000) NULL,
[HHI-NOC Transmittal Number]   varchar(2000) NULL,
[HHI-NOC Transmittal Date]   varchar(2000) NULL,
[HHI Review]   varchar(2000) NULL,
[Client Document Rev]   varchar(2000) NULL,
[Client Document Status]   varchar(2000) NULL,
[project_number] [varchar](2000) NULL,
 [file_name] [varchar](2000) NULL,
 [CreatedDateTime] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder','start_date','1','start_date','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder','end_date','2','end_date','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder','source_directory','3','source_directory','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder','table_name','4','table_name','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder','logicapp_url','5','logicapp_url','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder','range','6','range','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder','file_name','7','file_name','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder','project_number','8','project_number','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813')


insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('range','A1:ET500000','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813','pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('table_name','iDocs_Vendor_Data_Ruya13_D7506','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813','pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('logicapp_url','https://prod-56.eastus.logic.azure.com:443/workflows/3cff41a53ba14a82a9b7cc8d6d2bfe56/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=c7BCbv69x4tk7w5oqGQNOPlpIXvqBQi_Zwm8wkww0WQ','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813','pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('end_date','currdate','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813','pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('source_directory','07. D7506 - RUYA 13\02. Engineering\05. Vendor Data\01. iDocs Vendor Data','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813','pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('project_number','D7506','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813','pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('start_date','2024-02-12 11:23:20','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813','pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('file_name','PS04 - SMDR.xlsx','1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813','pl_iDocs_Vendor_Data_Ruya13_D7506','NetworkFolder')

insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_iDocs_Vendor_Data_Ruya13_D7506','NCSA','Manual Excel File Direct Source To Synapse',NULL,'1','sundararaju.batta@mcdermott.com','2025-03-11 08:42:51.813',9)

