/****** Object:  Table [gpd].[P6_engr_headcount_forecast]    Script Date: 2/6/2022 5:40:57 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [gpd].[P6_engr_headcount_forecast]
(
	[stage_p6_engr_id] [int] IDENTITY(1,1) NOT NULL,
	[project] [varchar](100) NOT NULL,
	[Activity_ID] [varchar](55) NULL,
	[Activity_Name] [varchar](512) NULL,
	[Original_Duration] [varchar](100) NULL,
	[Actual_Duration] [varchar](100) NULL,
	[Remaining_Duration] [varchar](100) NULL,
	[Start] [varchar](55) NULL,
	[Finish] [varchar](55) NULL,
	[Actual_Start] [varchar](55) NULL,
	[Actual_Finish] [varchar](55) NULL,
	[Remaining_Late_Start] [varchar](55) NULL,
	[Remaining_Late_Finish] [varchar](55) NULL,
	[Calendar] [varchar](100) NULL,
	[Budgeted_Units] [varchar](100) NULL,
	[Actual_Units] [varchar](100) NULL,
	[Remaining_Units] [varchar](100) NULL,
	[WBS] [varchar](100) NULL,
	[WBS_Name] [varchar](100) NULL,
	[Cost_Account] [varchar](100) NULL,
	[Role] [varchar](100) NULL,
	[Change_Management] [varchar](50) NULL,
	[Executed_By_Type] [varchar](50) NULL,
	[Function] [varchar](50) NULL,
	[Milestones] [varchar](50) NULL,
	[Office] [varchar](50) NULL,
	[Phase] [varchar](50) NULL,
	[Region] [varchar](50) NULL,
	[Schedule_Risk_Assessment] [varchar](50) NULL,
	[Storage_Solutions] [varchar](50) NULL,
	[Supply_Chain] [varchar](50) NULL,
	[Prime] [varchar](100) NULL,
	[SubPrime] [varchar](100) NULL,
	[Spreadsheet_Field] [varchar](512) NULL,
	[Period] [varchar](55) NULL,
	[Units] [varchar](100) NULL,
	[fx] [nvarchar](100) NULL,
	[work_unit] [nvarchar](100) NULL,
	[work_area] [nvarchar](100) NULL,
	[cwp] [nvarchar](100) NULL,
	[schedule_resource] [nvarchar](100) NULL,
	[iwp] [nvarchar](100) NULL,
	[pim] [nvarchar](100) NULL,
	[roc] [nvarchar](100) NULL,
	[data_class] [nvarchar](100) NULL,
	[sub_source] [nvarchar](100) NULL,
	[source] [nvarchar](100) NULL,
	[unit_of_measure] [nvarchar](100) NULL,
	[dim_entp_function_sk] [int] NULL,
	[dim_entp_function_nk] [int] NULL,
	[dim_entp_project_sk] [int] NULL,
	[dim_entp_project_nk] [int] NULL,
	[dim_entp_phase_sk] [int] NULL,
	[dim_entp_phase_nk] [int] NULL,
	[dim_entp_work_unit_sk] [int] NULL,
	[dim_entp_work_unit_nk] [int] NULL,
	[dim_entp_work_area_sk] [int] NULL,
	[dim_entp_work_area_nk] [int] NULL,
	[dim_entp_cwp_sk] [int] NULL,
	[dim_entp_cwp_nk] [int] NULL,
	[dim_entp_schedule_resource_sk] [int] NULL,
	[dim_entp_schedule_resource_nk] [int] NULL,
	[dim_entp_activity_sk] [int] NULL,
	[dim_entp_activity_nk] [int] NULL,
	[dim_entp_iwp_sk] [int] NULL,
	[dim_entp_iwp_nk] [int] NULL,
	[dim_entp_pim_sk] [int] NULL,
	[dim_entp_pim_nk] [int] NULL,
	[dim_entp_roc_sk] [int] NULL,
	[dim_entp_roc_nk] [int] NULL,
	[dim_entp_data_sub_class_sk] [int] NULL,
	[dim_entp_data_sub_class_nk] [int] NULL,
	[dim_entp_data_class_sk] [int] NULL,
	[dim_entp_data_class_nk] [int] NULL,
	[dim_entp_sub_source_sk] [int] NULL,
	[dim_entp_sub_source_nk] [int] NULL,
	[dim_entp_source_sk] [int] NULL,
	[dim_entp_source_nk] [int] NULL,
	[dim_entp_unit_of_measure_sk] [int] NULL,
	[dim_entp_unit_of_measure_nk] [int] NULL,
	[load_date_time] [datetime] NULL,
	[parent_rssk] [int] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

------------------------------------------

/****** Object:  Table [gpd].[reprocess_P6_engr_headcount_forecast]    Script Date: 2/6/2022 5:43:34 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [gpd].[reprocess_P6_engr_headcount_forecast]
(
	[rssk] [int] IDENTITY(1,1) NOT NULL,
	[project] [varchar](100) NOT NULL,
	[Activity_ID] [varchar](55) NULL,
	[Activity_Name] [varchar](512) NULL,
	[Original_Duration] [varchar](100) NULL,
	[Actual_Duration] [varchar](100) NULL,
	[Remaining_Duration] [varchar](100) NULL,
	[Start] [varchar](55) NULL,
	[Finish] [varchar](55) NULL,
	[Actual_Start] [varchar](55) NULL,
	[Actual_Finish] [varchar](55) NULL,
	[Remaining_Late_Start] [varchar](55) NULL,
	[Remaining_Late_Finish] [varchar](55) NULL,
	[Calendar] [varchar](100) NULL,
	[Budgeted_Units] [varchar](100) NULL,
	[Actual_Units] [varchar](100) NULL,
	[Remaining_Units] [varchar](100) NULL,
	[WBS] [varchar](100) NULL,
	[WBS_Name] [varchar](100) NULL,
	[Cost_Account] [varchar](100) NULL,
	[Role] [varchar](100) NULL,
	[Change_Management] [varchar](50) NULL,
	[Executed_By_Type] [varchar](50) NULL,
	[Function] [varchar](50) NULL,
	[Milestones] [varchar](50) NULL,
	[Office] [varchar](50) NULL,
	[Phase] [varchar](50) NULL,
	[Region] [varchar](50) NULL,
	[Schedule_Risk_Assessment] [varchar](50) NULL,
	[Storage_Solutions] [varchar](50) NULL,
	[Supply_Chain] [varchar](50) NULL,
	[Prime] [varchar](100) NULL,
	[SubPrime] [varchar](100) NULL,
	[Spreadsheet_Field] [varchar](512) NULL,
	[Period] [varchar](55) NULL,
	[Units] [varchar](100) NULL,
	[fx] [nvarchar](100) NULL,
	[work_unit] [nvarchar](100) NULL,
	[work_area] [nvarchar](100) NULL,
	[cwp] [nvarchar](100) NULL,
	[schedule_resource] [nvarchar](100) NULL,
	[iwp] [nvarchar](100) NULL,
	[pim] [nvarchar](100) NULL,
	[roc] [nvarchar](100) NULL,
	[data_class] [nvarchar](100) NULL,
	[sub_source] [nvarchar](100) NULL,
	[source] [nvarchar](100) NULL,
	[unit_of_measure] [nvarchar](100) NULL,
	[dim_entp_function_sk] [int] NULL,
	[dim_entp_function_nk] [int] NULL,
	[dim_entp_project_sk] [int] NULL,
	[dim_entp_project_nk] [int] NULL,
	[dim_entp_phase_sk] [int] NULL,
	[dim_entp_phase_nk] [int] NULL,
	[dim_entp_work_unit_sk] [int] NULL,
	[dim_entp_work_unit_nk] [int] NULL,
	[dim_entp_work_area_sk] [int] NULL,
	[dim_entp_work_area_nk] [int] NULL,
	[dim_entp_cwp_sk] [int] NULL,
	[dim_entp_cwp_nk] [int] NULL,
	[dim_entp_schedule_resource_sk] [int] NULL,
	[dim_entp_schedule_resource_nk] [int] NULL,
	[dim_entp_activity_sk] [int] NULL,
	[dim_entp_activity_nk] [int] NULL,
	[dim_entp_iwp_sk] [int] NULL,
	[dim_entp_iwp_nk] [int] NULL,
	[dim_entp_pim_sk] [int] NULL,
	[dim_entp_pim_nk] [int] NULL,
	[dim_entp_roc_sk] [int] NULL,
	[dim_entp_roc_nk] [int] NULL,
	[dim_entp_data_sub_class_sk] [int] NULL,
	[dim_entp_data_sub_class_nk] [int] NULL,
	[dim_entp_data_class_sk] [int] NULL,
	[dim_entp_data_class_nk] [int] NULL,
	[dim_entp_sub_source_sk] [int] NULL,
	[dim_entp_sub_source_nk] [int] NULL,
	[dim_entp_source_sk] [int] NULL,
	[dim_entp_source_nk] [int] NULL,
	[dim_entp_unit_of_measure_sk] [int] NULL,
	[dim_entp_unit_of_measure_nk] [int] NULL,
	[load_date_time] [datetime] NULL,
	[parent_rssk] [int] NULL,
	[rk_failure_info] [varchar](5000) NULL,
	[hash_code] [varchar](8000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO



