DROP VIEW [dbo].[dim_entp_yardkpi_intelex_injury_illness_v]

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[dim_entp_yardkpi_intelex_injury_illness_v]
AS select 
	[dim_entp_yardkpi_intelex_injury_illness_sk],
	[dim_entp_yardkpi_intelex_injury_illness_nk] ,
	[start_date],
	[end_date],
	[hash_code],
	[active],
	[created_date_time],
	[modified_date_time],
	[late_arrival_flag],
	[dim_ent_source_nk],
	[dim_ent_sub_source_nk],
	[row_id],
	[employee_id],
	[record_no],
	[category],
	[date],
	[hipo_change_counter] ,
	[location],
	[was_treatment_received],
	[hipo],
	[related_movs],
	[profile_type],
	[profile_no],
	[profile],
	[vessel_barge],
	[business_line],
	[area],
	[project_name],
	[project_number],
	[incident_title],
	[hospitalization_type],
	[description],
	[injury_or_illness],
	[number_of_people_impacted],
	[immediate_action],
	[external_agency_notification_required],
	[specify_agency],
	[specify_other],
	[worker_type],
	[does_employee_exist_in_the_system],
	[employee_id2],
	[first_name],
	[last_name],
	[did_the_incident_occur_during_rework],
	[potential_risk_reporting_level],
	[potential_severity_level],
	[actual_severity_level],
	[reported_by],
	[stop_work_authority_applied],
	[work_related_injury_illness],
	[impacted_person_sent_offsite_for_evaluation_or_treatment],
	[drug_and_or_alcohol_test_required],
	[local_news_media_involvement],
	[incident_reported_by],
	[created_by],
	[date_created],
	[assign_investigator],
	[comments],
	[workers_comp],
	[workers_comp_comments],
	[shift_details],
	[hours_into_shift],
	[shift_duration],
	[privacy_case],
	[events_exposures],
	[source_of_injury_illness],
	[source_details],
	[body_part],
	[injury_illness],
	[initial_treatment],
	[who_provided_treatment],
	[hospitalized],
	[recordable],
	[recordable_classification],
	[start_date_and_time_of_investigation],
	[end_date_and_time_of_investigation],
	[investigator],
	[additional_investigators],
	[hipo_2],
	[incident_owner],
	[total_number_of_days_away],
	[total_number_of_job_transfer],
	[total_number_of_restricted_days],
	[total_number_of_restricted_or_job_transfer_days],
	[date_approved],
	[approvers_comment],
	[approved_by],
	[workflowcurrent_stage],
	[workflowworkflow_status],
	[workflowstatus],
	[workflowcurrent_person_responsible]
	
from [dbo].[dim_entp_yardkpi_intelex_injury_illness] where active = 1;
GO