CREATE VIEW [dbo].[dim_entp_maps_authorised_user_active_v] AS select
[dim_entp_maps_authorised_user_sk]
,[dim_entp_maps_authorised_user_nk]
,[auth_user_id] as [Auth User Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[db_id] as [Database Id]
,[mail_box_id] as [Mail Box Id]
,[full_name] as [Full Name]
,[person_id_number] as [Person Id Number]
,[profile_auth_user_id] as [Profile Auth User Id]
,[profile_user] as [Profile User]
,[obsolete_user] as [Obsolete User]
,[profile_type] as [Profile Type]
,[profile_hidden] as [Profile Hidden]
FROM [dbo].[dim_entp_maps_authorised_user] where active = 1;
GO


CREATE VIEW [dbo].[dim_entp_maps_correspondence_active_v] AS select
[dim_entp_maps_correspondence_sk]
,[dim_entp_maps_correspondence_nk]
,[ch_id] as [Ch Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[correspondence_date] as [Correspondence Date]
,[actioned_by] as [Actioned By]
,[file_reference] as [File Reference] 
,[file_location] as [File Location]
,[link_to_entity_id] as [Link To Entity Id]
,[entity_name] as [Entity Name]
,[notes] as [Notes]
,[status_id] as [Status Id]
,[correspondence_type_id] as [Correspondence Type Id]
,[printed] as [Printed]
,[emailed_to] as [Emailed To]
,[itemtag_id] as [Item Tag Id]
,[itemdb_id] as [Itemdb Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[activity_db] as [Activity Db]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[dim_entp_maps_reason_nk]
FROM [dbo].[dim_entp_maps_correspondence] where active = 1;
GO


CREATE VIEW [dbo].[dim_entp_maps_employ_noneffect_active_v] AS select
[dim_entp_maps_employ_noneffect_sk]
,[dim_entp_maps_employ_noneffect_nk]
,[noneff_id] as [Noneff Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[staff_number] as [Staff Number]
,[noneff_sdate] as [Noneff Sdate]
,[noneff_reas] as [Noneff Reas]
,[noneff_edate] as [Noneff Edate]
,[noneff_state] as [Noneff State]
,[noneff_payable] as [Noneff Payable]
,[noneff_notes] as [Noneff Notes]
,[medically_certified] as [Medically Certified]
,[self_certified] as [Self Certified]
,[reas_type] as [Reas Type]
,[noneff_planned] as [Noneff Planned]
,[itemtag_id] as [Item Tag Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[itemdb_id] as [Itemdb Id]
,[activity_db] as [Activity Db]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[posting_id] as [Posting Id]
,[accrues_leave] as [Accrues Leave]
,[account_code] as [Account Code]
,[expected_well_date] as [Expected Well Date]
,[dim_entp_maps_person_nk]
,[dim_entp_maps_reasons_nk]
FROM [dbo].[dim_entp_maps_employ_noneffect] where active = 1;
GO


CREATE VIEW [dbo].[dim_entp_maps_employee_skill_active_v] AS select
[dim_entp_maps_employee_skill_sk]
,[dim_entp_maps_employee_skill_nk]
,[staff_number] as [Staff Number]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[pers_skill_text] as [Pers Skill Text]
,[itemtag_id] as [Item Tag Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[itemdb_id] as [Itemdb Id]
,[activity_db] as [Activity Db]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[dim_entp_maps_person_nk]
FROM [dbo].[dim_entp_maps_employee_skill] where active = 1;
GO


CREATE VIEW [dbo].[dim_entp_maps_grade_active_v] AS select
[dim_entp_maps_grade_sk]
,[dim_entp_maps_grade_nk]
,[itemtag_id] as [Item Tag Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[grade_sht_title] as [Grade Sht Title]
,[occ_sht_title] as [Occ Sht Title]
,[contract_type] as [Contract Type]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[grade_equiv] as [Grade Equiv]
,[grade_fl_title] as [Grade Fl Title]
,[mob_ind] as [Mob Ind]
,[dft_asr_ye_day] as [Dft Asr Ye Day]
,[dft_asr_ye_mth] as [Dft Asr Ye Mth]
,[dft_asr_iss_day] as [Dft Asr Iss Day]
,[dft_asr_iss_mth] as [Dft Asr Iss Mth]
,[dft_asr_rtn_day] as [Dft Asr Rtn Day]
,[dft_asr_rtn_mth] as [Dft Asr Rtn Mth]
,[dft_asr_des_day] as [Dft Asr Des Day]
,[dft_asr_des_mth] as [Dft Asr Des Mth]
,[allowance] as [Allowance]
,[itemdb_id] as [Itemdb Id]
,[activity_db] as [Activity Db]
,[valid_from_date] as [Valid From Date]
,[valid_to_date] as [Valid To Date]
,[grade_type_id] as [Grade Type Id]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
FROM [dbo].[dim_entp_maps_grade] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_org_name_history_active_v] AS select
[dim_entp_maps_org_name_history_sk]
,[dim_entp_maps_org_name_history_nk]
,[org_name_history_id] as [Org Name History Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[ou_id] as [Ou Id]
,[valid_from_date] as [Valid From Date]
,[valid_to_date] as [Valid To Date]
,[ou_fl_title] as [Ou Fl Title]
,[ou_sht_title] as [Ou Sht Title]
,[itemtag_id] as [Item Tag Id]
,[itemdb_id] as [Itemdb Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[activity_db] as [Activity Db]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[ou_primary_site] as [Ou Primary Site]
FROM [dbo].[dim_entp_maps_org_name_history] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_passport_active_v] AS select
[dim_entp_maps_passport_sk]
,[dim_entp_maps_passport_nk]
,[passport_id] as [Passport Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[id_number] as [Id Number]
,[country_id] as [Country Id]
,[passport_number] as [Passport Number]
,[passport_expiry_date] as [Passport Expiry Date]
,[issuing_office] as [Issuing Office]
,[place_of_birth] as [Place Of Birth]
,[valid_from_date] as [Valid From Date]
,[valid_to_date] as [Valid To Date]
,[passport_type_reason_id] as [Passport Type Reason Id]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[itemdb_id] as [Itemdb Id]
,[itemtag_id] as [Item Tag Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_db] as [Activity Db]
,[activity_id] as [Activity Id]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[dim_entp_maps_person_nk]
FROM [dbo].[dim_entp_maps_passport] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_person_active_v] AS select
[dim_entp_maps_person_sk]
,[dim_entp_maps_person_nk]
,[id_number] as [Id Number]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[prfscid_code] as [Prfscid Code]
,[pleave_rtype] as [Pleave Rtype]
,[leave_reas] as [Leave Reas]
,[title_rank] as [Title Rank]
,[surname] as [Surname]
,[forenames] as [Forenames]
,[initials] as [Initials]
,[date_leaving] as [Date Leaving]
,[part_time_acceptable] as [Part Time Acceptable]
,[part_time] as [Part Time]
,[part_time_hours] as [Part Time Hours]
,[date_joined] as [Date Joined]
,[extra_code_1] as [Extra Code 1]
,[extra_code_2] as [Extra Code 2]
,[person_type] as [Person Type]
,[grade_sht_title] as [Grade Sht Title]
,[dim_entp_maps_grade_nk]
,[tkt_grd_sht_title] as [Tkt Grd Sht Title]
,[employee_type] as [Employee Type]
,[sex] as [Sex]
,[date_birth] as [Date Birth]
,[marital_status] as [Marital Status]
,[surplus_sdate] as [Surplus Sdate]
,[supern_sdate] as [Supern Sdate]
,[date_ott_dus] as [Date Ott Dus]
,[promotion_ryear] as [Promotion Ryear]
,[eret_date] as [Eret Date]
,[ret_date] as [Ret Date]
,[ret_dec] as [Ret Dec]
,[asr_despatch] as [Asr Despatch]
,[asr_issue] as [Asr Issue]
,[asr_actual_return] as [Asr Actual Return]
,[date_av_post] as [Date Av Post]
,[disabled_number] as [Disabled Number]
,[seniority_date] as [Seniority Date]
,[comp_name] as [Comp Name]
,[date_contract] as [Date Contract]
,[student_type_id] as [Student Type Id]
,[dietary_requirements] as [Dietary Requirements]
,[special_needs] as [Special Needs]
,[country_of_orgin] as [Country Of Orgin]
,[telephone_number] as [Telephone Number]
,[students_company] as [Students Company]
,[notes] as [Notes]
,[previous_employee] as [Previous Employee]
,[applicant_id] as [Applicant Id]
,[blood_type] as [Blood Type]
,[e_mail_name] as [Email Name]
,[sob_type_id] as [Sob Type Id]
,[lifetime_sob] as [Lifetime Sob]
,[nationality_id] as [Nationality Id]
,[dim_entp_maps_person_nationality_nk]
,[person_check_box_1] as [Person Check Box 1]
,[person_check_box_2] as [Person Check Box 2]
,[person_check_box_3] as [Person Check Box 3]
,[companion_id_number] as [Companion Id Number]
,[is_smoker] as [Is Smoker]
,[travel_provider_id] as [Travel Provider Id]
,[hair_reason_id] as [Hair Reason Id]
,[eye_reason_id] as [Eye Reason Id]
,[person_weight] as [Person Weight]
,[person_height] as [Person Height]
,[shoe_size] as [Shoe Size]
,[uniform_size] as [Uniform Size]
,[place_of_birth] as [Place Of Birth]
,[itemtag_id] as [Item Tag Id]
,[itemdb_id] as [Itemdb Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[activity_db] as [Activity Db]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[country_of_birth_id] as [Country Of Birth Id]
,[person_known_as] as [Person Known As]
,[employ_type_name] as [Employ Type Name]
,[employ_type_desc] as [Employ Type Desc]
FROM [dbo].[dim_entp_maps_person] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_person_nationality_active_v] AS select
[dim_entp_maps_person_nationality_sk]
,[dim_entp_maps_person_nationality_nk]
,[Nationality_Id] as [Nationality Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[name] as [Name]
,[description] as [Description]
,[nationality_code] as [Nationality Code]
,[itemtag_id] as [Item Tag Id]
,[itemdb_id] as [Itemdb Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[activity_db] as [Activity Db]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
FROM [dbo].[dim_entp_maps_person_nationality] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_person_qualification_active_v] AS select
[dim_entp_maps_person_qualification_sk]
,[dim_entp_maps_person_qualification_nk]
,[ql_person_qual_id] as [Ql Person Qual Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[ql_qualification_id] as [Ql Qualification Id]
,[id_number] as [Id Number]
,[ql_authority_id] as [Ql Authority Id]
,[itemdb_id] as [Itemdb Id]
,[itemtag_id] as [Item Tag Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_db] as [Activity Db]
,[activity_id] as [Activity Id]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[valid_from_date] as [Valid From Date]
,[valid_to_date] as [Valid To Date]
,[certificate_number] as [Certificate Number]
,[vessel_flag_certificate] as [Vessel Flag Certificate]
,[issue_date] as [Issue Date]
,[expiry_date] as [Expiry Date]
,[person_qual_state_id] as [Person Qual State Id]
,[person_qual_type_id] as [Person Qual Type Id]
,[mandatory] as [Mandatory]
,[dim_entp_maps_person_nk]
,[dim_entp_maps_qualification_nk]
FROM [dbo].[dim_entp_maps_person_qualification] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_person_unit_active_v] AS select
[dim_entp_maps_person_unit_sk]
,[dim_entp_maps_person_unit_nk]
,[eo_id] as [Eo Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[id_number] as [Id Number]
,[ou_id] as [Ou Id]
,[member_no] as [Member No]
,[valid_from_date] as [Valid From Date]
,[valid_to_date] as [Valid To Date]
,[person_type_reason_id] as [Person Type Reason Id]
,[itemtag_id] as [Item Tag Id]
,[itemdb_id] as [Itemdb Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[activity_db] as [Activity Db]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[dim_entp_maps_person_nk]
,[dim_entp_maps_reason_nk]
,[dim_entp_maps_org_name_history_nk]
FROM [dbo].[dim_entp_maps_person_unit] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_person_vaccination_active_v] AS select
[dim_entp_maps_person_vaccination_sk]
,[dim_entp_maps_person_vaccination_nk]
,[person_vaccination_id] as [Person Vaccination Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[vaccination_id] as [Vaccination Id]
,[id_number] as [Id Number]
,[date] as [Date]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[itemdb_id] as [Itemdb Id]
,[itemtag_id] as [Item Tag Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_db] as [Activity Db]
,[activity_id] as [Activity Id]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[dim_entp_maps_person_nk]
,[dim_entp_maps_vaccination_nk]
FROM [dbo].[dim_entp_maps_person_vaccination] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_post_active_v] AS select
[dim_entp_maps_post_sk]
,[dim_entp_maps_post_nk]
,[ou_id] as [Ou Id]
,[post_id] as [Post Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[cpma_uin_id] as [Cpma Uin Id]
,[prfscid_code] as [Prfscid Code]
,[subprfscid_code] as [Subprfscid Code]
,[job_group] as [Job Group]
,[job_function1] as [Job Function 1]
,[job_function2] as [Job Function 2]
,[job_function3] as [Job Function 3]
,[epost_rtype] as [Epost Rtype]
,[epost_reas] as [Epost Reas]
,[post_category] as [Post Category]
,[post_title] as [Post Title]
,[grade_equiv] as [Grade Equiv]
,[public_service] as [Public Service]
,[part_tm_ind] as [Part Tm Ind]
,[collocation_ind] as [Collocation Ind]
,[post_sdate] as [Post Sdate]
,[post_edate] as [Post Edate]
,[sob_required] as [Sob Required]
,[wte_hrs] as [Wte Hrs]
,[template_post_id] as [Template Post Id]
,[itemtag_id] as [Item Tag Id]
,[activity_db] as [Activity Db]
,[last_edit_by] as [Last Edit By]
,[itemdb_id] as [Itemdb Id]
,[activity_id] as [Activity Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[post_type_id] as [Post Type Id]
,[extra_code_1] as [Extra Code 1]
,[extra_code_2] as [Extra Code 2]
,[notes] as [Notes]
,[job_description] as [Job Description]
,[jd_file_pointer] as [Jd File Pointer]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[role_id] as [Role Id]
FROM [dbo].[dim_entp_maps_post] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_post_location_active_v] AS select
[dim_entp_maps_post_location_sk]
,[dim_entp_maps_post_location_nk]
,[post_id] as [Post Id]
,[post_loc_sdate] as [Post Loc Sdate]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[site_name] as [Site Name]
,[build_name] as [Build Name]
,[room_no] as [Room No]
,[itemtag_id] as [Item Tag Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[spur] as [Spur]
,[post_loc_edate] as [Post Loc Edate]
,[itemdb_id] as [Itemdb Id]
,[activity_db] as [Activity Db]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
FROM [dbo].[dim_entp_maps_post_location] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_posting_active_v] AS select
[dim_entp_maps_posting_sk]
,[dim_entp_maps_posting_nk]
,[posting_id] as [Posting Id]
,[post_id] as [Post Id]
,[id_number] as [Id Number]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[org_group_id] as [Org Group Id]
,[posting_sdate] as [Posting Sdate]
,[epostg_rtype] as [Epostg Rtype]
,[posting_ereas] as [Posting Ereas]
,[posting_edate] as [Posting Edate]
,[posting_rdate] as [Posting Rdate]
,[part_time_hrs] as [Part Time Hrs]
,[pg_type_id] as [Pg Type Id]
,[fall_back_post_id] as [Fall Back Post Id]
,[notes] as [Notes]
,[carry_over_leave] as [Carry Over Leave]
,[leave_taken] as [Leave Taken]
,[liquidated_leave] as [Liquidated Leave]
,[last_calc_on] as [Last Calc On]
,[calc_for_date] as [Calc For Date]
,[leave_accrued] as [Leave Accrued]
,[probationary_period] as [Probationary Period]
,[confirmed_start_date] as [Confirmed Start Date]
,[confirmed_end_date] as [Confirmed End Date]
,[sob_person_id] as [Sob Person Id]
,[posting_extra_code_1] as [Posting Extra Code 1]
,[posting_extra_code_2] as [Posting Extra Code 2]
,[is_suspect] as [Is Suspect]
,[suspect_date] as [Suspect Date]
,[temp_pwc_id] as [Temp Pwc Id]
,[transit_days_before] as [Transit Days Before]
,[transit_days_after] as [Transit Days After]
,[posting_check_box_1] as [Posting Check Box 1]
,[posting_check_box_2] as [Posting Check Box 2]
,[travel_required] as [Travel Required]
,[posting_start_reason_id] as [Posting Start Reason Id]
,[itemtag_id] as [Item Tag Id]
,[itemdb_id] as [Itemdb Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[activity_db] as [Activity Db]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[orig_post_id] as [Orig Post Id]
,[dim_entp_maps_person_nk]
,[dim_entp_maps_post_nk]
,[dim_entp_maps_post_location_nk]
,[dim_entp_maps_posting_location_nk]
,[dim_entp_maps_authorised_user_nk]
FROM [dbo].[dim_entp_maps_posting] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_posting_location_active_v] AS select
[dim_entp_maps_posting_location_sk]
,[dim_entp_maps_posting_location_nk]
,[posting_location_id] as [Posting Location Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[site_name] as [Site Name]
,[build_name] as [Build Name]
,[itemtag_id] as [Item Tag Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[spur] as [Spur]
,[room_no] as [Room No]
,[tel_exch] as [Tel Exch]
,[tel_ext] as [Tel Ext]
,[mailing_flag] as [Mailing Flag]
,[itemdb_id] as [Itemdb Id]
,[activity_db] as [Activity Db]
,[valid_from_date] as [Valid From Date]
,[valid_to_date] as [Valid To Date]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[posting_id] as [Posting Id]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
FROM [dbo].[dim_entp_maps_posting_location] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_qualification_active_v] AS select
[dim_entp_maps_qualification_sk]
,[dim_entp_maps_qualification_nk]
,[ql_qualification_id] as [Ql Qualification Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[ql_qualification_group_id] as [Ql Qualification Group Id]
,[role_dependant] as [Role Dependant]
,[qualification_name] as [Qualification Name]
,[ql_authority_id] as [Ql Authority Id]
,[qualification_desc] as [Qualification Desc]
,[expiry_duration_reason_id] as [Expiry Duration Reason Id]
,[expire_duration] as [Expire Duration]
,[itemdb_id] as [Itemdb Id]
,[itemtag_id] as [Item Tag Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_db] as [Activity Db]
,[activity_id] as [Activity Id]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[valid_from_date] as [Valid From Date]
,[valid_to_date] as [Valid To Date]
,[ql_group_name] as [Ql Group Name]
,[ql_group_description] as [Ql Group Description]
FROM [dbo].[dim_entp_maps_qualification] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_reason_active_v] AS select
[dim_entp_maps_reason_sk]
,[dim_entp_maps_reason_nk]
,[reason_id] as [Reason Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[reas_cat_id] as [Reas Cat Id]
,[reason_name] as [Reason Name]
,[reason_desc] as [Reason Desc]
,[reason_type] as [Reason Type]
,[reason_code_1] as [Reason Code 1]
,[reason_code_2] as [Reason Code 2]
,[reason_bit_1] as [Reason Bit 1]
,[reason_bit_2] as [Reason Bit 2]
,[reason_internal_name] as [Reason Internal Name]
,[valid_from_date] as [Valid From Date]
,[valid_to_date] as [Valid To Date]
,[itemtag_id] as [Item Tag Id]
,[itemdb_id] as [Itemdb Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[activity_db] as [Activity Db]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
FROM [dbo].[dim_entp_maps_reason] where active = 1;
GO



CREATE VIEW [dbo].[dim_entp_maps_reasons_active_v] AS select
[dim_entp_maps_reasons_sk]
,[dim_entp_maps_reasons_nk]
,[reas_code] as [Reas Code]
,[reas_type] as [Reas Type]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[itemtag_id] as [Item Tag Id]
,[reas_sht_name] as [Reas Sht Name]
,[nerg_id] as [Nerg Id]
,[affects_leave] as [Affects Leave]
,[itemdb_id] as [Itemdb Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_id] as [Activity Id]
,[reas_text] as [reas_text]
,[activity_db] as [Activity Db]
,[valid_from_date] as [Valid From Date]
,[valid_to_date] as [Valid To Date]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
FROM [dbo].[dim_entp_maps_reasons] where active = 1;
GO


CREATE VIEW [dbo].[dim_entp_maps_vaccination_active_v] AS select
[dim_entp_maps_vaccination_sk]
,[dim_entp_maps_vaccination_nk]
,[vaccination_id] as [Vaccination Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[vaccination_name] as [Vaccination Name]
,[course_length] as [Course Length]
,[form] as [Form]
,[effective_period] as [Effective Period]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[itemdb_id] as [Itemdb Id]
,[itemtag_id] as [Item Tag Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_db] as [Activity Db]
,[activity_id] as [Activity Id]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
FROM [dbo].[dim_entp_maps_vaccination] where active = 1;
GO


CREATE VIEW [dbo].[dim_entp_maps_visa_active_v] AS select
[dim_entp_maps_visa_sk]
,[dim_entp_maps_visa_nk]
,[visa_id] as [Visa Id]
,[start_date] as [Start Date]
,[end_date] as [End Date]
,[hash_code] as [Hash Code]
,[late_arrival_flag] as [Late Arrival Flag]
,[active] as [Active]
,[created_date_time] as [Created Date Time]
,[modified_date_time] as [Modified Date Time]
,[id_number] as [Id Number]
,[country_id] as [Country Id]
,[passport_id] as [Passport Id]
,[type] as [Type]
,[visa_number] as [Visa Number]
,[valid_from_date] as [Valid From Date]
,[valid_to_date] as [Valid To Date]
,[visa_issuing_office] as [Visa Issuing Office]
,[visa_entries] as [Visa Entries]
,[spare_char_1_255] as [Spare Char 1]
,[spare_char_1_100] as [Spare Char 2]
,[spare_char_1_50] as [Spare Char 3]
,[spare_int_1] as [Spare Int 1]
,[spare_int_2] as [Spare Int 2]
,[itemdb_id] as [Itemdb Id]
,[itemtag_id] as [Item Tag Id]
,[date_created] as [Date Created]
,[date_last_mod] as [Date Last Mod]
,[last_edit_by] as [Last Edit By]
,[activity_db] as [Activity Db]
,[activity_id] as [Activity Id]
,[b1m] as [B1m]
,[b2m] as [B2m]
,[b3m] as [B3m]
,[b4m] as [B4m]
,[b5m] as [B5m]
,[b6m] as [B6m]
,[b7m] as [B7m]
,[b8m] as [B8m]
,[dim_entp_maps_person_nk]
FROM [dbo].[dim_entp_maps_visa] where active = 1;
GO

