CREATE TABLE [gpd].[reprocess_P6_resource_spread_direct]
(
	[rssk] [int] IDENTITY(1,1) NOT NULL,
	[hash_code] [varchar](8000) NULL,
	[load_date_time] [datetime] NULL,
	[hid] [int] NULL,
	[Project] [varchar](100) NULL,
	[project_number] [varchar](100) NULL,
	[Project_Description] [varchar](2000) NULL,
	[Activity_ID] [varchar](55) NULL,
	[Activity_Name] [varchar](512) NULL,
	[Original_Duration] [varchar](100) NULL,
	[Actual_Duration] [varchar](100) NULL,
	[Remaining_Duration] [varchar](100) NULL,
	[Start] [varchar](55) NULL,
	[Finish] [varchar](55) NULL,
	[Actual_Start] [varchar](55) NULL,
	[Actual_Finish] [varchar](55) NULL,
	[Calendar] [varchar](100) NULL,
	[Budgeted_Units] [varchar](100) NULL,
	[Actual_Units] [varchar](100) NULL,
	[Remaining_Units] [varchar](100) NULL,
	[WBS] [varchar](100) NULL,
	[WBS_Name] [varchar](100) NULL,
	[Cost_Account] [varchar](100) NULL,
	[Role] [varchar](100) NULL,
	[Resource_ID] [varchar](300) NULL,
	[Resource_ID_Name] [varchar](500) NULL,
	[Resource_Name] [varchar](500) NULL,
	[Resource_Type] [varchar](300) NULL,
	[Change_Management] [varchar](50) NULL,
	[Executed_By_Type] [varchar](50) NULL,
	[Function] [varchar](50) NULL,
	[Milestones] [varchar](50) NULL,
	[Office] [varchar](50) NULL,
	[Phase] [varchar](50) NULL,
	[Region] [varchar](50) NULL,
	[Schedule_Risk_Assessment] [varchar](50) NULL,
	[Storage_Solutions] [varchar](50) NULL,
	[Supply_Chain] [varchar](50) NULL,
	[Prime] [varchar](100) NULL,
	[SubPrime] [varchar](100) NULL,
	[Spreadsheet_Field] [varchar](512) NULL,
	[Period] [varchar](55) NULL,
	[Units] [varchar](100) NULL,
	[fx] [nvarchar](100) NULL,
	[work_unit] [nvarchar](100) NULL,
	[work_area] [nvarchar](100) NULL,
	[cwp] [nvarchar](100) NULL,
	[schedule_resource] [nvarchar](100) NULL,
	[iwp] [nvarchar](100) NULL,
	[pim] [nvarchar](100) NULL,
	[roc] [nvarchar](100) NULL,
	[data_class] [nvarchar](100) NULL,
	[sub_source] [nvarchar](100) NULL,
	[source] [nvarchar](100) NULL,
	[unit_of_measure] [nvarchar](100) NULL,
	[Total Float] [varchar](120) NULL,
	[Free Float] [varchar](120) NULL,
	[BL Project Start]  [varchar](120) NULL,
	[BL Project Finish] [varchar](120) NULL,
	[Critical] [varchar](120) NULL,
	[Activity Type] [varchar](120) NULL,
	[Longest Path] [varchar](120) NULL,
	[Primary Constraint Date] [varchar](120) NULL,
	[Secondary Constraint Date] [varchar](120) NULL,
	[Primary Constraint] [varchar](120) NULL,
	[Secondary Constraint] [varchar](120) NULL,
	[Expected Finish] [varchar](120) NULL,
	[Suspend Date] [varchar](120) NULL,
	[Resume Date] [varchar](120) NULL,
	[BL Project Labor Units] [varchar](120) NULL,
	[Earned Value Labor Units] [varchar](120) NULL,
	[Planned Value Labor Units] [varchar](120) NULL,
	[BL Project Duration] [varchar](120) NULL,
	[Physical Percent Complete] [varchar](120) NULL,
	[Predecessors] [varchar](120) NULL,
	[Successors] [varchar](120) NULL,
	[Predecessor Details] [varchar](120) NULL,
	[Successors Details] [varchar](120) NULL,
	[Late Start] [varchar](120) NULL,
	[Late Finish] [varchar](120) NULL,
	[dim_entp_function_sk] [int] NULL,
	[dim_entp_function_nk] [int] NULL,
	[dim_entp_project_sk] [int] NULL,
	[dim_entp_project_nk] [int] NULL,
	[dim_entp_phase_sk] [int] NULL,
	[dim_entp_phase_nk] [int] NULL,
	[dim_entp_work_unit_sk] [int] NULL,
	[dim_entp_work_unit_nk] [int] NULL,
	[dim_entp_work_area_sk] [int] NULL,
	[dim_entp_work_area_nk] [int] NULL,
	[dim_entp_cwp_sk] [int] NULL,
	[dim_entp_cwp_nk] [int] NULL,
	[dim_entp_schedule_resource_sk] [int] NULL,
	[dim_entp_schedule_resource_nk] [int] NULL,
	[dim_entp_activity_resource_sk] [int] NULL,
	[dim_entp_activity_resource_nk] [int] NULL,
	[dim_entp_iwp_sk] [int] NULL,
	[dim_entp_iwp_nk] [int] NULL,
	[dim_entp_pim_sk] [int] NULL,
	[dim_entp_pim_nk] [int] NULL,
	[dim_entp_roc_sk] [int] NULL,
	[dim_entp_roc_nk] [int] NULL,
	[dim_entp_data_sub_class_sk] [int] NULL,
	[dim_entp_data_sub_class_nk] [int] NULL,
	[dim_entp_data_class_sk] [int] NULL,
	[dim_entp_data_class_nk] [int] NULL,
	[dim_entp_sub_source_sk] [int] NULL,
	[dim_entp_sub_source_nk] [int] NULL,
	[dim_entp_source_sk] [int] NULL,
	[dim_entp_source_nk] [int] NULL,
	[dim_entp_unit_of_measure_sk] [int] NULL,
	[dim_entp_unit_of_measure_nk] [int] NULL,
	[dim_entp_planning_resource_sk] [int] NULL,
	[dim_entp_planning_resource_nk] [int] NULL,
	[parent_rssk] [int] NULL,
	[rk_failure_info] [varchar](5000) NULL,
	[t_spreadsheet_field] [varchar](512) null,
	[final_spreadsheet_field] [varchar](512) null,
	[Plan Type] [varchar](120) NULL,
	[Plan Type Description] [varchar](120) NULL,
	[Version No] [int] NULL,
	[plantype_revision] [varchar](300) NULL,
	[data_sub_class] [nvarchar](500) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

