/****** Object:  Table [gpd].[reprocess_NCSA_Sitepro_Progress]    Script Date: 5/21/2021 3:00:20 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[gpd].[reprocess_NCSA_Sitepro_Progress]') AND type in (N'U'))
DROP TABLE [gpd].[reprocess_NCSA_Sitepro_Progress]
GO
/****** Object:  Table [gpd].[reprocess_NCSA_Sitepro_budget]    Script Date: 5/21/2021 3:00:20 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[gpd].[reprocess_NCSA_Sitepro_budget]') AND type in (N'U'))
DROP TABLE [gpd].[reprocess_NCSA_Sitepro_budget]
GO
/****** Object:  Table [gpd].[NCSA_Sitepro_Budget]    Script Date: 5/21/2021 3:00:20 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[gpd].[NCSA_Sitepro_Budget]') AND type in (N'U'))
DROP TABLE [gpd].[NCSA_Sitepro_Budget]
GO
/****** Object:  Table [gpd].[NCSA_Sitepro_Budget]    Script Date: 5/21/2021 3:00:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [gpd].[NCSA_Sitepro_Budget]
(
	[ncsa_sitepro_budget_id] [int] IDENTITY(1,1) NOT NULL,
	[Project_id] [varchar](120) NULL,
	[function_code] [varchar](50) NULL,
	[source_name] [varchar](100) NULL,
	[sub_source_name] [varchar](100) NULL,
	[class_name_hours] [varchar](100) NULL,
	[class_name_quantity] [varchar](100) NULL,
	[sub_class_name_qty] [varchar](100) NULL,
	[sub_class_name_hours] [varchar](100) NULL,
	[sub_class_plan] [varchar](100) NULL,
	[unit_of_measure_qty] [varchar](100) NULL,
	[unit_of_measure_hours] [varchar](100) NULL,
	[pim_code] [varchar](120) NULL,
	[roc_code] [varchar](120) NULL,
	[ROC_Step] [varchar](20) NULL,
	[Phase_Code] [varchar](120) NULL,
	[WorkArea_Code] [varchar](120) NULL,
	[WorkUnit_Code] [varchar](120) NULL,
	[ScheduleResource_Code] [varchar](120) NULL,
	[cwp_code] [varchar](120) NULL,
	[Activity] [varchar](120) NULL,
	[iwp_Code] [varchar](120) NULL,
	[Budget_date] [date] NULL,
	[budget_qty] [varchar](20) NULL,
	[budget_hours] [varchar](20) NULL,
	[PlannedHours] [varchar](20) NULL,
	[dim_ent_function_sk] [int] NULL,
	[dim_ent_function_nk] [int] NULL,
	[dim_ent_project_sk] [int] NULL,
	[dim_ent_project_nk] [int] NULL,
	[dim_ent_data_class_hours_sk] [int] NULL,
	[dim_ent_data_class_hours_nk] [int] NULL,
	[dim_ent_data_class_quantity_sk] [int] NULL,
	[dim_ent_data_class_quantity_nk] [int] NULL,
	[dim_ent_data_sub_class_hours_sk] [int] NULL,
	[dim_ent_data_sub_class_hours_nk] [int] NULL,
	[dim_ent_data_sub_class_qty_sk] [int] NULL,
	[dim_ent_data_sub_class_qty_nk] [int] NULL,
	[dim_ent_data_sub_class_plan_sk] [int] NULL,
	[dim_ent_data_sub_class_plan_nk] [int] NULL,
	[dim_ent_sub_source_sk] [int] NULL,
	[dim_ent_sub_source_nk] [int] NULL,
	[dim_ent_source_sk] [int] NULL,
	[dim_ent_source_nk] [int] NULL,
	[dim_ent_unit_of_measure_hours_nk] [int] NULL,
	[dim_ent_unit_of_measure_hours_sk] [int] NULL,
	[dim_ent_unit_of_measure_qty_nk] [int] NULL,
	[dim_ent_unit_of_measure_qty_sk] [int] NULL,
	[dim_entp_phase_sk] [int] NULL,
	[dim_entp_phase_nk] [int] NULL,
	[dim_entp_work_unit_sk] [int] NULL,
	[dim_entp_work_unit_nk] [int] NULL,
	[dim_entp_work_area_sk] [int] NULL,
	[dim_entp_work_area_nk] [int] NULL,
	[dim_entp_cwp_sk] [int] NULL,
	[dim_entp_cwp_nk] [int] NULL,
	[dim_entp_schedule_resource_sk] [int] NULL,
	[dim_entp_schedule_resource_nk] [int] NULL,
	[dim_entp_activity_nk] [int] NULL,
	[dim_entp_activity_sk] [int] NULL,
	[dim_entp_iwp_sk] [int] NULL,
	[dim_entp_iwp_nk] [int] NULL,
	[dim_entp_pim_nk] [int] NULL,
	[dim_entp_pim_sk] [int] NULL,
	[dim_entp_roc_sk] [int] NULL,
	[dim_entp_roc_nk] [int] NULL,
	[rk_failure_info] [varchar](5000) NULL,
	[contract] [varchar](120) NULL,
	[costcode] [varchar](120) NULL,
	[costcode_desription] [varchar](1000) NULL,
	[costtype] [varchar](120) NULL,
	[costingcoa] [varchar](120) NULL,
	[Description] [varchar](4000) NULL,
	[DrawingNo] [varchar](1000) NULL,
	[TagNo] [varchar](1000) NULL,
	[Spool] [varchar](500) NULL,
	[Line] [varchar](255) NULL,
	[spec] [varchar](500) NULL,
	[System] [varchar](500) NULL,
	[PieceMark] [varchar](255) NULL,
	[NumberOfPieces] [varchar](255) NULL,
	[Subsystem] [varchar](250) NULL,
	[text5] [varchar](2000) NULL,
	[Level6] [varchar](255) NULL,
	[PlannedStatus] [varchar](100) NULL,
	[ProgressStatus] [varchar](100) NULL,
	[dim_ent_jde_coa_nk] [int] NULL,
	[dim_ent_jde_coa_sk] [int] NULL,
	[coa_value] [varchar](100) NULL,
	[load_date_time] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
/****** Object:  Table [gpd].[reprocess_NCSA_Sitepro_budget]    Script Date: 5/21/2021 3:00:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [gpd].[reprocess_NCSA_Sitepro_budget]
(
	[rssk] [int] IDENTITY(1,1) NOT NULL,
	[Project_id] [varchar](120) NULL,
	[function_code] [varchar](50) NULL,
	[source_name] [varchar](100) NULL,
	[sub_source_name] [varchar](100) NULL,
	[class_name_hours] [varchar](100) NULL,
	[class_name_quantity] [varchar](100) NULL,
	[sub_class_name_qty] [varchar](100) NULL,
	[sub_class_name_hours] [varchar](100) NULL,
	[sub_class_plan] [varchar](100) NULL,
	[unit_of_measure_qty] [varchar](100) NULL,
	[unit_of_measure_hours] [varchar](100) NULL,
	[pim_code] [varchar](120) NULL,
	[roc_code] [varchar](120) NULL,
	[ROC_Step] [varchar](20) NULL,
	[Phase_Code] [varchar](120) NULL,
	[WorkArea_Code] [varchar](120) NULL,
	[WorkUnit_Code] [varchar](120) NULL,
	[ScheduleResource_Code] [varchar](120) NULL,
	[cwp_code] [varchar](120) NULL,
	[Activity] [varchar](120) NULL,
	[iwp_Code] [varchar](120) NULL,
	[Budget_date] [date] NULL,
	[budget_qty] [varchar](20) NULL,
	[budget_hours] [varchar](20) NULL,
	[PlannedHours] [varchar](20) NULL,
	[dim_ent_function_sk] [int] NULL,
	[dim_ent_function_nk] [int] NULL,
	[dim_ent_project_sk] [int] NULL,
	[dim_ent_project_nk] [int] NULL,
	[dim_ent_data_class_hours_sk] [int] NULL,
	[dim_ent_data_class_hours_nk] [int] NULL,
	[dim_ent_data_class_quantity_sk] [int] NULL,
	[dim_ent_data_class_quantity_nk] [int] NULL,
	[dim_ent_data_sub_class_hours_sk] [int] NULL,
	[dim_ent_data_sub_class_hours_nk] [int] NULL,
	[dim_ent_data_sub_class_qty_sk] [int] NULL,
	[dim_ent_data_sub_class_qty_nk] [int] NULL,
	[dim_ent_data_sub_class_plan_sk] [int] NULL,
	[dim_ent_data_sub_class_plan_nk] [int] NULL,
	[dim_ent_sub_source_sk] [int] NULL,
	[dim_ent_sub_source_nk] [int] NULL,
	[dim_ent_source_sk] [int] NULL,
	[dim_ent_source_nk] [int] NULL,
	[dim_ent_unit_of_measure_hours_nk] [int] NULL,
	[dim_ent_unit_of_measure_hours_sk] [int] NULL,
	[dim_ent_unit_of_measure_qty_nk] [int] NULL,
	[dim_ent_unit_of_measure_qty_sk] [int] NULL,
	[dim_entp_phase_sk] [int] NULL,
	[dim_entp_phase_nk] [int] NULL,
	[dim_entp_work_unit_sk] [int] NULL,
	[dim_entp_work_unit_nk] [int] NULL,
	[dim_entp_work_area_sk] [int] NULL,
	[dim_entp_work_area_nk] [int] NULL,
	[dim_entp_cwp_sk] [int] NULL,
	[dim_entp_cwp_nk] [int] NULL,
	[dim_entp_schedule_resource_sk] [int] NULL,
	[dim_entp_schedule_resource_nk] [int] NULL,
	[dim_entp_activity_nk] [int] NULL,
	[dim_entp_activity_sk] [int] NULL,
	[dim_entp_iwp_sk] [int] NULL,
	[dim_entp_iwp_nk] [int] NULL,
	[dim_entp_pim_nk] [int] NULL,
	[dim_entp_pim_sk] [int] NULL,
	[dim_entp_roc_sk] [int] NULL,
	[dim_entp_roc_nk] [int] NULL,
	[rk_failure_info] [varchar](5000) NULL,
	[contract] [varchar](120) NULL,
	[costcode] [varchar](120) NULL,
	[costcode_desription] [varchar](1000) NULL,
	[costtype] [varchar](120) NULL,
	[costingcoa] [varchar](120) NULL,
	[Description] [varchar](4000) NULL,
	[DrawingNo] [varchar](1000) NULL,
	[TagNo] [varchar](1000) NULL,
	[Spool] [varchar](500) NULL,
	[Line] [varchar](255) NULL,
	[spec] [varchar](500) NULL,
	[System] [varchar](500) NULL,
	[PieceMark] [varchar](255) NULL,
	[NumberOfPieces] [varchar](255) NULL,
	[Subsystem] [varchar](250) NULL,
	[text5] [varchar](2000) NULL,
	[Level6] [varchar](255) NULL,
	[PlannedStatus] [varchar](100) NULL,
	[ProgressStatus] [varchar](100) NULL,
	[dim_ent_jde_coa_nk] [int] NULL,
	[dim_ent_jde_coa_sk] [int] NULL,
	[coa_value] [varchar](100) NULL,
	[load_date_time] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
/****** Object:  Table [gpd].[reprocess_NCSA_Sitepro_Progress]    Script Date: 5/21/2021 3:00:20 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [gpd].[reprocess_NCSA_Sitepro_Progress]
(
	[rssk] [int] IDENTITY(1,1) NOT NULL,
	[project_number] [varchar](14) NULL,
	[function_code] [varchar](50) NULL,
	[source_code] [varchar](80) NULL,
	[sub_source_code] [varchar](80) NULL,
	[data_class_budget_code] [varchar](80) NULL,
	[data_class_progress_code] [varchar](80) NULL,
	[data_class_quantity_name] [varchar](80) NULL,
	[data_class_time_name] [varchar](80) NULL,
	[sub_class_budget_hours_code] [varchar](100) NULL,
	[sub_class_budget_quantity_code] [varchar](100) NULL,
	[sub_class_progress_hours_code] [varchar](100) NULL,
	[sub_class_progress_quantity_code] [varchar](100) NULL,
	[sub_class_progress_installed_quantity_code] [varchar](100) NULL,
	[unit_of_measure_code_quantity] [varchar](30) NULL,
	[unit_of_measure_code_hours] [varchar](30) NULL,
	[phase_code] [varchar](30) NULL,
	[schedule_resource_code] [varchar](30) NULL,
	[work_unit_code] [varchar](30) NULL,
	[work_area_code] [varchar](30) NULL,
	[activity_code] [varchar](100) NULL,
	[IWP_Code] [varchar](100) NULL,
	[IWP_Status_Code] [varchar](30) NULL,
	[IWP_StatusDescription] [varchar](255) NULL,
	[PMID] [varchar](50) NULL,
	[PMID_Description] [varchar](250) NULL,
	[Contract] [varchar](80) NULL,
	[Cost_Code] [varchar](80) NULL,
	[Cost_Code_Description] [varchar](255) NULL,
	[Costing_COA] [varchar](8) NULL,
	[Drawing_No] [varchar](255) NULL,
	[Tag_No] [varchar](255) NULL,
	[spool] [varchar](255) NULL,
	[line] [varchar](255) NULL,
	[spec] [varchar](255) NULL,
	[system] [varchar](255) NULL,
	[Piece_Mark] [varchar](255) NULL,
	[Cost_Type] [varchar](6) NULL,
	[Number_Of_Pieces] [varchar](255) NULL,
	[Subsystem] [varchar](255) NULL,
	[Text5] [varchar](255) NULL,
	[Bom_Node_ID] [varchar](30) NULL,
	[Doc_ID] [varchar](30) NULL,
	[Staging_Reference] [varchar](30) NULL,
	[Level6] [varchar](255) NULL,
	[planned_Status] [varchar](17) NULL,
	[progress_Status] [varchar](100) NULL,
	[workpack_status] [varchar](11) NULL,
	[IFC] [varchar](50) NULL,
	[ProgressHistoryID] [varchar](100) NULL,
	[ROCCode] [varchar](100) NULL,
	[Step] [varchar](30) NULL,
	[Is_Driving] [varchar](5) NULL,
	[Name] [varchar](250) NULL,
	[Capture_Origin] [varchar](100) NULL,
	[UserName] [varchar](101) NULL,
	[Progress_Entry_Date_Time] [varchar](100) NULL,
	[TimestampShift] [varchar](50) NULL,
	[ProgressDate] [varchar](100) NULL,
	[ProgressDelta] [varchar](100) NULL,
	[ProgressCumulative] [varchar](100) NULL,
	[Step_Percent] [varchar](100) NULL,
	[Budget_Hrs] [varchar](100) NULL,
	[Progressed_Hrs] [varchar](100) NULL,
	[Budget_Qty] [varchar](100) NULL,
	[Progressed_Qty] [varchar](100) NULL,
	[Install_Qty] [varchar](100) NULL,
	[max_date] [varchar](100) NULL,
	[dim_ent_function_sk] [int] NULL,
	[dim_ent_function_nk] [int] NULL,
	[dim_ent_project_sk] [int] NULL,
	[dim_ent_project_nk] [int] NULL,
	[dim_ent_data_class_budget_sk] [int] NULL,
	[dim_ent_data_class_budget_nk] [int] NULL,
	[dim_ent_data_class_progress_sk] [int] NULL,
	[dim_ent_data_class_progress_nk] [int] NULL,
	[dim_ent_data_class_quantity_sk] [int] NULL,
	[dim_ent_data_class_quantity_nk] [int] NULL,
	[dim_ent_data_class_time_sk] [int] NULL,
	[dim_ent_data_class_time_nk] [int] NULL,
	[dim_ent_data_sub_class_budget_hours_sk] [int] NULL,
	[dim_ent_data_sub_class_budget_hours_nk] [int] NULL,
	[dim_ent_data_sub_class_budget_quantity_sk] [int] NULL,
	[dim_ent_data_sub_class_budget_quantity_nk] [int] NULL,
	[dim_ent_data_sub_class_progress_hours_sk] [int] NULL,
	[dim_ent_data_sub_class_progress_hours_nk] [int] NULL,
	[dim_ent_data_sub_class_progress_quantity_sk] [int] NULL,
	[dim_ent_data_sub_class_progress_quantity_nk] [int] NULL,
	[dim_ent_data_sub_class_progress_installed_quantity_sk] [int] NULL,
	[dim_ent_data_sub_class_progress_installed_quantity_nk] [int] NULL,
	[dim_ent_sub_source_sk] [int] NULL,
	[dim_ent_sub_source_nk] [int] NULL,
	[dim_ent_source_sk] [int] NULL,
	[dim_ent_source_nk] [int] NULL,
	[dim_ent_unit_of_measure_quantity_nk] [int] NULL,
	[dim_ent_unit_of_measure_quantity_sk] [int] NULL,
	[dim_ent_unit_of_measure_hours_nk] [int] NULL,
	[dim_ent_unit_of_measure_hours_sk] [int] NULL,
	[dim_entp_phase_sk] [int] NULL,
	[dim_entp_phase_nk] [int] NULL,
	[dim_entp_work_unit_sk] [int] NULL,
	[dim_entp_work_unit_nk] [int] NULL,
	[dim_entp_work_area_sk] [int] NULL,
	[dim_entp_work_area_nk] [int] NULL,
	[dim_entp_cwp_sk] [int] NULL,
	[dim_entp_cwp_nk] [int] NULL,
	[dim_entp_schedule_resource_sk] [int] NULL,
	[dim_entp_schedule_resource_nk] [int] NULL,
	[dim_entp_activity_nk] [int] NULL,
	[dim_entp_activity_sk] [int] NULL,
	[dim_entp_iwp_sk] [int] NULL,
	[dim_entp_iwp_nk] [int] NULL,
	[dim_entp_pim_nk] [int] NULL,
	[dim_entp_pim_sk] [int] NULL,
	[dim_entp_roc_sk] [int] NULL,
	[dim_entp_roc_nk] [int] NULL,
	[CWP_Code] [varchar](80) NULL,
	[dim_ent_unit_of_measure_percentage_sk] [int] NULL,
	[dim_ent_unit_of_measure_percentage_nk] [int] NULL,
	[dim_ent_data_Percentage_sk] [int] NULL,
	[dim_ent_data_Percentage_nk] [int] NULL,
	[dim_ent_data_sub_Percentage_sk] [int] NULL,
	[dim_ent_data_sub_Percentage_nk] [int] NULL,
	[rk_failure_info] [varchar](5000) NULL,
	[coa_value] [varchar](100) NULL,
	[dim_ent_jde_coa_sk] [int] NULL,
	[dim_ent_jde_coa_nk] [int] NULL,
	[load_date_time] [datetime] NULL,
	[data_class_percentage_code] [varchar](100) NULL,
	[sub_class_percentage_code] [varchar](100) NULL,
	[unit_of_measure_code_percentage] [varchar](100) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
