/****** Object:  Table [gpd].[reprocess_NCSA_MCPM_ProgressItems_Onshore]    Script Date: 7/2/2021 1:28:18 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[gpd].[reprocess_NCSA_MCPM_ProgressItems_Onshore]') AND type in (N'U'))
DROP TABLE [gpd].[reprocess_NCSA_MCPM_ProgressItems_Onshore]
GO
/****** Object:  Table [gpd].[NCSA_MCPM_ProgressItems_Onshore]    Script Date: 7/2/2021 1:28:18 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[gpd].[NCSA_MCPM_ProgressItems_Onshore]') AND type in (N'U'))
DROP TABLE [gpd].[NCSA_MCPM_ProgressItems_Onshore]
GO
/****** Object:  Table [gpd].[NCSA_MCPM_ProgressItems_Onshore]    Script Date: 7/2/2021 1:28:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [gpd].[NCSA_MCPM_ProgressItems_Onshore]
(
	[stage_ncsa_mcpm_progress_items_onshore_id] [int] IDENTITY(1,1) NOT NULL,
	[Domain] [varchar](30) NULL,
	[KeyUoM] [varchar](5) NULL,
	[CutOff] [varchar](30) NULL,
	[CoA] [varchar](100) NULL,
	[EarnedQty] [varchar](30) NULL,
	[EarnedHrs] [varchar](30) NULL,
	[PrevEarnedQty] [varchar](30) NULL,
	[PrevEarnedHrs] [varchar](30) NULL,
	[VarianceEarnedQty] [varchar](30) NULL,
	[VarianceEarnedHrs] [varchar](30) NULL,
	[TakeOffQty] [varchar](30) NULL,
	[TakeOffHrs] [varchar](30) NULL,
	[ProgressBaseQty] [varchar](30) NULL,
	[ProgressBaseHrs] [varchar](30) NULL,
	[ProgressBaseAmt] [varchar](30) NULL,
	[ActualHrs] [varchar](30) NULL,
	[ActualAmt] [varchar](30) NULL,
	[Phase] [varchar](2) NULL,
	[Prime] [varchar](2) NULL,
	[SubPrime] [varchar](3) NULL,
	[CostCode] [varchar](5) NULL,
	[Contract] [varchar](30) NULL,
	[WorkArea] [varchar](3) NULL,
	[SummaryCostType] [varchar](5) NULL,
	[CostType] [varchar](5) NULL,
	[OriginalHrs] [varchar](30) NULL,
	[OriginalQty] [varchar](30) NULL,
	[OriginalAmt] [varchar](30) NULL,
	[dim_ent_project_sk] [int] NULL,
	[dim_ent_project_nk] [int] NULL,
	[dim_ent_jde_coa_sk] [int] NULL,
	[dim_ent_jde_coa_nk] [int] NULL,
	[dim_ent_work_unit_sk] [int] NULL,
	[dim_ent_work_unit_nk] [int] NULL,
	[dim_ent_work_area_sk] [int] NULL,
	[dim_ent_work_area_nk] [int] NULL,
	[dim_entp_phase_sk] [int] NULL,
	[dim_entp_phase_nk] [int] NULL,
	[dim_ent_function_sk] [int] NULL,
	[dim_ent_function_nk] [int] NULL,
	[dim_entp_cwp_sk] [int] NULL,
	[dim_entp_cwp_nk] [int] NULL,
	[dim_entp_schedule_resource_sk] [int] NULL,
	[dim_entp_schedule_resource_nk] [int] NULL,
	[dim_entp_activity_sk] [int] NULL,
	[dim_entp_activity_nk] [int] NULL,
	[dim_entp_iwp_sk] [int] NULL,
	[dim_entp_iwp_nk] [int] NULL,
	[dim_entp_pim_sk] [int] NULL,
	[dim_entp_pim_nk] [int] NULL,
	[dim_entp_roc_sk] [int] NULL,
	[dim_entp_roc_nk] [int] NULL,
	[dim_ent_data_class_quantity_sk] [int] NULL,
	[dim_ent_data_class_quantity_nk] [int] NULL,
	[dim_ent_data_class_hours_sk] [int] NULL,
	[dim_ent_data_class_hours_nk] [int] NULL,
	[dim_ent_source_sk] [int] NULL,
	[dim_ent_source_nk] [int] NULL,
	[dim_ent_sub_source_sk] [int] NULL,
	[dim_ent_sub_source_nk] [int] NULL,
	[dim_ent_unit_of_measure_quantity_sk] [int] NULL,
	[dim_ent_unit_of_measure_quantity_nk] [int] NULL,
	[dim_ent_unit_of_measure_hours_sk] [int] NULL,
	[dim_ent_unit_of_measure_hours_nk] [int] NULL,
	[load_date_time] [datetime] NULL,
	[cwp_code] [varchar](50) NULL,
	[schedule_resource_code] [varchar](100) NULL,
	[activity_code] [varchar](50) NULL,
	[iwp_code] [varchar](50) NULL,
	[pim_code] [varchar](50) NULL,
	[roc_code] [varchar](50) NULL,
	[function_code] [varchar](50) NULL,
	[source_code] [varchar](50) NULL,
	[sub_source_code] [varchar](50) NULL,
	[dim_ent_data_sub_class_variance_earned_quantity_sk] [int] NULL,
	[dim_ent_data_sub_class_variance_earned_quantity_nk] [int] NULL,
	[dim_ent_data_sub_class_variance_earned_hours_sk] [int] NULL,
	[dim_ent_data_sub_class_variance_earned_hours_nk] [int] NULL,
	[sub_class_earned_variance_quantity_code] [varchar](100) NULL,
	[sub_class_earned_variance_hours_code] [varchar](100) NULL,
	[unit_of_measure_code_quantity] [varchar](50) NULL,
	[unit_of_measure_code_hours] [varchar](50) NULL,
	[data_class_quantity_code] [varchar](50) NULL,
	[data_class_hours_code] [varchar](50) NULL,
	[sub_class_earned_quantity_code] [varchar](100) NULL,
	[sub_class_earned_hours_code] [varchar](100) NULL,
	[dim_ent_data_sub_class_earned_quantity_sk] [int] NULL,
	[dim_ent_data_sub_class_earned_quantity_nk] [int] NULL,
	[dim_ent_data_sub_class_earned_hours_sk] [int] NULL,
	[dim_ent_data_sub_class_earned_hours_nk] [int] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
/****** Object:  Table [gpd].[reprocess_NCSA_MCPM_ProgressItems_Onshore]    Script Date: 7/2/2021 1:28:18 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [gpd].[reprocess_NCSA_MCPM_ProgressItems_Onshore]
(
	[rssk] [int] IDENTITY(1,1) NOT NULL,
	[created_date_time] [datetime] NULL,
	[Domain] [varchar](30) NULL,
	[KeyUoM] [varchar](5) NULL,
	[CutOff] [varchar](30) NULL,
	[CoA] [varchar](100) NULL,
	[EarnedQty] [varchar](30) NULL,
	[EarnedHrs] [varchar](30) NULL,
	[PrevEarnedQty] [varchar](30) NULL,
	[PrevEarnedHrs] [varchar](30) NULL,
	[VarianceEarnedQty] [varchar](30) NULL,
	[VarianceEarnedHrs] [varchar](30) NULL,
	[TakeOffQty] [varchar](30) NULL,
	[TakeOffHrs] [varchar](30) NULL,
	[ProgressBaseQty] [varchar](30) NULL,
	[ProgressBaseHrs] [varchar](30) NULL,
	[ProgressBaseAmt] [varchar](30) NULL,
	[ActualHrs] [varchar](30) NULL,
	[ActualAmt] [varchar](30) NULL,
	[Phase] [varchar](2) NULL,
	[Prime] [varchar](2) NULL,
	[SubPrime] [varchar](3) NULL,
	[CostCode] [varchar](5) NULL,
	[Contract] [varchar](30) NULL,
	[WorkArea] [varchar](3) NULL,
	[SummaryCostType] [varchar](5) NULL,
	[CostType] [varchar](5) NULL,
	[OriginalHrs] [varchar](30) NULL,
	[OriginalQty] [varchar](30) NULL,
	[OriginalAmt] [varchar](30) NULL,
	[dim_ent_project_sk] [int] NULL,
	[dim_ent_project_nk] [int] NULL,
	[dim_ent_jde_coa_sk] [int] NULL,
	[dim_ent_jde_coa_nk] [int] NULL,
	[dim_ent_work_unit_sk] [int] NULL,
	[dim_ent_work_unit_nk] [int] NULL,
	[dim_ent_work_area_sk] [int] NULL,
	[dim_ent_work_area_nk] [int] NULL,
	[dim_entp_phase_sk] [int] NULL,
	[dim_entp_phase_nk] [int] NULL,
	[dim_ent_function_sk] [int] NULL,
	[dim_ent_function_nk] [int] NULL,
	[dim_entp_cwp_sk] [int] NULL,
	[dim_entp_cwp_nk] [int] NULL,
	[dim_entp_schedule_resource_sk] [int] NULL,
	[dim_entp_schedule_resource_nk] [int] NULL,
	[dim_entp_activity_sk] [int] NULL,
	[dim_entp_activity_nk] [int] NULL,
	[dim_entp_iwp_sk] [int] NULL,
	[dim_entp_iwp_nk] [int] NULL,
	[dim_entp_pim_sk] [int] NULL,
	[dim_entp_pim_nk] [int] NULL,
	[dim_entp_roc_sk] [int] NULL,
	[dim_entp_roc_nk] [int] NULL,
	[dim_ent_data_class_quantity_sk] [int] NULL,
	[dim_ent_data_class_quantity_nk] [int] NULL,
	[dim_ent_data_class_hours_sk] [int] NULL,
	[dim_ent_data_class_hours_nk] [int] NULL,
	[dim_ent_source_sk] [int] NULL,
	[dim_ent_source_nk] [int] NULL,
	[dim_ent_sub_source_sk] [int] NULL,
	[dim_ent_sub_source_nk] [int] NULL,
	[dim_ent_unit_of_measure_quantity_sk] [int] NULL,
	[dim_ent_unit_of_measure_quantity_nk] [int] NULL,
	[dim_ent_unit_of_measure_hours_sk] [int] NULL,
	[dim_ent_unit_of_measure_hours_nk] [int] NULL,
	[load_date_time] [datetime] NULL,
	[cwp_code] [varchar](50) NULL,
	[schedule_resource_code] [varchar](100) NULL,
	[activity_code] [varchar](50) NULL,
	[iwp_code] [varchar](50) NULL,
	[pim_code] [varchar](50) NULL,
	[roc_code] [varchar](50) NULL,
	[function_code] [varchar](50) NULL,
	[source_code] [varchar](50) NULL,
	[sub_source_code] [varchar](50) NULL,
	[dim_ent_data_sub_class_variance_earned_quantity_sk] [int] NULL,
	[dim_ent_data_sub_class_variance_earned_quantity_nk] [int] NULL,
	[dim_ent_data_sub_class_variance_earned_hours_sk] [int] NULL,
	[dim_ent_data_sub_class_variance_earned_hours_nk] [int] NULL,
	[sub_class_earned_variance_quantity_code] [varchar](100) NULL,
	[sub_class_earned_variance_hours_code] [varchar](100) NULL,
	[unit_of_measure_code_quantity] [varchar](50) NULL,
	[unit_of_measure_code_hours] [varchar](50) NULL,
	[data_class_quantity_code] [varchar](50) NULL,
	[data_class_hours_code] [varchar](50) NULL,
	[sub_class_earned_quantity_code] [varchar](100) NULL,
	[sub_class_earned_hours_code] [varchar](100) NULL,
	[dim_ent_data_sub_class_earned_quantity_sk] [int] NULL,
	[dim_ent_data_sub_class_earned_quantity_nk] [int] NULL,
	[dim_ent_data_sub_class_earned_hours_sk] [int] NULL,
	[dim_ent_data_sub_class_earned_hours_nk] [int] NULL,
	[hash_code] [varchar](8000) NULL,
	[rk_failure_info] [varchar](5000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
