SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--DROP VIEW [dbo].[dim_entp_yardkpi_intelex_nonconformance_v]
CREATE VIEW [dbo].[dim_entp_yardkpi_intelex_nonconformance_v]
AS select 
	[dim_entp_yardkpi_intelex_nonconformance_sk] 
	,[dim_entp_yardkpi_intelex_nonconformance_nk]
	,[start_date]
	,[end_date]
	,[hash_code]
	,[active]
	,[created_date_time] 
	,[modified_date_time] 
	,[late_arrival_flag] 
	,[dim_ent_source_nk]
	,[dim_ent_sub_source_nk] 
	,[row_id] 
	,[ncr_no] 
	,[date_created]
	,[date_closed]
	,[location] 
	,[profile_type]
	,[profile] 
	,[product_line]
	,[ncr_type] 
	,[issued_to] 
	,[specify_regulatory_agency_issued_to] 
	,[issued_by]
	,[specify_regulatory_agency_issued_by]
	,[client_ncr_no]
	,[issue] 
	,[description]
	,[requirement] 
	,[area_of_project] 
	,[vessel]
	,[function_name] 
	,[product_activity]
	,[defect_code]
	,[units_affected]
	,[seriallot_no]
	,[immediate_action]
	,[recommended_action] 
	,[identified_by]
	,[reported_by] 
	,[date_reported]
	,[project_phase] 
	,[supplier] 
	,[return_material_authorization_no] 
	,[is_this_recurrence] 
	,[suspected_cause]
	,[probability]
	,[detection] 
	,[criticality]
	,[rpn]
	,[responsible_for_disposition] 
	,[disposition_due_date]
	,[reviewer_comments]
	,[cancel_comments] 
	,[disposition]
	,[client_approval_required] 
	,[qty_used_as_is]
	,[used_as_is_comments]
	,[dispositioner_action_plan_recommendations] 
	,[disposition_completed_date] 
	,[action_verification_due_date]
	,[dispositioner_comments]
	,[verification_due_date]
	,[verification_by] 
	,[verification_notes] 
	,[verification_date]
	,[workflowcurrent_stage]
	,[workflowstatus]
	
from [dbo].[dim_entp_yardkpi_intelex_nonconformance] where active = 1;
GO

