
alter table dim_ent_data_sub_class add gpd_level varchar(25)
go

update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Actual Amount'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Actual Hours'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Actual Rate'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Committed Amount'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Current Budget Amount'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Current Budget Hours'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Current Budget Quantity'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Earned Amount'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Earned Hours'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Earned Quantity'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Estimate At Completion Amount'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Estimate At Completion Hours'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Estimate To Complete Amount'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Estimate To Complete Hours'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Estimate To Complete Rate'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Original Budget Amount'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Original Budget Hours'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Original Budget Quantity'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Original Budget Rate'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Percentage Complete'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Progress Base Amount'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Progress Base Hours'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Progress Base Quantity'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Take-Off Hours'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Take-Off Quantity'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Variance Earned Hours'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Variance Earned Quantity'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Variance Earned Hours'
update dim_ent_data_sub_class  set gpd_level = 'BY JDE COA' where data_sub_class_name = 'Variance Earned Quantity'
update dim_ent_data_sub_class  set gpd_level = 'By Activity' where data_sub_class_name = 'At Completion Units'
update dim_ent_data_sub_class  set gpd_level = 'By Activity' where data_sub_class_name = 'Baseline Plan Hours 2019_11_16'
update dim_ent_data_sub_class  set gpd_level = 'By Activity' where data_sub_class_name = 'Baseline Plan Hours 2020_04_25'
update dim_ent_data_sub_class  set gpd_level = 'By Activity' where data_sub_class_name = 'Baseline Plan Hours 2020_12_26'
update dim_ent_data_sub_class  set gpd_level = 'By Activity' where data_sub_class_name = 'Earned Units'
update dim_ent_data_sub_class  set gpd_level = 'By Activity' where data_sub_class_name = 'Remaining Early Units'
update dim_ent_data_sub_class  set gpd_level = 'By Activity' where data_sub_class_name = 'Weekly Plan Hours'
update dim_ent_data_sub_class  set gpd_level = 'By Activity/IWP' where data_sub_class_name = '6 Week Look Ahead'
update dim_ent_data_sub_class  set gpd_level = 'By IWP' where data_sub_class_name = 'Sitepro Budget Hours'
update dim_ent_data_sub_class  set gpd_level = 'By IWP' where data_sub_class_name = 'Sitepro Budget Quantity'
update dim_ent_data_sub_class  set gpd_level = 'By IWP' where data_sub_class_name = 'Sitepro Earned Hours'
update dim_ent_data_sub_class  set gpd_level = 'By IWP' where data_sub_class_name = 'Sitepro Earned Quantity'
update dim_ent_data_sub_class  set gpd_level = 'By IWP' where data_sub_class_name = 'Sitepro Installed Quantity'
update dim_ent_data_sub_class  set gpd_level = 'By IWP' where data_sub_class_name = 'Sitepro Planned Hours'
update dim_ent_data_sub_class  set gpd_level = 'By IWP' where data_sub_class_name = 'Sitepro Spent Hours'

go
