
--@AK for P6 office
INSERT INTO [dbo].[generic_load_header]
           ([load_name]
           ,[description]
           ,[stage_table_name]
           ,[target_table_name]
           ,[reprocess_table_name]
           ,[target_sk_name]
           ,[target_gnk_name]
           ,[stage_sk_name]
           ,[glt_id]
           ,[active_flag]
          ,load_type)
     VALUES('dim_ent_office','Load P6 Office codes to dim table','[gpd].[P6_codes_office_v]','dim_ent_office','gpd.reprocess_dim_ent_office','dim_ent_office_sk','dim_ent_office_nk','stage_p6_codes_office_id','13','Y','DIMENSION')



INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES('dim_ent_office','Code_Value','varchar(10)','TEXT','NK','office_code',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'1','Y',NULL)

INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES('dim_ent_office','Description','varchar(100)','TEXT','OA','office_description',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2','Y',NULL)

INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES('dim_ent_office','alternative_office_code','varchar(5000)','TEXT','OA','alternative_office_code',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'3','Y',NULL)