SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--DROP VIEW [dbo].[dim_entp_yardkpi_tabware_wo_v]
CREATE VIEW [dbo].[dim_entp_yardkpi_tabware_wo_v]
AS select [dim_entp_yardkpi_tabware_wo_sk]
	,[dim_entp_yardkpi_tabware_wo_nk]
	,[start_date] 
	,[end_date] 
	,[hash_code]
	,[active]
	,[created_date_time] 
	,[modified_date_time] 
	,[late_arrival_flag]
	,[dim_ent_source_nk] 
	,[dim_ent_sub_source_nk]
	,[equipment]
	,[equipment_class]
	,[entered_date]
	,[requested_completion]
	,[completed_date]
	,[last_modified]
	,[wo_status]
	,[work_class]
	,[iso9000]
	,[workers]
	,[wo_planned_hours]
	,[down_hours]
	,[res_planned_hours]
	,[actual_hours]
	,[planned_hours_total]
	,[internal_labor]
	,[contract_labor]
	,[internal_nonstock]
	,[contract_nonstock]
	,[stores_material]
	,[wo_services]
	,[internal_tool]
	,[contract_tool]
	,[internal_other]
	,[contract_other]
	,[wo_base]
	,[wo_task]
	,[wo_subtask]
	,[failure_flag]
	,[planned_labor]
	,[planned_nonstock]
	,[planned_stores]
	,[planned_services]
	,[planned_tools]
	,[plant]
from [dbo].[dim_entp_yardkpi_tabware_wo] where active = 1;
GO
