drop table epr.BIR_Global_Expediting_Report_Ummshaif_D7650




/****** Object:  Table [epr].[BIR_Global_Expediting_Report_Ummshaif_D7650]    Script Date: 3/6/2025 1:46:00 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [epr].[BIR_Global_Expediting_Report_Ummshaif_D7650]
(
	[Project]   varchar(200) NULL,
[Discipline]   varchar(200) NULL,
[Requisition No]   varchar(4000) NULL,
[Req Supp]   varchar(200) NULL,
[Req LI]   varchar(200) NULL,
[Req Sub LI]   varchar(200) NULL,
[PO No]   varchar(200) NULL,
[PO Rev No]   varchar(200) NULL,
[Description]   varchar(200) NULL,
[Issued]   varchar(200) NULL,
[Approved Date]   varchar(200) NULL,
[PO Status]   varchar(200) NULL,
[Supplier]   varchar(200) NULL,
[Supplier Name]   varchar(2000) NULL,
[Supplier City]   varchar(4000) NULL,
[Country of Origin]   varchar(200) NULL,
[Supplier Country]   varchar(4000) NULL,
[Expediting Level]   varchar(200) NULL,
[Inspection Level]   varchar(200) NULL,
[Pos]   varchar(200) NULL,
[Sub]   varchar(200) NULL,
[IS Pos]   varchar(200) NULL,
[IS Sub]   varchar(200) NULL,
[Ident Short Description]   varchar(4000) NULL,
[Ident Code]   varchar(4000) NULL,
[Client Ident Code]   varchar(4000) NULL,
[Tag Number]   varchar(200) NULL,
[Commodity Code]   varchar(200) NULL,
[Size1]   varchar(200) NULL,
[Size2]   varchar(200) NULL,
[Size3]   varchar(200) NULL,
[Size4]   varchar(200) NULL,
[Order Qty]   varchar(200) NULL,
[Item Ship Qty]   varchar(200) NULL,
[Received Qty]   varchar(200) NULL,
[Balance MRR Qty]   varchar(200) NULL,
[Qty Unit]   varchar(200) NULL,
[Item Ship Weight]   varchar(200) NULL,
[Total ISH Weight]   varchar(200) NULL,
[Weight Unit]   varchar(200) NULL,
[(Charge) Account Code]   varchar(200) NULL,
[Delivery Designation]   varchar(200) NULL,
[Routing Method]   varchar(200) NULL,
[Transit Days]   varchar(200) NULL,
[Incoterm]   varchar(200) NULL,
[Delivery Place]   varchar(200) NULL,
[Prom Contract]   varchar(200) NULL,
[Forecasted Delivery Date]   varchar(200) NULL,
[Contractual Float]   varchar(200) NULL,
[Pred On Site]   varchar(200) NULL,
[Req On Site]   varchar(200) NULL,
[ROS Float]   varchar(200) NULL,
[NOI Nr]   varchar(200) NULL,
[NOI Date]   varchar(200) NULL,
[NOI Qty]   varchar(200) NULL,
[NOI Destination]   varchar(200) NULL,
[NOI Plan]   varchar(200) NULL,
[NOI Fcst]   varchar(200) NULL,
[NOI Act]   varchar(200) NULL,
[IRC Nr]   varchar(200) NULL,
[IRC Approved Date]   varchar(200) NULL,
[IRC Qty]   varchar(200) NULL,
[Balance IRC Qty]   varchar(200) NULL,
[Act Insp Date]   varchar(200) NULL,
[IRC Destination]   varchar(200) NULL,
[IRC Plan]   varchar(200) NULL,
[IRC Fcst]   varchar(200) NULL,
[IRC Act]   varchar(200) NULL,
[Release Note Nr]   varchar(200) NULL,
[RN Date]   varchar(200) NULL,
[RN Qty]   varchar(200) NULL,
[Balance RN Qty]   varchar(200) NULL,
[RN Approved Date]   varchar(200) NULL,
[RN Delivery Date]   varchar(200) NULL,
[RN Ready Date]   varchar(200) NULL,
[Hand Over Destination]   varchar(200) NULL,
[Hand Over Plan]   varchar(200) NULL,
[Hand Over Fcst]   varchar(200) NULL,
[Hand Over Act]   varchar(200) NULL,
[1ST Ship Destination]   varchar(200) NULL,
[1ST Ship Plan]   varchar(200) NULL,
[1ST Ship Fcst]   varchar(200) NULL,
[1ST Ship Act]   varchar(200) NULL,
[2ND Ship Destination]   varchar(200) NULL,
[2ND Ship Plan]   varchar(200) NULL,
[2ND Ship Fcst]   varchar(200) NULL,
[2ND Ship Act]   varchar(200) NULL,
[3RD Ship Destination]   varchar(200) NULL,
[3RD Ship Plan]   varchar(200) NULL,
[3RD Ship Fcst]   varchar(200) NULL,
[3RD Ship Act]   varchar(200) NULL,
[Traffic Arr Destination]   varchar(200) NULL,
[Traffic Arr Plan]   varchar(200) NULL,
[Traffic Arr Fcst]   varchar(200) NULL,
[Traffic Arr Act]   varchar(200) NULL,
[Arr On Site Destination]   varchar(200) NULL,
[Arr On Site Plan]   varchar(200) NULL,
[Arr On Site Fcst]   varchar(200) NULL,
[Arr On Site Act]   varchar(200) NULL,
[Shipment Number]   varchar(200) NULL,
[MOC]   varchar(200) NULL,
[Transport No]   varchar(200) NULL,
[Departure Point]   varchar(200) NULL,
[Arrival Point]   varchar(200) NULL,
[Shipment ETD]   varchar(200) NULL,
[Shipment ATD]   varchar(200) NULL,
[Shipment ETA]   varchar(200) NULL,
[Shipment ATA]   varchar(200) NULL,
[No of Cont]   varchar(200) NULL,
[Pre-Ship MOC]   varchar(200) NULL,
[Pre-Ship Transport No]   varchar(200) NULL,
[Pre-Ship Dept Point]   varchar(200) NULL,
[Pre-Ship Arr Point]   varchar(200) NULL,
[Pre-Ship ETD]   varchar(200) NULL,
[Pre-Ship ATD]   varchar(200) NULL,
[Pre-Ship ETA]   varchar(200) NULL,
[Pre-Ship ATA]   varchar(200) NULL,
[Pre-Ship Freight Ton]   varchar(200) NULL,
[Pre-Ship No of Pack]   varchar(200) NULL,
[Post-Ship MOC]   varchar(200) NULL,
[Post-Ship Transport No]   varchar(200) NULL,
[Post-Ship Dept Point]   varchar(200) NULL,
[Post-Ship Arr Point]   varchar(200) NULL,
[Post-Ship ETD]   varchar(200) NULL,
[Post-Ship ATD]   varchar(200) NULL,
[Post-Ship ETA]   varchar(200) NULL,
[Post-Ship ATA]   varchar(200) NULL,
[Post-Ship Freight Ton]   varchar(200) NULL,
[Post-Ship No of Pack]   varchar(200) NULL,
[MRR Number]   varchar(200) NULL,
[MRR Rev Nr]   varchar(200) NULL,
[(1st of) MRR Created Date(s)]   varchar(200) NULL,
[(Earliest) Matl Recv Date]   varchar(200) NULL,
[MRR Posted Date]   varchar(200) NULL,
[MRR Quantity]   varchar(200) NULL,
[OSD Number]   varchar(200) NULL,
[OSD Created Date]   varchar(200) NULL,
[OSD Qty]   varchar(200) NULL,
[OSD Type]   varchar(200) NULL,
[OSD Request Action]   varchar(200) NULL,
[OSD Action Taken]   varchar(200) NULL,
[OSD Closed Date]   varchar(200) NULL,
[Buyer]   varchar(2000) NULL,
[Expeditor]   varchar(200) NULL,
[Package Manager]   varchar(200) NULL,
[Item Comments]   varchar(200) NULL,
[Header Comment]   varchar(8000) NULL,
[Color]   varchar(200) NULL,
[is_master_tag]   varchar(200) NULL,
[project_number] [varchar](200) NULL,
[CreatedDateTime] [varchar](200) NULL,
[file_name] [varchar](200) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	HEAP
)
GO


