
CREATE TABLE [epr].[MDR_Data_Ummshaif_D7650](
[iDocs Document Number]   varchar(4000) NULL,
[Project Document Number]   varchar(4000) NULL,
[Title]   varchar(4000) NULL,
[Revision]   varchar(200) NULL,
[Revision Date]   varchar(200) NULL,
[Issue State]   varchar(200) NULL,
[Document Type]   varchar(200) NULL,
[Area]   varchar(200) NULL,
[Document Classification]   varchar(4000) NULL,
[Originator]   varchar(200) NULL,
[Client Section Code]   varchar(200) NULL,
[Client Sub-Doc. Type]   varchar(200) NULL,
[Deliverable Criteria]   varchar(200) NULL,
[Scope]   varchar(200) NULL,
[MCD Discipline]   varchar(4000) NULL,
[Unique ID]   varchar(200) NULL,
[GPCA Cost Code]   varchar(4000) NULL,
[GPCA Cost Code Description]   varchar(200) NULL,
[GPCA Prime Description]   varchar(200) NULL,
[GPCA Sub Prime Description]   varchar(200) NULL,
[Discipline]   varchar(200) NULL,
[Client Discipline]   varchar(200) NULL,
[Client Doc Type]   varchar(200) NULL,
[Drawing Sub-Doc. Type]   varchar(200) NULL,
[Remarks]   varchar(4000) NULL,
[Status]   varchar(4000) NULL,
[Project Identification]   varchar(200) NULL,
[Unit Number]   varchar(200) NULL,
[Ext. Last Client Trans.No.]   varchar(200) NULL,
[Ext. Last Client D. Purpose]   varchar(200) NULL,
[Ext. Last Client Trans.Date]   varchar(200) NULL,
[Internal Last Trans.No.]   varchar(200) NULL,
[Internal Last Trans.Date]   varchar(200) NULL,
[Last Inc.Client Trans.No.]   varchar(200) NULL,
[Last Inc.Client Trans.Date.]   varchar(200) NULL,
[Last Inc.Client Trans.Code.]   varchar(200) NULL,
[SD_Budget - Progress Base]   varchar(200) NULL,
[SD_Budget - Original]   varchar(200) NULL,
[SD_Budget - Forecast]   varchar(200) NULL,
[SD_Budget - Revised]   varchar(200) NULL,
[Total (Current) Progress]   varchar(200) NULL,
[Start Activity Id]   varchar(200) NULL,
[IDC Activity Id]   varchar(200) NULL,
[IFR Activity Id]   varchar(200) NULL,
[RCA-1 Activity Id]   varchar(200) NULL,
[IFA Activity Id]   varchar(200) NULL,
[RCA-2 Activity Id]   varchar(200) NULL,
[Re-IFA Activity ID]   varchar(200) NULL,
[AFD Activity Id]   varchar(200) NULL,
[AFC(H) Activity Id]   varchar(200) NULL,
[AFC Activity Id]   varchar(200) NULL,
[IFI Activity Id]   varchar(200) NULL,
[As-Built Activity Id]   varchar(200) NULL,
[Start Original]   varchar(200) NULL,
[Start Plan]   varchar(200) NULL,
[Start Forecast]   varchar(200) NULL,
[Start Actual]   varchar(200) NULL,
[IDC Original]   varchar(200) NULL,
[IDC Plan]   varchar(200) NULL,
[IDC Forecast]   varchar(200) NULL,
[IDC Actual]   varchar(200) NULL,
[IDC Complete Original]   varchar(200) NULL,
[IDC Complete Plan]   varchar(200) NULL,
[IDC Complete Forecast]   varchar(200) NULL,
[IDC Complete Actual]   varchar(200) NULL,
[IFR Original]   varchar(200) NULL,
[IFR Plan]   varchar(200) NULL,
[IFR Forecast]   varchar(200) NULL,
[IFR Actual]   varchar(200) NULL,
[RCA IFR Original]   varchar(200) NULL,
[RCA IFR Plan]   varchar(200) NULL,
[RCA IFR Forecast]   varchar(200) NULL,
[RCA IFR Actual]   varchar(200) NULL,
[IFA Original]   varchar(200) NULL,
[IFA Plan]   varchar(200) NULL,
[IFA Forecast]   varchar(200) NULL,
[IFA Actual]   varchar(200) NULL,
[RCA-IFA Original]   varchar(200) NULL,
[RCA-IFA Plan]   varchar(200) NULL,
[RCA-IFA Forecast]   varchar(200) NULL,
[RCA-IFA Actual]   varchar(200) NULL,
[Re-IFA Original]   varchar(200) NULL,
[Re-IFA Plan]   varchar(200) NULL,
[Re-IFA Forecast]   varchar(200) NULL,
[Re-IFA Actual]   varchar(200) NULL,
[RCA-Re-IFA Plan]   varchar(200) NULL,
[RCA-Re-IFA Forecast]   varchar(200) NULL,
[RCA-Re-IFA Actual]   varchar(200) NULL,
[IFH Original]   varchar(200) NULL,
[IFH Plan]   varchar(200) NULL,
[IFH Forecast]   varchar(200) NULL,
[IFH Actual]   varchar(200) NULL,
[RCA-IFH Original]   varchar(200) NULL,
[RCA-IFH Plan]   varchar(200) NULL,
[RCA-IFH Forecast]   varchar(200) NULL,
[RCA-IFH Actual]   varchar(200) NULL,
[IFD Original]   varchar(200) NULL,
[IFD Plan]   varchar(200) NULL,
[IFD Forecast]   varchar(200) NULL,
[IFD Actual]   varchar(200) NULL,
[AFC(H) Original]   varchar(200) NULL,
[AFC(H) Plan]   varchar(200) NULL,
[AFC(H) Forecast]   varchar(200) NULL,
[AFC(H) Actual]   varchar(200) NULL,
[AFC Original]   varchar(200) NULL,
[AFC Plan]   varchar(200) NULL,
[AFC Forecast]   varchar(200) NULL,
[AFC Actual]   varchar(200) NULL,
[Re-IFI Original]   varchar(200) NULL,
[Re-IFI Plan]   varchar(200) NULL,
[Re-IFI Forecast]   varchar(200) NULL,
[Re-IFI Actual]   varchar(200) NULL,
[IFI Original]   varchar(200) NULL,
[IFI Plan]   varchar(200) NULL,
[IFI Forecast]   varchar(200) NULL,
[IFI Actual]   varchar(200) NULL,
[As-Built Original]   varchar(200) NULL,
[As-Built Plan]   varchar(200) NULL,
[As-Built Forecast]   varchar(200) NULL,
[As-Built Actual]   varchar(200) NULL,
[PCM Input]   varchar(200) NULL,
[3rd Party ID]   varchar(200) NULL,
[CRS No.]   varchar(200) NULL,
[Voided Reason]   varchar(200) NULL,
[Location]   varchar(200) NULL,
[Deliverable Type]   varchar(200) NULL,
[Profile Type]   varchar(200) NULL,
[File Location]   varchar(200) NULL,
[Dynamic Folder]   varchar(200) NULL,
[File Name]   varchar(200) NULL,
[Version]   varchar(200) NULL,
[D1 BM]   varchar(200) NULL,
[SMAT MR#]   varchar(200) NULL,
[Deck]   varchar(200) NULL,
[Deck Level]   varchar(200) NULL,
[Component]   varchar(200) NULL,
[Job Number]   varchar(200) NULL,
[30% Design Review]   varchar(200) NULL,
[60% Design Review]   varchar(200) NULL,
[90% Design Review]   varchar(200) NULL,
[Ver_Creator]   varchar(200) NULL,
[Rev_Creator]   varchar(200) NULL,
[Transmittal Issuer]   varchar(200) NULL,
[SD_Work Area - Construction (CWA)]   varchar(200) NULL,
[SD_Work Package - Construction (CWP)]   varchar(200) NULL,
[SD_Work Package - Engineering (EWP)]   varchar(200) NULL,
[SD_Work Package - Procurement (PWP)]   varchar(200) NULL,
[SourceFileName] varchar(200) NULL,
[CreatedDateTime] varchar(200) NULL,
[project_number] varchar(200) NULL
)WITH(	DISTRIBUTION = ROUND_ROBIN,	CLUSTERED COLUMNSTORE INDEX)



INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_MDR_Data_Ummshaif_D7650','NetworkFolder','start_date','1','start_date','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_MDR_Data_Ummshaif_D7650','NetworkFolder','end_date','2','end_date','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_MDR_Data_Ummshaif_D7650','NetworkFolder','source_directory','3','source_directory','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_MDR_Data_Ummshaif_D7650','NetworkFolder','table_name','4','table_name','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_MDR_Data_Ummshaif_D7650','NetworkFolder','logicapp_url','5','logicapp_url','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_MDR_Data_Ummshaif_D7650','NetworkFolder','range','6','range','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_MDR_Data_Ummshaif_D7650','NetworkFolder','file_name','7','file_name','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697')
INSERT INTO [dbo].[plp_pipeline_parameter] ([pipeline_code],[pipeline_sub_code],[parameter_code],[display_order],[source_column_name],[source_operator],[comment],[active],[touched_by],[touched_dtm]) values ('pl_MDR_Data_Ummshaif_D7650','NetworkFolder','project_number','8','project_number','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697')

insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('range','A1:ER50000','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697','pl_MDR_Data_Ummshaif_D7650','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('table_name','MDR_Data_Ummshaif_D7650','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697','pl_MDR_Data_Ummshaif_D7650','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('logicapp_url','https://prod-56.eastus.logic.azure.com:443/workflows/3cff41a53ba14a82a9b7cc8d6d2bfe56/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=c7BCbv69x4tk7w5oqGQNOPlpIXvqBQi_Zwm8wkww0WQ','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697','pl_MDR_Data_Ummshaif_D7650','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('end_date','currdate','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697','pl_MDR_Data_Ummshaif_D7650','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('source_directory','06. D7650 - Umm Shaif\02. Engineering\01. MDR','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697','pl_MDR_Data_Ummshaif_D7650','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('project_number','D7650','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697','pl_MDR_Data_Ummshaif_D7650','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('start_date','2025-02-16 11:23:20','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697','pl_MDR_Data_Ummshaif_D7650','NetworkFolder')
insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('file_name','MDR_IDOCS.CSV','1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697','pl_MDR_Data_Ummshaif_D7650','NetworkFolder')

insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_MDR_Data_Ummshaif_D7650','NCSA','Manual Excel File Direct Source To Synapse',NULL,'1','sundararaju.batta@mcdermott.com','2025-02-24 06:20:46.697',9)

                                                            