SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--DROP VIEW [dbo].[dim_entp_yardkpi_r2p_po_header_v]
CREATE VIEW [dbo].[dim_entp_yardkpi_r2p_po_header_v]
AS select [dim_entp_yardkpi_r2p_po_header_sk],
	[dim_entp_yardkpi_r2p_po_header_nk],
	[start_date],
	[end_date],
	[hash_code],
	[active],
	[created_date_time],
	[modified_date_time],
	[late_arrival_flag],
	[dim_ent_source_nk],
	[dim_ent_sub_source_nk],
	[project_number],
	[project_name],
	[requisition_bu],
	[requisition_no],
	[requisition_originator],
	[req_submission_date],
	[req_approved_date],
	[purchaser_or_requester],
	[po_no],
	[source_poh_id],
	[source_base_poh_id],
	[req_start_date],
	[req_end_date],
	[smat_rev_no],
	[po_rev],
	[po_description],
	[po_status],
	[po_creation_date],
	[po_approved_date],
	[first_po_version_amount],
	[first_po_version_receive_date],
	[acknowledgement_date],
	[po_currency],
	[payment_terms],
	[incoterm],
	[selection_code],
	[mpp_po],
	[original_po_amount],
	[po_amount_in_usd],
	[charge_account],
	[supplier],
	[supplier_num],
	[supplier_site],
	[supplier_type],
	[supplier_country],
	[buyer],
	[po_approver],
	[po_closed_date],
	[agreement_number],
	[material_work_group],
	[source_po],
	[buyer_email_id],
	[requester_email_id]
from [dbo].[dim_entp_yardkpi_r2p_po_header] where active = 1;
GO
