
drop view [dbo].[dim_entp_yardkpi_detailing_engineering_v]

create view [dbo].[dim_entp_yardkpi_detailing_engineering_v]
as
SELECT [dim_entp_yardkpi_detailing_engineering_sk]
      ,[dim_entp_yardkpi_detailing_engineering_nk]
      ,[start_date]
      ,[end_date]
      ,[hash_code]
      ,[active]
      ,[created_date_time]
      ,[modified_date_time]
      ,[late_arrival_flag]
      ,[dim_ent_source_nk]
      ,[dim_ent_sub_source_nk]
      ,[dim_ent_contract_nk]
      ,[dim_ent_time_coa_kronos_sk]
      ,[project]
      ,[project_status]
      ,[scope]
      ,[plan_actual]
      ,[activity_id]
      ,[discipline]
      ,[discipline_description]
      ,[piping_detailing_deliverable_type]
      ,[facility]
      ,[facility_description]
      ,[description]
      ,[project_category]
      ,[detailing_group_activity]
      ,[Remarks]
      ,[division]
	,[component]
	,[subf] 
	,[cst_element]
	,[wbs]
  FROM [dbo].[dim_entp_yardkpi_detailing_engineering]
  where active = 1