
ALTER PROC [promt].[sp_validate_for_promt_datalake_export_risk_snapshot] AS
BEGIN
    
begin try
	
declare @error_message varchar(1000)
declare @processed_count  int
declare @unprocessed_count  int


	declare @exceptionRaiser	int;
	declare @errorMessage		varchar(4000);

	DECLARE @Date DATETIME;
	SET @Date = GETDATE();
	
	--------------------------------------------------------------------------------------
	----setup any pre=processing values as required.
	--------------------------------------------------------------------------------------

	select @processed_count=0 --temp entry


	--------------------------------------------------------------------------------------
	-- Combine date from the Reprocess table for the current run
	--------------------------------------------------------------------------------------
	
INSERT INTO [promt].[stage_promt_datalake_export_risk_snapshot]
([ssri_id]
,[ss_id]
,[period_date]
,[risk_id]
,[risk_no]
,[ro_category]
,[ro_category_description]
,[sub_category]
,[dim_ent_risk_opportunity_category_sk]
,[dim_ent_risk_opportunity_category_nk]
,[risk_title]
,[description]
,[record_date]
,[probability_range_percentage]
,[probability_range_percentage_description]
,[probability_range_percentage_display_order]
,[dim_ent_probability_range_percentage_sk]
,[dim_ent_probability_range_percentage_nk]
,[environment]
,[environment_description]
,[dim_ent_environment_sk]
,[dim_ent_environment_nk]
,[health_safety_security]
,[health_safety_security_description]
,[dim_ent_health_safety_security_sk]
,[dim_ent_health_safety_security_nk]
,[quality]
,[quality_description]
,[dim_ent_quality_sk]
,[dim_ent_quality_nk]
,[reputation]
,[reputation_description]
,[dim_ent_reputation_sk]
,[dim_ent_reputation_nk]
,[social_culture]
,[social_culture_description]
,[dim_ent_social_culture_sk]
,[dim_ent_social_culture_nk]
,[cost_impact_tcv_percentage]
,[cost_impact_tcv_percentage_description]
,[dim_ent_cost_impact_tcv_percentage_sk]
,[dim_ent_cost_impact_tcv_percentage_nk]
,[schedule]
,[schedule_description]
,[dim_ent_schedule_sk]
,[dim_ent_schedule_nk]
,[overall_impact]
,[overall_impact_description]
,[overall_impact_display_sort_order]
,[dim_ent_overall_impact_sk]
,[dim_ent_overall_impact_nk]
,[severity_score]
,[hilp]
,[risk_owner]
,[risk_status]
,[risk_status_description]
,[dim_ent_risk_status_sk]
,[dim_ent_risk_status_nk]
,[closing_justification]
,[closing_justification_description]
,[dim_ent_risk_closing_justification_sk]
,[dim_ent_risk_closing_justification_nk]
,[strategy_pre_contract]
,[strategy_pre_contract_description]
,[dim_ent_strategy_pre_contract_sk]
,[dim_ent_strategy_pre_contract_nk]
,[strategy_execution]
,[strategy_execution_description]
,[dim_ent_strategy_execution_sk]
,[dim_ent_strategy_execution_nk]
,[actions]
,[cost_mitigation]
,[action_status]
,[action_status_description]
,[dim_ent_action_status_sk]
,[dim_ent_action_status_nk]
,[action_due_date]
,[mit_probability_range_percentage]
,[mit_probability_range_percentage_description]
,[mit_probability_range_percentage_display_order]
,[dim_ent_mit_probability_range_percentage_sk]
,[dim_ent_mit_probability_range_percentage_nk]
,[mit_environment]
,[mit_environment_description]
,[dim_ent_mit_environment_sk]
,[dim_ent_mit_environment_nk]
,[mit_health_safety_security]
,[mit_health_safety_security_description]
,[dim_ent_mit_health_safety_security_sk]
,[dim_ent_mit_health_safety_security_nk]
,[mit_quality]
,[mit_quality_description]
,[dim_ent_mit_quality_sk]
,[dim_ent_mit_quality_nk]
,[mit_reputation]
,[mit_reputation_description]
,[dim_ent_mit_reputation_sk]
,[dim_ent_mit_reputation_nk]
,[mit_social_culture]
,[mit_social_culture_description]
,[dim_ent_mit_social_culture_sk]
,[dim_ent_mit_social_culture_nk]
,[mit_cost_impact_tcv_percentage]
,[mit_cost_impact_tcv_percentage_description]
,[dim_ent_mit_cost_impact_tcv_percentage_sk]
,[dim_ent_mit_cost_impact_tcv_percentage_nk]
,[mit_schedule]
,[mit_schedule_description]
,[dim_ent_mit_schedule_sk]
,[dim_ent_mit_schedule_nk]
,[mit_overall_impact]
,[mit_overall_impact_description]
,[mit_overall_impact_display_sort_order]
,[dim_ent_mit_overall_impact_sk]
,[dim_ent_mit_overall_impact_nk]
,[mit_severity_score]
,[mit_hilp]
,[probability]
,[best_case]
,[most_likely]
,[worst_case]
,[discrete_value]
,[bottom_value]
,[top_value]
,[lower_probability]
,[min_value]
,[max_value]
,[distribution_type]
,[distribution_type_description]
,[dim_ent_distribution_type_sk]
,[dim_ent_distribution_type_nk]
,[risk_function1]
,[mit_probability]
,[mit_best_case]
,[mit_most_likely]
,[mit_worst_case]
,[mit_discrete_value]
,[mit_bottom_value]
,[mit_top_value]
,[mit_lower_probability]
,[mit_min_value]
,[mit_max_value]
,[risk_function_2]
,[shared_externaly]
,[shared_externaly_description]
,[dim_ent_shared_externaly_sk]
,[dim_ent_shared_externaly_nk]
,[drivers_causes]
,[risk_due_date]
,[mit_cost]
,[risk_modeling_tech]
,[risk_modeling_tech_description]
,[dim_ent_risk_modeling_tech_sk]
,[dim_ent_risk_modeling_tech_nk]
,[t_project_id]
,[mit_fully_transferred]
,[mit_fully_transferred_description]
,[dim_ent_mit_fully_transferred_sk]
,[dim_ent_mit_fully_transferred_nk]
,[mit_fully_avoided]
,[mit_fully_avoided_description]
,[dim_ent_mit_fully_avoided_sk]
,[dim_ent_mit_fully_avoided_nk]
,[active_flag]
,[created_by]
,[created_dtm]
,[version_no]
,[expected_value_at_risk]
,[weighted_value_at_risk]
,[cost_impact_ranging_basis]
,[expected_value_at_risk_pre_contract]
,[dim_ent_promt_project_sk]
,[dim_ent_promt_project_nk]
,[project_no]						
,[project_pc_code]					
,[project_pc_code_description]		
,[project_bid_project_id]			
,[project_project_title]				
,[project_client_name]				
,[project_business_line]				
,[project_business_line_description]	
,[project_country]					
,[project_manager]					
,[project_prom_lead]					
,[project_category]					
,[project_category_description]		
,[project_total_contract_value]		
,[project_estimated_cost]			
,[project_currency_code]				
,[project_currency_code_description]	
,[project_contract_type]				
,[project_contract_type_description]	
,[project_total_duration]			
,[project_document_revision_no]		
,[project_document_revision_date]	
,[project_revisied_by]				
,[project_approved_by]				
,[project_award_date]				
,[project_active_flag]				
,[project_project_type]				
,[project_project_type_description]	
,[project_duration_type]				
,[project_version_no]				
,[project_status]					
,[project_status_description]		
,[dl_touched_dtm]
,[process_date]
,[closed_dtm]
,[archived]
,[rearchival_date]
)
SELECT
[ssri_id]
,[ss_id]
,[period_date]
,[risk_id]
,[risk_no]
,[ro_category]
,[ro_category_description]
,[sub_category]
,[dim_ent_risk_opportunity_category_sk]
,[dim_ent_risk_opportunity_category_nk]
,[risk_title]
,[description]
,[record_date]
,[probability_range_percentage]
,[probability_range_percentage_description]
,[probability_range_percentage_display_order]
,[dim_ent_probability_range_percentage_sk]
,[dim_ent_probability_range_percentage_nk]
,[environment]
,[environment_description]
,[dim_ent_environment_sk]
,[dim_ent_environment_nk]
,[health_safety_security]
,[health_safety_security_description]
,[dim_ent_health_safety_security_sk]
,[dim_ent_health_safety_security_nk]
,[quality]
,[quality_description]
,[dim_ent_quality_sk]
,[dim_ent_quality_nk]
,[reputation]
,[reputation_description]
,[dim_ent_reputation_sk]
,[dim_ent_reputation_nk]
,[social_culture]
,[social_culture_description]
,[dim_ent_social_culture_sk]
,[dim_ent_social_culture_nk]
,[cost_impact_tcv_percentage]
,[cost_impact_tcv_percentage_description]
,[dim_ent_cost_impact_tcv_percentage_sk]
,[dim_ent_cost_impact_tcv_percentage_nk]
,[schedule]
,[schedule_description]
,[dim_ent_schedule_sk]
,[dim_ent_schedule_nk]
,[overall_impact]
,[overall_impact_description]
,[overall_impact_display_sort_order]
,[dim_ent_overall_impact_sk]
,[dim_ent_overall_impact_nk]
,[severity_score]
,[hilp]
,[risk_owner]
,[risk_status]
,[risk_status_description]
,[dim_ent_risk_status_sk]
,[dim_ent_risk_status_nk]
,[closing_justification]
,[closing_justification_description]
,[dim_ent_risk_closing_justification_sk]
,[dim_ent_risk_closing_justification_nk]
,[strategy_pre_contract]
,[strategy_pre_contract_description]
,[dim_ent_strategy_pre_contract_sk]
,[dim_ent_strategy_pre_contract_nk]
,[strategy_execution]
,[strategy_execution_description]
,[dim_ent_strategy_execution_sk]
,[dim_ent_strategy_execution_nk]
,[actions]
,[cost_mitigation]
,[action_status]
,[action_status_description]
,[dim_ent_action_status_sk]
,[dim_ent_action_status_nk]
,[action_due_date]
,[mit_probability_range_percentage]
,[mit_probability_range_percentage_description]
,[mit_probability_range_percentage_display_order]
,[dim_ent_mit_probability_range_percentage_sk]
,[dim_ent_mit_probability_range_percentage_nk]
,[mit_environment]
,[mit_environment_description]
,[dim_ent_mit_environment_sk]
,[dim_ent_mit_environment_nk]
,[mit_health_safety_security]
,[mit_health_safety_security_description]
,[dim_ent_mit_health_safety_security_sk]
,[dim_ent_mit_health_safety_security_nk]
,[mit_quality]
,[mit_quality_description]
,[dim_ent_mit_quality_sk]
,[dim_ent_mit_quality_nk]
,[mit_reputation]
,[mit_reputation_description]
,[dim_ent_mit_reputation_sk]
,[dim_ent_mit_reputation_nk]
,[mit_social_culture]
,[mit_social_culture_description]
,[dim_ent_mit_social_culture_sk]
,[dim_ent_mit_social_culture_nk]
,[mit_cost_impact_tcv_percentage]
,[mit_cost_impact_tcv_percentage_description]
,[dim_ent_mit_cost_impact_tcv_percentage_sk]
,[dim_ent_mit_cost_impact_tcv_percentage_nk]
,[mit_schedule]
,[mit_schedule_description]
,[dim_ent_mit_schedule_sk]
,[dim_ent_mit_schedule_nk]
,[mit_overall_impact]
,[mit_overall_impact_description]
,[mit_overall_impact_display_sort_order]
,[dim_ent_mit_overall_impact_sk]
,[dim_ent_mit_overall_impact_nk]
,[mit_severity_score]
,[mit_hilp]
,[probability]
,[best_case]
,[most_likely]
,[worst_case]
,[discrete_value]
,[bottom_value]
,[top_value]
,[lower_probability]
,[min_value]
,[max_value]
,[distribution_type]
,[distribution_type_description]
,[dim_ent_distribution_type_sk]
,[dim_ent_distribution_type_nk]
,[risk_function1]
,[mit_probability]
,[mit_best_case]
,[mit_most_likely]
,[mit_worst_case]
,[mit_discrete_value]
,[mit_bottom_value]
,[mit_top_value]
,[mit_lower_probability]
,[mit_min_value]
,[mit_max_value]
,[risk_function_2]
,[shared_externaly]
,[shared_externaly_description]
,[dim_ent_shared_externaly_sk]
,[dim_ent_shared_externaly_nk]
,[drivers_causes]
,[risk_due_date]
,[mit_cost]
,[risk_modeling_tech]
,[risk_modeling_tech_description]
,[dim_ent_risk_modeling_tech_sk]
,[dim_ent_risk_modeling_tech_nk]
,[t_project_id]
,[mit_fully_transferred]
,[mit_fully_transferred_description]
,[dim_ent_mit_fully_transferred_sk]
,[dim_ent_mit_fully_transferred_nk]
,[mit_fully_avoided]
,[mit_fully_avoided_description]
,[dim_ent_mit_fully_avoided_sk]
,[dim_ent_mit_fully_avoided_nk]
,[active_flag]
,[created_by]
,[created_dtm]
,[version_no]
,[expected_value_at_risk]
,[weighted_value_at_risk]
,[cost_impact_ranging_basis]
,[expected_value_at_risk_pre_contract]
,[dim_ent_promt_project_sk]
,[dim_ent_promt_project_nk]
,[project_no]						
,[project_pc_code]					
,[project_pc_code_description]		
,[project_bid_project_id]			
,[project_project_title]				
,[project_client_name]				
,[project_business_line]				
,[project_business_line_description]	
,[project_country]					
,[project_manager]					
,[project_prom_lead]					
,[project_category]					
,[project_category_description]		
,[project_total_contract_value]		
,[project_estimated_cost]			
,[project_currency_code]				
,[project_currency_code_description]	
,[project_contract_type]				
,[project_contract_type_description]	
,[project_total_duration]			
,[project_document_revision_no]		
,[project_document_revision_date]	
,[project_revisied_by]				
,[project_approved_by]				
,[project_award_date]				
,[project_active_flag]				
,[project_project_type]				
,[project_project_type_description]	
,[project_duration_type]				
,[project_version_no]				
,[project_status]					
,[project_status_description]		
,[dl_touched_dtm]
,[process_date]
,[closed_dtm]
,[archived]
,[rearchival_date]
FROM [promt].[reprocess_promt_datalake_export_risk_snapshot];

DELETE FROM [promt].[reprocess_promt_datalake_export_risk_snapshot];

	-----------------------------------------------------------------
-------Update the SK/NK values within the Synapse table USING STORED PROCEDURE.
	-----------------------------------------------------------------
	
EXEC promt.sp_update_dimension_keys_for_promt_datalake_export_risk_snapshot;


	SELECT @unprocessed_count  = count(*) FROM promt.stage_promt_datalake_export_risk_snapshot
	WHERE   
[dim_ent_risk_opportunity_category_sk]
IS NULL OR [dim_ent_risk_opportunity_category_nk]
IS NULL OR [dim_ent_probability_range_percentage_sk]
IS NULL OR [dim_ent_probability_range_percentage_nk]
IS NULL OR [dim_ent_environment_sk]
IS NULL OR [dim_ent_environment_nk]
IS NULL OR [dim_ent_health_safety_security_sk]
IS NULL OR [dim_ent_health_safety_security_nk]
IS NULL OR [dim_ent_quality_sk]
IS NULL OR [dim_ent_quality_nk]
IS NULL OR [dim_ent_reputation_sk]
IS NULL OR [dim_ent_reputation_nk]
IS NULL OR [dim_ent_social_culture_sk]
IS NULL OR [dim_ent_social_culture_nk]
IS NULL OR [dim_ent_cost_impact_tcv_percentage_sk]
IS NULL OR [dim_ent_cost_impact_tcv_percentage_nk]
IS NULL OR [dim_ent_schedule_sk]
IS NULL OR [dim_ent_schedule_nk]
IS NULL OR [dim_ent_risk_status_sk]
IS NULL OR [dim_ent_risk_status_nk]
IS NULL OR [dim_ent_risk_closing_justification_sk]
IS NULL OR [dim_ent_risk_closing_justification_nk]
IS NULL OR [dim_ent_strategy_pre_contract_sk]
IS NULL OR [dim_ent_strategy_pre_contract_nk]
IS NULL OR [dim_ent_strategy_execution_sk]
IS NULL OR [dim_ent_strategy_execution_nk]
IS NULL OR [dim_ent_action_status_sk]
IS NULL OR [dim_ent_action_status_nk]
IS NULL OR [dim_ent_mit_probability_range_percentage_sk]
IS NULL OR [dim_ent_mit_probability_range_percentage_nk]
IS NULL OR [dim_ent_mit_environment_sk]
IS NULL OR [dim_ent_mit_environment_nk]
IS NULL OR [dim_ent_mit_health_safety_security_sk]
IS NULL OR [dim_ent_mit_health_safety_security_nk]
IS NULL OR [dim_ent_mit_quality_sk]
IS NULL OR [dim_ent_mit_quality_nk]
IS NULL OR [dim_ent_mit_reputation_sk]
IS NULL OR [dim_ent_mit_reputation_nk]
IS NULL OR [dim_ent_mit_social_culture_sk]
IS NULL OR [dim_ent_mit_social_culture_nk]
IS NULL OR [dim_ent_mit_cost_impact_tcv_percentage_sk]
IS NULL OR [dim_ent_mit_cost_impact_tcv_percentage_nk]
IS NULL OR [dim_ent_mit_schedule_sk]
IS NULL OR [dim_ent_mit_schedule_nk]
IS NULL OR [dim_ent_distribution_type_sk]
IS NULL OR [dim_ent_distribution_type_nk]
IS NULL OR [dim_ent_shared_externaly_sk]
IS NULL OR [dim_ent_shared_externaly_nk]
IS NULL OR [dim_ent_risk_modeling_tech_sk]
IS NULL OR [dim_ent_risk_modeling_tech_nk]
IS NULL OR [dim_ent_mit_fully_transferred_sk]
IS NULL OR [dim_ent_mit_fully_transferred_nk]
IS NULL OR [dim_ent_mit_fully_avoided_sk]
IS NULL OR [dim_ent_mit_fully_avoided_nk]
IS NULL OR [dim_ent_promt_project_sk]
IS NULL OR [dim_ent_promt_project_nk]
IS NULL OR [dim_ent_overall_impact_sk]
IS NULL OR [dim_ent_overall_impact_nk]
IS NULL OR [dim_ent_mit_overall_impact_sk]
IS NULL OR [dim_ent_mit_overall_impact_nk]
IS NULL 
;
			


	SELECT @processed_count  = count(*) FROM promt.stage_promt_datalake_export_risk_snapshot
	WHERE   

[dim_ent_risk_opportunity_category_sk] IS NOT NULL
AND [dim_ent_risk_opportunity_category_nk] IS NOT NULL
AND [dim_ent_probability_range_percentage_sk] IS NOT NULL
AND [dim_ent_probability_range_percentage_nk] IS NOT NULL
AND [dim_ent_environment_sk] IS NOT NULL
AND [dim_ent_environment_nk] IS NOT NULL
AND [dim_ent_health_safety_security_sk] IS NOT NULL
AND [dim_ent_health_safety_security_nk] IS NOT NULL
AND [dim_ent_quality_sk] IS NOT NULL
AND [dim_ent_quality_nk] IS NOT NULL
AND [dim_ent_reputation_sk] IS NOT NULL
AND [dim_ent_reputation_nk] IS NOT NULL
AND [dim_ent_social_culture_sk] IS NOT NULL
AND [dim_ent_social_culture_nk] IS NOT NULL
AND [dim_ent_cost_impact_tcv_percentage_sk] IS NOT NULL
AND [dim_ent_cost_impact_tcv_percentage_nk] IS NOT NULL
AND [dim_ent_schedule_sk] IS NOT NULL
AND [dim_ent_schedule_nk] IS NOT NULL
AND [dim_ent_risk_status_sk] IS NOT NULL
AND [dim_ent_risk_status_nk] IS NOT NULL
AND [dim_ent_risk_closing_justification_sk] IS NOT NULL
AND [dim_ent_risk_closing_justification_nk] IS NOT NULL
AND [dim_ent_strategy_pre_contract_sk] IS NOT NULL
AND [dim_ent_strategy_pre_contract_nk] IS NOT NULL
AND [dim_ent_strategy_execution_sk] IS NOT NULL
AND [dim_ent_strategy_execution_nk] IS NOT NULL
AND [dim_ent_action_status_sk] IS NOT NULL
AND [dim_ent_action_status_nk] IS NOT NULL
AND [dim_ent_mit_probability_range_percentage_sk] IS NOT NULL
AND [dim_ent_mit_probability_range_percentage_nk] IS NOT NULL
AND [dim_ent_mit_environment_sk] IS NOT NULL
AND [dim_ent_mit_environment_nk] IS NOT NULL
AND [dim_ent_mit_health_safety_security_sk] IS NOT NULL
AND [dim_ent_mit_health_safety_security_nk] IS NOT NULL
AND [dim_ent_mit_quality_sk] IS NOT NULL
AND [dim_ent_mit_quality_nk] IS NOT NULL
AND [dim_ent_mit_reputation_sk] IS NOT NULL
AND [dim_ent_mit_reputation_nk] IS NOT NULL
AND [dim_ent_mit_social_culture_sk] IS NOT NULL
AND [dim_ent_mit_social_culture_nk] IS NOT NULL
AND [dim_ent_mit_cost_impact_tcv_percentage_sk] IS NOT NULL
AND [dim_ent_mit_cost_impact_tcv_percentage_nk] IS NOT NULL
AND [dim_ent_mit_schedule_sk] IS NOT NULL
AND [dim_ent_mit_schedule_nk] IS NOT NULL
AND [dim_ent_distribution_type_sk] IS NOT NULL
AND [dim_ent_distribution_type_nk] IS NOT NULL
AND [dim_ent_shared_externaly_sk] IS NOT NULL
AND [dim_ent_shared_externaly_nk] IS NOT NULL
AND [dim_ent_risk_modeling_tech_sk] IS NOT NULL
AND [dim_ent_risk_modeling_tech_nk] IS NOT NULL
AND [dim_ent_mit_fully_transferred_sk] IS NOT NULL
AND [dim_ent_mit_fully_transferred_nk] IS NOT NULL
AND [dim_ent_mit_fully_avoided_sk] IS NOT NULL
AND [dim_ent_mit_fully_avoided_nk] IS NOT NULL
AND [dim_ent_promt_project_sk] IS NOT NULL
AND [dim_ent_promt_project_nk] IS NOT NULL
AND [dim_ent_overall_impact_sk] IS NOT NULL
AND [dim_ent_overall_impact_nk] IS NOT NULL
AND [dim_ent_mit_overall_impact_sk] IS NOT NULL
AND [dim_ent_mit_overall_impact_nk] IS NOT NULL
;



INSERT INTO [promt].[reprocess_promt_datalake_export_risk_snapshot]
(
[ssri_id]
,[ss_id]
,[period_date]
,[risk_id]
,[risk_no]
,[ro_category]
,[ro_category_description]
,[sub_category]
,[dim_ent_risk_opportunity_category_sk]
,[dim_ent_risk_opportunity_category_nk]
,[risk_title]
,[description]
,[record_date]
,[probability_range_percentage]
,[probability_range_percentage_description]
,[probability_range_percentage_display_order]
,[dim_ent_probability_range_percentage_sk]
,[dim_ent_probability_range_percentage_nk]
,[environment]
,[environment_description]
,[dim_ent_environment_sk]
,[dim_ent_environment_nk]
,[health_safety_security]
,[health_safety_security_description]
,[dim_ent_health_safety_security_sk]
,[dim_ent_health_safety_security_nk]
,[quality]
,[quality_description]
,[dim_ent_quality_sk]
,[dim_ent_quality_nk]
,[reputation]
,[reputation_description]
,[dim_ent_reputation_sk]
,[dim_ent_reputation_nk]
,[social_culture]
,[social_culture_description]
,[dim_ent_social_culture_sk]
,[dim_ent_social_culture_nk]
,[cost_impact_tcv_percentage]
,[cost_impact_tcv_percentage_description]
,[dim_ent_cost_impact_tcv_percentage_sk]
,[dim_ent_cost_impact_tcv_percentage_nk]
,[schedule]
,[schedule_description]
,[dim_ent_schedule_sk]
,[dim_ent_schedule_nk]
,[overall_impact]
,[overall_impact_description]
,[overall_impact_display_sort_order]
,[dim_ent_overall_impact_sk]
,[dim_ent_overall_impact_nk]
,[severity_score]
,[hilp]
,[risk_owner]
,[risk_status]
,[risk_status_description]
,[dim_ent_risk_status_sk]
,[dim_ent_risk_status_nk]
,[closing_justification]
,[closing_justification_description]
,[dim_ent_risk_closing_justification_sk]
,[dim_ent_risk_closing_justification_nk]
,[strategy_pre_contract]
,[strategy_pre_contract_description]
,[dim_ent_strategy_pre_contract_sk]
,[dim_ent_strategy_pre_contract_nk]
,[strategy_execution]
,[strategy_execution_description]
,[dim_ent_strategy_execution_sk]
,[dim_ent_strategy_execution_nk]
,[actions]
,[cost_mitigation]
,[action_status]
,[action_status_description]
,[dim_ent_action_status_sk]
,[dim_ent_action_status_nk]
,[action_due_date]
,[mit_probability_range_percentage]
,[mit_probability_range_percentage_description]
,[mit_probability_range_percentage_display_order]
,[dim_ent_mit_probability_range_percentage_sk]
,[dim_ent_mit_probability_range_percentage_nk]
,[mit_environment]
,[mit_environment_description]
,[dim_ent_mit_environment_sk]
,[dim_ent_mit_environment_nk]
,[mit_health_safety_security]
,[mit_health_safety_security_description]
,[dim_ent_mit_health_safety_security_sk]
,[dim_ent_mit_health_safety_security_nk]
,[mit_quality]
,[mit_quality_description]
,[dim_ent_mit_quality_sk]
,[dim_ent_mit_quality_nk]
,[mit_reputation]
,[mit_reputation_description]
,[dim_ent_mit_reputation_sk]
,[dim_ent_mit_reputation_nk]
,[mit_social_culture]
,[mit_social_culture_description]
,[dim_ent_mit_social_culture_sk]
,[dim_ent_mit_social_culture_nk]
,[mit_cost_impact_tcv_percentage]
,[mit_cost_impact_tcv_percentage_description]
,[dim_ent_mit_cost_impact_tcv_percentage_sk]
,[dim_ent_mit_cost_impact_tcv_percentage_nk]
,[mit_schedule]
,[mit_schedule_description]
,[dim_ent_mit_schedule_sk]
,[dim_ent_mit_schedule_nk]
,[mit_overall_impact]
,[mit_overall_impact_description]
,[mit_overall_impact_display_sort_order]
,[dim_ent_mit_overall_impact_sk]
,[dim_ent_mit_overall_impact_nk]
,[mit_severity_score]
,[mit_hilp]
,[probability]
,[best_case]
,[most_likely]
,[worst_case]
,[discrete_value]
,[bottom_value]
,[top_value]
,[lower_probability]
,[min_value]
,[max_value]
,[distribution_type]
,[distribution_type_description]
,[dim_ent_distribution_type_sk]
,[dim_ent_distribution_type_nk]
,[risk_function1]
,[mit_probability]
,[mit_best_case]
,[mit_most_likely]
,[mit_worst_case]
,[mit_discrete_value]
,[mit_bottom_value]
,[mit_top_value]
,[mit_lower_probability]
,[mit_min_value]
,[mit_max_value]
,[risk_function_2]
,[shared_externaly]
,[shared_externaly_description]
,[dim_ent_shared_externaly_sk]
,[dim_ent_shared_externaly_nk]
,[drivers_causes]
,[risk_due_date]
,[mit_cost]
,[risk_modeling_tech]
,[risk_modeling_tech_description]
,[dim_ent_risk_modeling_tech_sk]
,[dim_ent_risk_modeling_tech_nk]
,[t_project_id]
,[mit_fully_transferred]
,[mit_fully_transferred_description]
,[dim_ent_mit_fully_transferred_sk]
,[dim_ent_mit_fully_transferred_nk]
,[mit_fully_avoided]
,[mit_fully_avoided_description]
,[dim_ent_mit_fully_avoided_sk]
,[dim_ent_mit_fully_avoided_nk]
,[active_flag]
,[created_by]
,[created_dtm]
,[version_no]
,[expected_value_at_risk]
,[weighted_value_at_risk]
,[cost_impact_ranging_basis]
,[expected_value_at_risk_pre_contract]
,[dim_ent_promt_project_sk]
,[dim_ent_promt_project_nk]
,[project_no]						
,[project_pc_code]					
,[project_pc_code_description]		
,[project_bid_project_id]			
,[project_project_title]				
,[project_client_name]				
,[project_business_line]				
,[project_business_line_description]	
,[project_country]					
,[project_manager]					
,[project_prom_lead]					
,[project_category]					
,[project_category_description]		
,[project_total_contract_value]		
,[project_estimated_cost]			
,[project_currency_code]				
,[project_currency_code_description]	
,[project_contract_type]				
,[project_contract_type_description]	
,[project_total_duration]			
,[project_document_revision_no]		
,[project_document_revision_date]	
,[project_revisied_by]				
,[project_approved_by]				
,[project_award_date]				
,[project_active_flag]				
,[project_project_type]				
,[project_project_type_description]	
,[project_duration_type]				
,[project_version_no]				
,[project_status]					
,[project_status_description]		
,[dl_touched_dtm]
,[process_date]
,[closed_dtm]
,[archived]
,[rearchival_date]
)
SELECT

[ssri_id]
,[ss_id]
,[period_date]
,[risk_id]
,[risk_no]
,[ro_category]
,[ro_category_description]
,[sub_category]
,[dim_ent_risk_opportunity_category_sk]
,[dim_ent_risk_opportunity_category_nk]
,[risk_title]
,[description]
,[record_date]
,[probability_range_percentage]
,[probability_range_percentage_description]
,[probability_range_percentage_display_order]
,[dim_ent_probability_range_percentage_sk]
,[dim_ent_probability_range_percentage_nk]
,[environment]
,[environment_description]
,[dim_ent_environment_sk]
,[dim_ent_environment_nk]
,[health_safety_security]
,[health_safety_security_description]
,[dim_ent_health_safety_security_sk]
,[dim_ent_health_safety_security_nk]
,[quality]
,[quality_description]
,[dim_ent_quality_sk]
,[dim_ent_quality_nk]
,[reputation]
,[reputation_description]
,[dim_ent_reputation_sk]
,[dim_ent_reputation_nk]
,[social_culture]
,[social_culture_description]
,[dim_ent_social_culture_sk]
,[dim_ent_social_culture_nk]
,[cost_impact_tcv_percentage]
,[cost_impact_tcv_percentage_description]
,[dim_ent_cost_impact_tcv_percentage_sk]
,[dim_ent_cost_impact_tcv_percentage_nk]
,[schedule]
,[schedule_description]
,[dim_ent_schedule_sk]
,[dim_ent_schedule_nk]
,[overall_impact]
,[overall_impact_description]
,[overall_impact_display_sort_order]
,[dim_ent_overall_impact_sk]
,[dim_ent_overall_impact_nk]
,[severity_score]
,[hilp]
,[risk_owner]
,[risk_status]
,[risk_status_description]
,[dim_ent_risk_status_sk]
,[dim_ent_risk_status_nk]
,[closing_justification]
,[closing_justification_description]
,[dim_ent_risk_closing_justification_sk]
,[dim_ent_risk_closing_justification_nk]
,[strategy_pre_contract]
,[strategy_pre_contract_description]
,[dim_ent_strategy_pre_contract_sk]
,[dim_ent_strategy_pre_contract_nk]
,[strategy_execution]
,[strategy_execution_description]
,[dim_ent_strategy_execution_sk]
,[dim_ent_strategy_execution_nk]
,[actions]
,[cost_mitigation]
,[action_status]
,[action_status_description]
,[dim_ent_action_status_sk]
,[dim_ent_action_status_nk]
,[action_due_date]
,[mit_probability_range_percentage]
,[mit_probability_range_percentage_description]
,[mit_probability_range_percentage_display_order]
,[dim_ent_mit_probability_range_percentage_sk]
,[dim_ent_mit_probability_range_percentage_nk]
,[mit_environment]
,[mit_environment_description]
,[dim_ent_mit_environment_sk]
,[dim_ent_mit_environment_nk]
,[mit_health_safety_security]
,[mit_health_safety_security_description]
,[dim_ent_mit_health_safety_security_sk]
,[dim_ent_mit_health_safety_security_nk]
,[mit_quality]
,[mit_quality_description]
,[dim_ent_mit_quality_sk]
,[dim_ent_mit_quality_nk]
,[mit_reputation]
,[mit_reputation_description]
,[dim_ent_mit_reputation_sk]
,[dim_ent_mit_reputation_nk]
,[mit_social_culture]
,[mit_social_culture_description]
,[dim_ent_mit_social_culture_sk]
,[dim_ent_mit_social_culture_nk]
,[mit_cost_impact_tcv_percentage]
,[mit_cost_impact_tcv_percentage_description]
,[dim_ent_mit_cost_impact_tcv_percentage_sk]
,[dim_ent_mit_cost_impact_tcv_percentage_nk]
,[mit_schedule]
,[mit_schedule_description]
,[dim_ent_mit_schedule_sk]
,[dim_ent_mit_schedule_nk]
,[mit_overall_impact]
,[mit_overall_impact_description]
,[mit_overall_impact_display_sort_order]
,[dim_ent_mit_overall_impact_sk]
,[dim_ent_mit_overall_impact_nk]
,[mit_severity_score]
,[mit_hilp]
,[probability]
,[best_case]
,[most_likely]
,[worst_case]
,[discrete_value]
,[bottom_value]
,[top_value]
,[lower_probability]
,[min_value]
,[max_value]
,[distribution_type]
,[distribution_type_description]
,[dim_ent_distribution_type_sk]
,[dim_ent_distribution_type_nk]
,[risk_function1]
,[mit_probability]
,[mit_best_case]
,[mit_most_likely]
,[mit_worst_case]
,[mit_discrete_value]
,[mit_bottom_value]
,[mit_top_value]
,[mit_lower_probability]
,[mit_min_value]
,[mit_max_value]
,[risk_function_2]
,[shared_externaly]
,[shared_externaly_description]
,[dim_ent_shared_externaly_sk]
,[dim_ent_shared_externaly_nk]
,[drivers_causes]
,[risk_due_date]
,[mit_cost]
,[risk_modeling_tech]
,[risk_modeling_tech_description]
,[dim_ent_risk_modeling_tech_sk]
,[dim_ent_risk_modeling_tech_nk]
,[t_project_id]
,[mit_fully_transferred]
,[mit_fully_transferred_description]
,[dim_ent_mit_fully_transferred_sk]
,[dim_ent_mit_fully_transferred_nk]
,[mit_fully_avoided]
,[mit_fully_avoided_description]
,[dim_ent_mit_fully_avoided_sk]
,[dim_ent_mit_fully_avoided_nk]
,[active_flag]
,[created_by]
,[created_dtm]
,[version_no]
,[expected_value_at_risk]
,[weighted_value_at_risk]
,[cost_impact_ranging_basis]
,[expected_value_at_risk_pre_contract]
,[dim_ent_promt_project_sk]
,[dim_ent_promt_project_nk]
,[project_no]						
,[project_pc_code]					
,[project_pc_code_description]		
,[project_bid_project_id]			
,[project_project_title]				
,[project_client_name]				
,[project_business_line]				
,[project_business_line_description]	
,[project_country]					
,[project_manager]					
,[project_prom_lead]					
,[project_category]					
,[project_category_description]		
,[project_total_contract_value]		
,[project_estimated_cost]			
,[project_currency_code]				
,[project_currency_code_description]	
,[project_contract_type]				
,[project_contract_type_description]	
,[project_total_duration]			
,[project_document_revision_no]		
,[project_document_revision_date]	
,[project_revisied_by]				
,[project_approved_by]				
,[project_award_date]				
,[project_active_flag]				
,[project_project_type]				
,[project_project_type_description]	
,[project_duration_type]				
,[project_version_no]				
,[project_status]					
,[project_status_description]		
,[dl_touched_dtm]
,[process_date]
,[closed_dtm]
,[archived]
,[rearchival_date]

FROM promt.stage_promt_datalake_export_risk_snapshot

WHERE   
[dim_ent_risk_opportunity_category_sk]
IS NULL OR [dim_ent_risk_opportunity_category_nk]
IS NULL OR [dim_ent_probability_range_percentage_sk]
IS NULL OR [dim_ent_probability_range_percentage_nk]
IS NULL OR [dim_ent_environment_sk]
IS NULL OR [dim_ent_environment_nk]
IS NULL OR [dim_ent_health_safety_security_sk]
IS NULL OR [dim_ent_health_safety_security_nk]
IS NULL OR [dim_ent_quality_sk]
IS NULL OR [dim_ent_quality_nk]
IS NULL OR [dim_ent_reputation_sk]
IS NULL OR [dim_ent_reputation_nk]
IS NULL OR [dim_ent_social_culture_sk]
IS NULL OR [dim_ent_social_culture_nk]
IS NULL OR [dim_ent_cost_impact_tcv_percentage_sk]
IS NULL OR [dim_ent_cost_impact_tcv_percentage_nk]
IS NULL OR [dim_ent_schedule_sk]
IS NULL OR [dim_ent_schedule_nk]
IS NULL OR [dim_ent_risk_status_sk]
IS NULL OR [dim_ent_risk_status_nk]
IS NULL OR [dim_ent_risk_closing_justification_sk]
IS NULL OR [dim_ent_risk_closing_justification_nk]
IS NULL OR [dim_ent_strategy_pre_contract_sk]
IS NULL OR [dim_ent_strategy_pre_contract_nk]
IS NULL OR [dim_ent_strategy_execution_sk]
IS NULL OR [dim_ent_strategy_execution_nk]
IS NULL OR [dim_ent_action_status_sk]
IS NULL OR [dim_ent_action_status_nk]
IS NULL OR [dim_ent_mit_probability_range_percentage_sk]
IS NULL OR [dim_ent_mit_probability_range_percentage_nk]
IS NULL OR [dim_ent_mit_environment_sk]
IS NULL OR [dim_ent_mit_environment_nk]
IS NULL OR [dim_ent_mit_health_safety_security_sk]
IS NULL OR [dim_ent_mit_health_safety_security_nk]
IS NULL OR [dim_ent_mit_quality_sk]
IS NULL OR [dim_ent_mit_quality_nk]
IS NULL OR [dim_ent_mit_reputation_sk]
IS NULL OR [dim_ent_mit_reputation_nk]
IS NULL OR [dim_ent_mit_social_culture_sk]
IS NULL OR [dim_ent_mit_social_culture_nk]
IS NULL OR [dim_ent_mit_cost_impact_tcv_percentage_sk]
IS NULL OR [dim_ent_mit_cost_impact_tcv_percentage_nk]
IS NULL OR [dim_ent_mit_schedule_sk]
IS NULL OR [dim_ent_mit_schedule_nk]
IS NULL OR [dim_ent_distribution_type_sk]
IS NULL OR [dim_ent_distribution_type_nk]
IS NULL OR [dim_ent_shared_externaly_sk]
IS NULL OR [dim_ent_shared_externaly_nk]
IS NULL OR [dim_ent_risk_modeling_tech_sk]
IS NULL OR [dim_ent_risk_modeling_tech_nk]
IS NULL OR [dim_ent_mit_fully_transferred_sk]
IS NULL OR [dim_ent_mit_fully_transferred_nk]
IS NULL OR [dim_ent_mit_fully_avoided_sk]
IS NULL OR [dim_ent_mit_fully_avoided_nk]
IS NULL OR [dim_ent_promt_project_sk]
IS NULL OR [dim_ent_promt_project_nk]
IS NULL OR [dim_ent_overall_impact_sk]
IS NULL OR [dim_ent_overall_impact_nk]
IS NULL OR [dim_ent_mit_overall_impact_sk]
IS NULL OR [dim_ent_mit_overall_impact_nk]
IS NULL
;
		

UPDATE promt.stage_promt_datalake_export_risk_snapshot
set process_date = GETDATE();

UPDATE promt.reprocess_promt_datalake_export_risk_snapshot
set process_date = GETDATE();

UPDATE promt.reprocess_promt_datalake_export_risk_snapshot
set created_date_time = GETDATE();

	---------------------------------------------------------------------------

DELETE FROM promt.stage_promt_datalake_export_risk_snapshot
WHERE   
[dim_ent_risk_opportunity_category_sk]
IS NULL OR [dim_ent_risk_opportunity_category_nk]
IS NULL OR [dim_ent_probability_range_percentage_sk]
IS NULL OR [dim_ent_probability_range_percentage_nk]
IS NULL OR [dim_ent_environment_sk]
IS NULL OR [dim_ent_environment_nk]
IS NULL OR [dim_ent_health_safety_security_sk]
IS NULL OR [dim_ent_health_safety_security_nk]
IS NULL OR [dim_ent_quality_sk]
IS NULL OR [dim_ent_quality_nk]
IS NULL OR [dim_ent_reputation_sk]
IS NULL OR [dim_ent_reputation_nk]
IS NULL OR [dim_ent_social_culture_sk]
IS NULL OR [dim_ent_social_culture_nk]
IS NULL OR [dim_ent_cost_impact_tcv_percentage_sk]
IS NULL OR [dim_ent_cost_impact_tcv_percentage_nk]
IS NULL OR [dim_ent_schedule_sk]
IS NULL OR [dim_ent_schedule_nk]
IS NULL OR [dim_ent_risk_status_sk]
IS NULL OR [dim_ent_risk_status_nk]
IS NULL OR [dim_ent_risk_closing_justification_sk]
IS NULL OR [dim_ent_risk_closing_justification_nk]
IS NULL OR [dim_ent_strategy_pre_contract_sk]
IS NULL OR [dim_ent_strategy_pre_contract_nk]
IS NULL OR [dim_ent_strategy_execution_sk]
IS NULL OR [dim_ent_strategy_execution_nk]
IS NULL OR [dim_ent_action_status_sk]
IS NULL OR [dim_ent_action_status_nk]
IS NULL OR [dim_ent_mit_probability_range_percentage_sk]
IS NULL OR [dim_ent_mit_probability_range_percentage_nk]
IS NULL OR [dim_ent_mit_environment_sk]
IS NULL OR [dim_ent_mit_environment_nk]
IS NULL OR [dim_ent_mit_health_safety_security_sk]
IS NULL OR [dim_ent_mit_health_safety_security_nk]
IS NULL OR [dim_ent_mit_quality_sk]
IS NULL OR [dim_ent_mit_quality_nk]
IS NULL OR [dim_ent_mit_reputation_sk]
IS NULL OR [dim_ent_mit_reputation_nk]
IS NULL OR [dim_ent_mit_social_culture_sk]
IS NULL OR [dim_ent_mit_social_culture_nk]
IS NULL OR [dim_ent_mit_cost_impact_tcv_percentage_sk]
IS NULL OR [dim_ent_mit_cost_impact_tcv_percentage_nk]
IS NULL OR [dim_ent_mit_schedule_sk]
IS NULL OR [dim_ent_mit_schedule_nk]
IS NULL OR [dim_ent_distribution_type_sk]
IS NULL OR [dim_ent_distribution_type_nk]
IS NULL OR [dim_ent_shared_externaly_sk]
IS NULL OR [dim_ent_shared_externaly_nk]
IS NULL OR [dim_ent_risk_modeling_tech_sk]
IS NULL OR [dim_ent_risk_modeling_tech_nk]
IS NULL OR [dim_ent_mit_fully_transferred_sk]
IS NULL OR [dim_ent_mit_fully_transferred_nk]
IS NULL OR [dim_ent_mit_fully_avoided_sk]
IS NULL OR [dim_ent_mit_fully_avoided_nk]
IS NULL OR [dim_ent_promt_project_sk]
IS NULL OR [dim_ent_promt_project_nk]
IS NULL OR [dim_ent_overall_impact_sk]
IS NULL OR [dim_ent_overall_impact_nk]
IS NULL OR [dim_ent_mit_overall_impact_sk]
IS NULL OR [dim_ent_mit_overall_impact_nk]
IS NULL
;
		



if isnull(@processed_count,0) > 0 
	begin
		select @error_message = 'Total records processed is ' + convert(varchar(40),@processed_count)
	end
	select @error_message = isnull(@error_message,'')
	if isnull(@unprocessed_count,0) > 0 
	begin
		select @error_message = @error_message + 'Total records failed validation ' + convert(varchar(40),@unprocessed_count)
		
	
	end

	if isnull(@unprocessed_count,0) = 0 --isnull(@error_message,'') = '' 
	begin
	  select 'Success'; 
	end
	else
	begin
      select @error_message ;
	end

end try
begin catch
	if @errorMessage is not null 
	begin
		select 'Failed', @errorMessage;
	end
	else
	begin
		--select 'Falied', error_message()

		DECLARE @sp_failureMessage nvarchar(4000), @sp_failureSeverity int, @sp_failureStatus int;

		SET @sp_failureSeverity=ERROR_SEVERITY();
		SET @sp_failureStatus=ERROR_STATE();
	
		SET @sp_failureMessage =  
		  'Error_No: ' + CAST(ERROR_NUMBER() AS VARCHAR) + ' ||'+
		  'Error_Severity: ' + CAST(ERROR_SEVERITY() AS VARCHAR) + ' ||' +
		  'Error State: ' + CAST(ERROR_STATE() AS VARCHAR) + ' ||' +
		  'SPName: ' + ERROR_PROCEDURE() + ' ||' +
		  'Error_Message: ' + ERROR_MESSAGE() + ' ||' ;

		SELECT @sp_failureMessage as failureMessage
		RAISERROR (@sp_failureMessage, @sp_failureSeverity, @sp_failureStatus);
		


	end;
end catch;


--End of Stored Procedure
END
GO

