CREATE VIEW [dbo].[dim_entp_pcm_ndt_details_vw]
AS Select
       a.[dim_entp_pcm_ndt_details_sk]
      ,a.[dim_entp_pcm_ndt_details_nk]
      ,a.[start_date]
      ,a.[end_date]
      ,a.[hash_code]
      ,a.[active]
      ,a.[created_date_time]
      ,a.[modified_date_time]
      ,a.[late_arrival_flag]
      ,a.[dim_ent_source_nk]
      ,a.[dim_ent_sub_source_nk]
      ,a.[dim_ent_contract_nk]
      ,a.[dim_entp_pcm_job_item_nk]
      ,a.[ndt_drawing]
      ,a.[ndt_drawing_desc]
      ,CAST([trans_date] as DATE) AS trans_date
      ,a.[trans_type]
      ,a.[fab_code]
      ,a.[wctrl]
      ,a.[weld_suffix]
      ,a.[stress_relief]
      ,a.[weld_repair_ref]
      ,a.[ndt_type]
      ,a.[weldcount]
      ,a.[spool]
      ,a.[report_num]
      ,a.[ndt_procedure]
      ,a.[ndt_percent]
      ,a.[test_percent]
      ,CAST([test_date] as DATE) AS test_date
      ,a.[pass_fail]
      ,a.[narrative]
      ,a.[inspector]
      ,a.[insp_name]
      ,a.[signed]
      ,a.[sign_override]
      ,a.[clt_jrm]
      ,a.[signatory]
      ,CAST([sign_date] as DATE) AS sign_date 
      ,a.[remarks]
      ,a.[jrm_signed]
      ,CAST([jrm_sign_date] as DATE) AS jrm_sign_date
      ,a.[jrm_technician]
      ,a.[jrm_technician_org]
      ,a.[ndt_report_format]
     ,a.[is_approval_required]
      ,a.[jrm_approver]
      ,a.[jrm_approver_signed]
     ,CAST([jrm_approver_sign_date] as DATE) AS jrm_approver_sign_date
     ,a.[defect_type]
      ,a.[defect_title]
      ,a.[defect_length]
,b.job,b.job_title,b.item,b.item_title,c.contract_number  From dbo.dim_entp_pcm_ndt_details a left join dbo.dim_entp_pcm_job_item_vw b  on a.dim_entp_pcm_job_item_nk= b.dim_entp_pcm_job_item_nk   left join dbo.dim_ent_contract_active_v c on a.dim_ent_contract_nk=c.dim_ent_contract_nk  Where a.active=1 AND a.fab_code = 'BTY';
GO