
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','noneff_id','nvarchar(50)','TEXT','NK','noneff_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','staff_number','nvarchar(50)','TEXT','NK','staff_number',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','noneff_sdate','datetime','DATETIME','OA','noneff_sdate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','noneff_reas','int','NUMBER','OA','noneff_reas',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','noneff_edate','datetime','DATETIME','OA','noneff_edate',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,5,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','noneff_state','nvarchar(25)','TEXT','OA','noneff_state',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','noneff_payable','int','NUMBER','OA','noneff_payable',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,7,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','noneff_notes','varchar(4000)','TEXT','OA','noneff_notes',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,8,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','medically_certIfied','int','NUMBER','OA','medically_certIfied',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,9,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','self_certIfied','int','NUMBER','OA','self_certIfied',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,10,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','reas_type','nvarchar(25)','TEXT','OA','reas_type',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,11,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','noneff_planned','int','NUMBER','OA','noneff_planned',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,12,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','itemtag_id','numeric(18,0)','NUMBER','OA','itemtag_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,13,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','date_created','datetime','DATETIME','OA','date_created',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,14,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','date_last_mod','datetime','DATETIME','OA','date_last_mod',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,15,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','last_edit_by','int','NUMBER','OA','last_edit_by',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','activity_id','numeric(18,0)','NUMBER','OA','activity_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,17,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','itemdb_id','numeric(4,0)','NUMBER','OA','itemdb_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,18,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','activity_db','numeric(4,0)','NUMBER','OA','activity_db',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,19,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','spare_char_1_255','nvarchar(255)','TEXT','OA','spare_char_1_255',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,20,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','spare_char_1_100','nvarchar(100)','TEXT','OA','spare_char_1_100',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,21,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','spare_char_1_50','nvarchar(50)','TEXT','OA','spare_char_1_50',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,22,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','spare_int_1','int','NUMBER','OA','spare_int_1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,23,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','spare_int_2','int','NUMBER','OA','spare_int_2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,24,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','b1m','int','NUMBER','OA','b1m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,25,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','b2m','int','NUMBER','OA','b2m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,26,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','b3m','int','NUMBER','OA','b3m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,27,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','b4m','int','NUMBER','OA','b4m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,28,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','b5m','int','NUMBER','OA','b5m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,29,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','b6m','int','NUMBER','OA','b6m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,30,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','b7m','int','NUMBER','OA','b7m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,31,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','b8m','int','NUMBER','OA','b8m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,32,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','posting_id','nvarchar(50)','TEXT','OA','posting_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,33,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','accrues_leave','int','NUMBER','OA','accrues_leave',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,34,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','account_code','nvarchar(50)','TEXT','OA','account_code',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,35,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_employ_noneffect','expected_well_date','datetime','DATETIME','OA','expected_well_date',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,36,'Y',NULL)
Insert into [dbo].[generic_load_detail] values('dim_entp_maps_employ_noneffect','dim_entp_maps_person_nk','int','NUMBER','RK','dim_entp_maps_person_nk','dim_entp_maps_person','dim_entp_maps_person_nk','id_number','staff_number',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,37,'Y',NULL)
Insert into [dbo].[generic_load_detail] values('dim_entp_maps_employ_noneffect','dim_entp_maps_reasons_nk','int','NUMBER','RK','dim_entp_maps_reasons_nk','dim_entp_maps_reasons','dim_entp_maps_reasons_nk','reas_type','reas_type',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,38,'Y',NULL)



