Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','passport_id','nvarchar(50)','TEXT','NK','passport_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','id_number','nvarchar(50)','TEXT','OA','id_number',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,2,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','country_id','nvarchar(50)','TEXT','OA','country_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,3,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','passport_number','nvarchar(50)','TEXT','OA','passport_number',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,4,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','passport_expiry_date','datetime','DATETIME','OA','passport_expiry_date',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,5,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','issuing_office','nvarchar(100)','TEXT','OA','issuing_office',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,6,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','place_of_birth','nvarchar(100)','TEXT','OA','place_of_birth',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,7,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','valid_from_date','datetime','DATETIME','OA','valid_from_date',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,8,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','valid_to_date','datetime','DATETIME','OA','valid_to_date',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,9,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','passport_type_reason_id','nvarchar(50)','TEXT','OA','passport_type_reason_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,10,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','spare_char_1_255','nvarchar(255)','TEXT','OA','spare_char_1_255',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,11,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','spare_char_1_100','nvarchar(100)','TEXT','OA','spare_char_1_100',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,12,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','spare_char_1_50','nvarchar(50)','TEXT','OA','spare_char_1_50',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,13,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','spare_int_1','int','NUMBER','OA','spare_int_1',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,14,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','spare_int_2','int','NUMBER','OA','spare_int_2',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,15,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','itemdb_id','numeric(4,0)','NUMBER','OA','itemdb_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,16,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','itemtag_id','numeric(18,0)','NUMBER','OA','itemtag_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,17,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','date_created','datetime','DATETIME','OA','date_created',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,18,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','date_last_mod','datetime','DATETIME','OA','date_last_mod',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,19,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','last_edit_by','int','NUMBER','OA','last_edit_by',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,20,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','activity_db','numeric(4,0)','NUMBER','OA','activity_db',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,21,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','activity_id','numeric(18,0)','NUMBER','OA','activity_id',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,22,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','b1m','int','NUMBER','OA','b1m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,23,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','b2m','int','NUMBER','OA','b2m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,24,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','b3m','int','NUMBER','OA','b3m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,25,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','b4m','int','NUMBER','OA','b4m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,26,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','b5m','int','NUMBER','OA','b5m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,25,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','b6m','int','NUMBER','OA','b6m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,26,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','b7m','int','NUMBER','OA','b7m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,27,'Y',NULL)
Insert into [dbo].[generic_load_detail] values ('dim_entp_maps_passport','b8m','int','NUMBER','OA','b8m',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,28,'Y',NULL)
Insert into [dbo].[generic_load_detail] values('dim_entp_maps_passport','dim_entp_maps_person_nk','int','NUMBER','RK','dim_entp_maps_person_nk','dim_entp_maps_person','dim_entp_maps_person_nk','id_number','id_number',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,29,'Y',NULL)


