insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_risk_source_to_stage','PROMT','pl_promt_datalake_export_risk_source_to_stage',NULL,'1','aditya.anand2@mcdermott.com','2023-11-30 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_risk_stage_to_raw','PROMT','pl_promt_datalake_export_risk_stage_to_raw',NULL,'1','aditya.anand2@mcdermott.com','2023-11-30 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_risk_raw_to_synapse','PROMT','pl_promt_datalake_export_risk_raw_to_synapse',NULL,'1','aditya.anand2@mcdermott.com','2023-11-30 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_risk_master_pipeline','PROMT','pl_promt_datalake_export_risk_master_pipeline',NULL,'1','aditya.anand2@mcdermott.com','2023-11-30 06:42:19.043',153)


insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_opportunity_source_to_stage','PROMT','pl_promt_datalake_export_opportunity_source_to_stage',NULL,'1','aditya.anand2@mcdermott.com','2023-11-30 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_opportunity_stage_to_raw','PROMT','pl_promt_datalake_export_opportunity_stage_to_raw',NULL,'1','aditya.anand2@mcdermott.com','2023-11-30 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_opportunity_raw_to_synapse','PROMT','pl_promt_datalake_export_opportunity_raw_to_synapse',NULL,'1','aditya.anand2@mcdermott.com','2023-11-30 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_opportunity_master_pipeline','PROMT','pl_promt_datalake_export_opportunity_master_pipeline',NULL,'1','aditya.anand2@mcdermott.com','2023-11-30 06:42:19.043',153)


insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_simulationresult_source_to_stage','PROMT','pl_promt_datalake_export_simulationresult_source_to_stage',NULL,'1','aditya.anand2@mcdermott.com','2023-12-14 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_simulationresult_stage_to_raw','PROMT','pl_promt_datalake_export_simulationresult_stage_to_raw',NULL,'1','aditya.anand2@mcdermott.com','2023-12-14 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_simulationresult_raw_to_synapse','PROMT','pl_promt_datalake_export_simulationresult_raw_to_synapse',NULL,'1','aditya.anand2@mcdermott.com','2023-12-14 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_simulationresult_master_pipeline','PROMT','pl_promt_datalake_export_simulationresult_master_pipeline',NULL,'1','aditya.anand2@mcdermott.com','2023-12-14 06:42:19.043',153)


insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_contingency_source_to_stage','PROMT','pl_promt_datalake_export_contingency_source_to_stage',NULL,'1','aditya.anand2@mcdermott.com','2024-01-31 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_contingency_stage_to_raw','PROMT','pl_promt_datalake_export_contingency_stage_to_raw',NULL,'1','aditya.anand2@mcdermott.com','2024-01-31 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_contingency_raw_to_synapse','PROMT','pl_promt_datalake_export_contingency_raw_to_synapse',NULL,'1','aditya.anand2@mcdermott.com','2024-01-31 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_contingency_master_pipeline','PROMT','pl_promt_datalake_export_contingency_master_pipeline',NULL,'1','aditya.anand2@mcdermott.com','2024-01-31 06:42:19.043',153)

insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_risk_snapshot_source_to_stage','PROMT','pl_promt_datalake_export_risk_snapshot_source_to_stage',NULL,'1','aditya.anand2@mcdermott.com','2024-02-16 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_risk_snapshot_stage_to_raw','PROMT','pl_promt_datalake_export_risk_snapshot_stage_to_raw',NULL,'1','aditya.anand2@mcdermott.com','2024-02-16 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_risk_snapshot_raw_to_synapse','PROMT','pl_promt_datalake_export_risk_snapshot_raw_to_synapse',NULL,'1','aditya.anand2@mcdermott.com','2024-02-16 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_risk_snapshot_master_pipeline','PROMT','pl_promt_datalake_export_risk_snapshot_master_pipeline',NULL,'1','aditya.anand2@mcdermott.com','2024-02-16 06:42:19.043',153)

insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_opportunity_snapshot_source_to_stage','PROMT','pl_promt_datalake_export_opportunity_snapshot_source_to_stage',NULL,'1','aditya.anand2@mcdermott.com','2024-02-16 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_opportunity_snapshot_stage_to_raw','PROMT','pl_promt_datalake_export_opportunity_snapshot_stage_to_raw',NULL,'1','aditya.anand2@mcdermott.com','2024-02-16 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_opportunity_snapshot_raw_to_synapse','PROMT','pl_promt_datalake_export_opportunity_snapshot_raw_to_synapse',NULL,'1','aditya.anand2@mcdermott.com','2024-02-16 06:42:19.043',153)
insert into plp_pipeline (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) Values('pl_promt_datalake_export_opportunity_snapshot_master_pipeline','PROMT','pl_promt_datalake_export_opportunity_snapshot_master_pipeline',NULL,'1','aditya.anand2@mcdermott.com','2024-02-16 06:42:19.043',153)

