
CREATE TABLE [dbo].[dim_entp_maps_posting]
(
	[dim_entp_maps_posting_sk] 			[bigint] IDENTITY(1,1) NOT NULL,
	[dim_entp_maps_posting_nk] 			[bigint] NOT NULL,
	[posting_id] 						[nvarchar](50) null,
	[post_id] 							[nvarchar](50) null,
	[id_number] 						[nchar](50) null,	
	[start_date] 						[datetime] NOT NULL,
	[end_date] 							[datetime] NOT NULL,
	[hash_code] 						[varchar](8000) NOT NULL,
	[late_arrival_flag] 				[varchar](1) NOT NULL,
	[active] 							[int] NOT NULL,
	[created_date_time] 				[datetime] NULL,
	[modified_date_time] 				[datetime] NULL,
	[org_group_id] 						[nchar](50) null,
	[posting_sdate] 					[datetime] null,
	[epostg_rtype] 						[nvarchar](50) null,
	[posting_ereas] 					[int] null,
	[posting_edate] 					[datetime] null,
	[posting_rdate] 					[datetime] null,
	[part_time_hrs] 					[float] null,
	[pg_type_id] 						[nchar](50) null,
	[fall_back_post_id] 				[nvarchar](50) null,
	[notes] 							[nvarchar](2048) null,
	[carry_over_leave] 					[decimal](5, 2) null,
	[leave_taken] 						[decimal](5, 2) null,
	[liquidated_leave] 					[money] null,
	[last_calc_on] 						[datetime] null,
	[calc_for_date] 					[datetime] null,
	[leave_accrued] 					[int] null,
	[probationary_period] 				[int] null,
	[confirmed_start_date] 				[datetime] null,
	[confirmed_end_date] 				[datetime] null,
	[sob_person_id] 					[nvarchar](50) null,
	[posting_extra_code_1] 				[nvarchar](50) null,
	[posting_extra_code_2] 				[nvarchar](50) null,
	[is_suspect] 						[int] null,
	[suspect_date] 						[datetime] null,
	[temp_pwc_id] 						[nchar](50) null,
	[transit_days_before] 				[decimal](5, 2) null,
	[transit_days_after] 				[decimal](5, 2) null,
	[posting_check_box_1] 				[int] null,
	[posting_check_box_2] 				[int] null,
	[travel_required] 					[int] null,
	[posting_start_reason_id] 			[nchar](50) null,
	[itemtag_id] 						[numeric](18, 0) null,
	[itemdb_id] 						[numeric](4, 0) null,
	[date_created] 						[datetime] null,
	[date_last_mod] 					[datetime] null,
	[last_edit_by] 						[int] null,
	[activity_id] 						[numeric](18, 0) null,
	[activity_db] 						[numeric](4, 0) null,
	[spare_char_1_255] 					[nvarchar](255) null,
	[spare_char_1_100] 					[nvarchar](100) null,
	[spare_char_1_50] 					[nvarchar](50) null,
	[spare_int_1] 						[int] null,
	[spare_int_2] 						[int] null,
	[b1m] 								[int] null,
	[b2m] 								[int] null,
	[b3m] 								[int] null,
	[b4m] 								[int] null,
	[b5m] 								[int] null,
	[b6m] 								[int] null,
	[b7m] 								[int] null,
	[b8m] 								[int] null,
	[orig_post_id] 						[nvarchar](50) null,
	[dim_entp_maps_person_nk]			[int] null,	
	[dim_entp_maps_post_nk]				[int] null,
	[dim_entp_maps_post_location_nk]	[int] null,
	[dim_entp_maps_posting_location_nk]	[int] null,
	[dim_entp_maps_authorised_user_nk]	[int] null,
	
 CONSTRAINT [Constr_dim_entp_maps_posting_sk] PRIMARY KEY NONCLUSTERED 
	(
		[dim_entp_maps_posting_sk] ASC
	) NOT ENFORCED 
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
