CREATE TABLE [gpd].[reprocess_dim_entp_maps_person]
(
	[rssk] [int] IDENTITY(1,1) NOT NULL,
	[created_date_time] [datetime] NULL,
	[hash_code] [varchar](4000) NULL,
	[id_number] [nchar](27) NULL,
	[prfscid_code] [nvarchar](15) NULL,
	[pleave_rtype] [nvarchar](15) NULL,
	[leave_reas] [int] NULL,
	[title_rank] [nvarchar](8) NULL,
	[surname] [nvarchar](40) NULL,
	[forenames] [nvarchar](32) NULL,
	[initials] [nvarchar](32) NULL,
	[date_leaving] [datetime] NULL,
	[part_time_acceptable] [nvarchar](10) NULL,
	[part_time] [nvarchar](10) NULL,
	[part_time_hours] [nvarchar](15) NULL,
	[date_joined] [datetime] NULL,
	[extra_code_1] [nvarchar](50) NULL,
	[extra_code_2] [nvarchar](50) NULL,
	[person_type] [nchar](8) NULL,
	[grade_sht_title] [nvarchar](12) NULL,
	[tkt_grd_sht_title] [nvarchar](12) NULL,
	[employee_type] [int] NULL,
	[sex] [nvarchar](6) NULL,
	[date_birth] [datetime] NULL,
	[marital_status] [nvarchar](11) NULL,
	[surplus_sdate] [datetime] NULL,
	[supern_sdate] [datetime] NULL,
	[date_ott_dus] [datetime] NULL,
	[promotion_ryear] [nvarchar](4) NULL,
	[eret_date] [datetime] NULL,
	[ret_date] [datetime] NULL,
	[ret_dec] [nvarchar](13) NULL,
	[asr_despatch] [datetime] NULL,
	[asr_issue] [datetime] NULL,
	[asr_actual_return] [datetime] NULL,
	[date_av_post] [datetime] NULL,
	[disabled_number] [nvarchar](10) NULL,
	[seniority_date] [datetime] NULL,
	[comp_name] [nvarchar](30) NULL,
	[date_contract] [datetime] NULL,
	[student_type_id] [nvarchar](27) NULL,
	[dietary_requirements] [nvarchar](100) NULL,
	[special_needs] [nvarchar](255) NULL,
	[country_of_orgin] [nvarchar](50) NULL,
	[telephone_number] [nvarchar](20) NULL,
	[students_company] [nvarchar](50) NULL,
	[notes] [nvarchar](2048) NULL,
	[previous_employee] [nvarchar](10) NULL,
	[applicant_id] [nchar](27) NULL,
	[blood_type] [nvarchar](10) NULL,
	[e_mail_name] [nvarchar](50) NULL,
	[sob_type_id] [nchar](27) NULL,
	[lifetime_sob] [nvarchar](10) NULL,
	[nationality_id] [nchar](27) NULL,
	[person_check_box_1] [nvarchar](10) NULL,
	[person_check_box_2] [nvarchar](10) NULL,
	[person_check_box_3] [nvarchar](10) NULL,
	[companion_id_number] [nchar](27) NULL,
	[is_smoker] [nvarchar](10) NULL,
	[travel_provider_id] [nvarchar](27) NULL,
	[hair_reason_id] [nchar](27) NULL,
	[eye_reason_id] [nchar](27) NULL,
	[person_weight] [nvarchar](10) NULL,
	[person_height] [nvarchar](10) NULL,
	[shoe_size] [nvarchar](10) NULL,
	[uniform_size] [nvarchar](10) NULL,
	[place_of_birth] [nvarchar](100) NULL,
	[itemtag_id] [numeric](18, 0) NULL,
	[itemdb_id] [numeric](4, 0) NULL,
	[date_created] [datetime] NULL,
	[date_last_mod] [datetime] NULL,
	[last_edit_by] [int] NULL,
	[activity_id] [numeric](18, 0) NULL,
	[activity_db] [numeric](4, 0) NULL,
	[spare_char_1_255] [nvarchar](255) NULL,
	[spare_char_1_100] [nvarchar](100) NULL,
	[spare_char_1_50] [nvarchar](50) NULL,
	[spare_int_1] [int] NULL,
	[spare_int_2] [int] NULL,
	[b1m] [int] NULL,
	[b2m] [int] NULL,
	[b3m] [int] NULL,
	[b4m] [int] NULL,
	[b5m] [int] NULL,
	[b6m] [int] NULL,
	[b7m] [int] NULL,
	[b8m] [int] NULL,
	[country_of_birth_id] [nchar](27) NULL,
	[person_known_as] [nvarchar](50) NULL,
	[employ_type_name] [nvarchar](15) NULL,
	[employ_type_desc] [nvarchar](100) NULL,
	[rk_failure_info] [varchar](4000) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

