CREATE TABLE [promt].[stage_promt_datalake_export_risk]
(
	[stage_promt_datalake_export_risk_id] [int] IDENTITY(1,1) NOT NULL,
	[risk_id] [int] NULL,
	[risk_no] [int] NULL,
	[ro_category] [varchar](500) NULL,
	[ro_category_description] [varchar](500) NULL,
	[sub_category] [varchar](500) NULL,
	[dim_ent_risk_opportunity_category_sk] [int] NULL,
	[dim_ent_risk_opportunity_category_nk] [int] NULL,
	[risk_title] [varchar](1000) NULL,
	[description] [varchar](8000) NULL,
	[record_date] [datetime] NULL,
	[probability_range_percentage] [varchar](500) NULL,
	[probability_range_percentage_description] [varchar](500) NULL,
	[probability_range_percentage_display_order] [varchar](10) NULL,
	[dim_ent_probability_range_percentage_sk] [int] NULL,
	[dim_ent_probability_range_percentage_nk] [int] NULL,
	[environment] [varchar](500) NULL,
	[environment_description] [varchar](500) NULL,
	[dim_ent_environment_sk] [int] NULL,
	[dim_ent_environment_nk] [int] NULL,
	[health_safety_security] [varchar](500) NULL,
	[health_safety_security_description] [varchar](500) NULL,
	[dim_ent_health_safety_security_sk] [int] NULL,
	[dim_ent_health_safety_security_nk] [int] NULL,
	[quality] [varchar](500) NULL,
	[quality_description] [varchar](500) NULL,
	[dim_ent_quality_sk] [int] NULL,
	[dim_ent_quality_nk] [int] NULL,
	[reputation] [varchar](500) NULL,
	[reputation_description] [varchar](500) NULL,
	[dim_ent_reputation_sk] [int] NULL,
	[dim_ent_reputation_nk] [int] NULL,
	[social_culture] [varchar](500) NULL,
	[social_culture_description] [varchar](500) NULL,
	[dim_ent_social_culture_sk] [int] NULL,
	[dim_ent_social_culture_nk] [int] NULL,
	[cost_impact_tcv_percentage] [varchar](500) NULL,
	[cost_impact_tcv_percentage_description] [varchar](500) NULL,
	[dim_ent_cost_impact_tcv_percentage_sk] [int] NULL,
	[dim_ent_cost_impact_tcv_percentage_nk] [int] NULL,
	[schedule] [varchar](500) NULL,
	[schedule_description] [varchar](500) NULL,
	[dim_ent_schedule_sk] [int] NULL,
	[dim_ent_schedule_nk] [int] NULL,
	[overall_impact] [varchar](10) NULL,
	[overall_impact_description] [varchar](500) NULL,
	[overall_impact_display_sort_order] [varchar](10) NULL,
	[dim_ent_overall_impact_sk] [int] NULL,
	[dim_ent_overall_impact_nk] [int] NULL,
	[severity_score] [int] NULL,
	[hilp] [varchar](500) NULL,
	[risk_owner] [varchar](500) NULL,
	[risk_status] [varchar](500) NULL,
	[risk_status_description] [varchar](500) NULL,
	[dim_ent_risk_status_sk] [int] NULL,
	[dim_ent_risk_status_nk] [int] NULL,
	[closing_justification] [varchar](500) NULL,
	[closing_justification_description] [varchar](500) NULL,
	[dim_ent_risk_closing_justification_sk] [int] NULL,
	[dim_ent_risk_closing_justification_nk] [int] NULL,
	[strategy_pre_contract] [varchar](500) NULL,
	[strategy_pre_contract_description] [varchar](500) NULL,
	[dim_ent_strategy_pre_contract_sk] [int] NULL,
	[dim_ent_strategy_pre_contract_nk] [int] NULL,
	[strategy_execution] [varchar](500) NULL,
	[strategy_execution_description] [varchar](500) NULL,
	[dim_ent_strategy_execution_sk] [int] NULL,
	[dim_ent_strategy_execution_nk] [int] NULL,
	[actions] [varchar](8000) NULL,
	[cost_mitigation] [decimal](15, 2) NULL,
	[action_status] [varchar](500) NULL,
	[action_status_description] [varchar](500) NULL,
	[dim_ent_action_status_sk] [int] NULL,
	[dim_ent_action_status_nk] [int] NULL,
	[action_due_date] [datetime] NULL,
	[mit_probability_range_percentage] [varchar](500) NULL,
	[mit_probability_range_percentage_description] [varchar](500) NULL,
	[mit_probability_range_percentage_display_order] [varchar](10) NULL,
	[dim_ent_mit_probability_range_percentage_sk] [int] NULL,
	[dim_ent_mit_probability_range_percentage_nk] [int] NULL,
	[mit_environment] [varchar](500) NULL,
	[mit_environment_description] [varchar](500) NULL,
	[dim_ent_mit_environment_sk] [int] NULL,
	[dim_ent_mit_environment_nk] [int] NULL,
	[mit_health_safety_security] [varchar](500) NULL,
	[mit_health_safety_security_description] [varchar](500) NULL,
	[dim_ent_mit_health_safety_security_sk] [int] NULL,
	[dim_ent_mit_health_safety_security_nk] [int] NULL,
	[mit_quality] [varchar](500) NULL,
	[mit_quality_description] [varchar](500) NULL,
	[dim_ent_mit_quality_sk] [int] NULL,
	[dim_ent_mit_quality_nk] [int] NULL,
	[mit_reputation] [varchar](500) NULL,
	[mit_reputation_description] [varchar](500) NULL,
	[dim_ent_mit_reputation_sk] [int] NULL,
	[dim_ent_mit_reputation_nk] [int] NULL,
	[mit_social_culture] [varchar](500) NULL,
	[mit_social_culture_description] [varchar](500) NULL,
	[dim_ent_mit_social_culture_sk] [int] NULL,
	[dim_ent_mit_social_culture_nk] [int] NULL,
	[mit_cost_impact_tcv_percentage] [varchar](500) NULL,
	[mit_cost_impact_tcv_percentage_description] [varchar](500) NULL,
	[dim_ent_mit_cost_impact_tcv_percentage_sk] [int] NULL,
	[dim_ent_mit_cost_impact_tcv_percentage_nk] [int] NULL,
	[mit_schedule] [varchar](500) NULL,
	[mit_schedule_description] [varchar](500) NULL,
	[dim_ent_mit_schedule_sk] [int] NULL,
	[dim_ent_mit_schedule_nk] [int] NULL,
	[mit_overall_impact] [varchar](10) NULL,
	[mit_overall_impact_description] [varchar](500) NULL,
	[mit_overall_impact_display_sort_order] [varchar](10) NULL,
	[dim_ent_mit_overall_impact_sk] [int] NULL,
	[dim_ent_mit_overall_impact_nk] [int] NULL,
	[mit_severity_score] [int] NULL,
	[mit_hilp] [varchar](500) NULL,
	[probability] [decimal](15, 2) NULL,
	[best_case] [decimal](15, 2) NULL,
	[most_likely] [decimal](15, 2) NULL,
	[worst_case] [decimal](15, 2) NULL,
	[discrete_value] [decimal](15, 2) NULL,
	[bottom_value] [decimal](15, 2) NULL,
	[top_value] [decimal](15, 2) NULL,
	[lower_probability] [decimal](15, 2) NULL,
	[min_value] [decimal](15, 2) NULL,
	[max_value] [decimal](15, 2) NULL,
	[distribution_type] [varchar](500) NULL,
	[distribution_type_description] [varchar](500) NULL,
	[dim_ent_distribution_type_sk] [int] NULL,
	[dim_ent_distribution_type_nk] [int] NULL,
	[risk_function1] [decimal](15, 2) NULL,
	[mit_probability] [decimal](15, 2) NULL,
	[mit_best_case] [decimal](15, 2) NULL,
	[mit_most_likely] [decimal](15, 2) NULL,
	[mit_worst_case] [decimal](15, 2) NULL,
	[mit_discrete_value] [decimal](15, 2) NULL,
	[mit_bottom_value] [decimal](15, 2) NULL,
	[mit_top_value] [decimal](15, 2) NULL,
	[mit_lower_probability] [decimal](15, 2) NULL,
	[mit_min_value] [decimal](15, 2) NULL,
	[mit_max_value] [decimal](15, 2) NULL,
	[risk_function_2] [decimal](15, 2) NULL,
	[shared_externaly] [varchar](5) NULL,
	[shared_externaly_description] [varchar](1000) NULL,
	[dim_ent_shared_externaly_sk] [int] NULL,
	[dim_ent_shared_externaly_nk] [int] NULL,
	[drivers_causes] [varchar](8000) NULL,
	[risk_due_date] [datetime] NULL,
	[mit_cost] [decimal](15, 2) NULL,
	[risk_modeling_tech] [varchar](500) NULL,
	[risk_modeling_tech_description] [varchar](500) NULL,
	[dim_ent_risk_modeling_tech_sk] [int] NULL,
	[dim_ent_risk_modeling_tech_nk] [int] NULL,
	[t_project_id] [int] NULL,
	[mit_fully_transferred] [varchar](1) NULL,
	[mit_fully_transferred_description] [varchar](500) NULL,
	[dim_ent_mit_fully_transferred_sk] [int] NULL,
	[dim_ent_mit_fully_transferred_nk] [int] NULL,
	[mit_fully_avoided] [varchar](1) NULL,
	[mit_fully_avoided_description] [varchar](500) NULL,
	[dim_ent_mit_fully_avoided_sk] [int] NULL,
	[dim_ent_mit_fully_avoided_nk] [int] NULL,
	[active_flag] [varchar](1) NULL,
	[created_by] [varchar](500) NULL,
	[created_dtm] [datetime] NULL,
	[version_no] [int] NULL,
	[expected_value_at_risk] [decimal](15, 2) NULL,
	[weighted_value_at_risk] [decimal](15, 2) NULL,
	[cost_impact_ranging_basis] [varchar](8000) NULL,
	[expected_value_at_risk_pre_contract] [decimal](15, 2) NULL,
	[dim_ent_promt_project_sk] [int] NULL,
	[dim_ent_promt_project_nk] [int] NULL,
	[project_no] [varchar](120) NULL,
	[project_pc_code] [varchar](120) NULL,
	[project_pc_code_description] [varchar](500) NULL,
	[project_bid_project_id] [int] NULL,
	[project_project_title] [varchar](500) NULL,
	[project_client_name] [varchar](500) NULL,
	[project_business_line] [varchar](120) NULL,
	[project_business_line_description] [varchar](500) NULL,
	[project_country] [varchar](500) NULL,
	[project_manager] [varchar](500) NULL,
	[project_prom_lead] [varchar](500) NULL,
	[project_category] [varchar](120) NULL,
	[project_category_description] [varchar](500) NULL,
	[project_total_contract_value] [decimal](15, 2) NULL,
	[project_estimated_cost] [decimal](15, 2) NULL,
	[project_currency_code] [varchar](120) NULL,
	[project_currency_code_description] [varchar](500) NULL,
	[project_contract_type] [varchar](120) NULL,
	[project_contract_type_description] [varchar](500) NULL,
	[project_total_duration] [decimal](15, 2) NULL,
	[project_document_revision_no] [varchar](120) NULL,
	[project_document_revision_date] [datetime] NULL,
	[project_revisied_by] [varchar](120) NULL,
	[project_approved_by] [varchar](120) NULL,
	[project_award_date] [datetime] NULL,
	[project_active_flag] [varchar](1) NULL,
	[project_project_type] [varchar](120) NULL,
	[project_project_type_description] [varchar](500) NULL,
	[project_duration_type] [varchar](120) NULL,
	[project_version_no] [int] NULL,
	[project_status] [varchar](20) NULL,
	[project_status_description] [varchar](500) NULL,
	[dl_touched_dtm] [datetime] NULL,
	[process_date] [datetime] NULL,
 CONSTRAINT [stage_promt_datalake_export_risk_id] PRIMARY KEY NONCLUSTERED 
	(
		[stage_promt_datalake_export_risk_id] ASC
	) NOT ENFORCED 
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

