CREATE TABLE [promt].[fact_promt_risk]
(
	[fact_promt_risk_id] [int] IDENTITY(1,1) NOT NULL,
	[dim_ent_risk_opportunity_category_sk] [int] NULL,
	[dim_ent_risk_opportunity_category_nk] [int] NULL,
	[dim_ent_probability_range_percentage_sk] [int] NULL,
	[dim_ent_probability_range_percentage_nk] [int] NULL,
	[dim_ent_environment_sk] [int] NULL,
	[dim_ent_environment_nk] [int] NULL,
	[dim_ent_health_safety_security_sk] [int] NULL,
	[dim_ent_health_safety_security_nk] [int] NULL,
	[dim_ent_quality_sk] [int] NULL,
	[dim_ent_quality_nk] [int] NULL,
	[dim_ent_reputation_sk] [int] NULL,
	[dim_ent_reputation_nk] [int] NULL,
	[dim_ent_social_culture_sk] [int] NULL,
	[dim_ent_social_culture_nk] [int] NULL,
	[dim_ent_cost_impact_tcv_percentage_sk] [int] NULL,
	[dim_ent_cost_impact_tcv_percentage_nk] [int] NULL,
	[dim_ent_schedule_sk] [int] NULL,
	[dim_ent_schedule_nk] [int] NULL,
	[dim_ent_risk_status_sk] [int] NULL,
	[dim_ent_risk_status_nk] [int] NULL,
	[dim_ent_risk_closing_justification_sk] [int] NULL,
	[dim_ent_risk_closing_justification_nk] [int] NULL,
	[dim_ent_strategy_pre_contract_sk] [int] NULL,
	[dim_ent_strategy_pre_contract_nk] [int] NULL,
	[dim_ent_strategy_execution_sk] [int] NULL,
	[dim_ent_strategy_execution_nk] [int] NULL,
	[dim_ent_action_status_sk] [int] NULL,
	[dim_ent_action_status_nk] [int] NULL,
	[dim_ent_mit_probability_range_percentage_sk] [int] NULL,
	[dim_ent_mit_probability_range_percentage_nk] [int] NULL,
	[dim_ent_mit_environment_sk] [int] NULL,
	[dim_ent_mit_environment_nk] [int] NULL,
	[dim_ent_mit_health_safety_security_sk] [int] NULL,
	[dim_ent_mit_health_safety_security_nk] [int] NULL,
	[dim_ent_mit_quality_sk] [int] NULL,
	[dim_ent_mit_quality_nk] [int] NULL,
	[dim_ent_mit_reputation_sk] [int] NULL,
	[dim_ent_mit_reputation_nk] [int] NULL,
	[dim_ent_mit_social_culture_sk] [int] NULL,
	[dim_ent_mit_social_culture_nk] [int] NULL,
	[dim_ent_mit_cost_impact_tcv_percentage_sk] [int] NULL,
	[dim_ent_mit_cost_impact_tcv_percentage_nk] [int] NULL,
	[dim_ent_mit_schedule_sk] [int] NULL,
	[dim_ent_mit_schedule_nk] [int] NULL,
	[dim_ent_distribution_type_sk] [int] NULL,
	[dim_ent_distribution_type_nk] [int] NULL,
	[dim_ent_shared_externaly_sk] [int] NULL,
	[dim_ent_shared_externaly_nk] [int] NULL,
	[dim_ent_risk_modeling_tech_sk] [int] NULL,
	[dim_ent_risk_modeling_tech_nk] [int] NULL,
	[dim_ent_mit_fully_transferred_sk] [int] NULL,
	[dim_ent_mit_fully_transferred_nk] [int] NULL,
	[dim_ent_mit_fully_avoided_sk] [int] NULL,
	[dim_ent_mit_fully_avoided_nk] [int] NULL,
	[dim_ent_promt_project_sk] [int] NULL,
	[dim_ent_promt_project_nk] [int] NULL,
	[dim_ent_overall_impact_sk] [int] NULL,
	[dim_ent_overall_impact_nk] [int] NULL,
	[dim_ent_mit_overall_impact_sk] [int] NULL,
	[dim_ent_mit_overall_impact_nk] [int] NULL,
	[risk_id] [int] NULL,
	[risk_no] [int] NULL,
	[risk_title] [varchar](1000) NULL,
	[description] [varchar](8000) NULL,
	[record_date] [datetime] NULL,
	[overall_impact] [varchar](10) NULL,
	[severity_score] [int] NULL,
	[hilp] [varchar](50) NULL,
	[risk_owner] [varchar](150) NULL,
	[actions] [varchar](8000) NULL,
	[cost_mitigation] [decimal](15, 2) NULL,
	[action_due_date] [datetime] NULL,
	[mit_overall_impact] [varchar](10) NULL,
	[mit_severity_score] [int] NULL,
	[mit_hilp] [varchar](50) NULL,
	[probability] [decimal](15, 2) NULL,
	[best_case] [decimal](15, 2) NULL,
	[most_likely] [decimal](15, 2) NULL,
	[worst_case] [decimal](15, 2) NULL,
	[discrete_value] [decimal](15, 2) NULL,
	[bottom_value] [decimal](15, 2) NULL,
	[top_value] [decimal](15, 2) NULL,
	[lower_probability] [decimal](15, 2) NULL,
	[min_value] [decimal](15, 2) NULL,
	[max_value] [decimal](15, 2) NULL,
	[risk_function1] [decimal](15, 2) NULL,
	[mit_probability] [decimal](15, 2) NULL,
	[mit_best_case] [decimal](15, 2) NULL,
	[mit_most_likely] [decimal](15, 2) NULL,
	[mit_worst_case] [decimal](15, 2) NULL,
	[mit_discrete_value] [decimal](15, 2) NULL,
	[mit_bottom_value] [decimal](15, 2) NULL,
	[mit_top_value] [decimal](15, 2) NULL,
	[mit_lower_probability] [decimal](15, 2) NULL,
	[mit_min_value] [decimal](15, 2) NULL,
	[mit_max_value] [decimal](15, 2) NULL,
	[risk_function_2] [decimal](15, 2) NULL,
	[drivers_causes] [varchar](8000) NULL,
	[risk_due_date] [datetime] NULL,
	[mit_cost] [decimal](15, 2) NULL,
	[t_project_id] [int] NULL,
	[active_flag] [varchar](1) NULL,
	[created_by] [varchar](120) NULL,
	[created_dtm] [datetime] NULL,
	[version_no] [int] NULL,
	[expected_value_at_risk] [decimal](15, 2) NULL,
	[weighted_value_at_risk] [decimal](15, 2) NULL,
	[cost_impact_ranging_basis] [varchar](8000) NULL,
	[expected_value_at_risk_pre_contract] [decimal](15, 2) NULL,
	[dl_touched_dtm] [datetime] NULL,
	[process_date] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

