CREATE TABLE [promt].[reprocess_promt_datalake_export_opportunity_snapshot]
(

[rssk] 															[int] IDENTITY(1,1) NOT NULL,
[created_date_time] 											[datetime] NULL,
[hash_code] 													[varchar](8000) NULL,	
[ssoi_id] 														[int] NULL,
[ss_id] 														[int] NULL,
[period_date] 													[date] NULL,
[opportunity_id]												[int],								
[opportunity_no]												[int],
[ro_category]													[varchar](500),
[ro_category_description]										[varchar](500),
[sub_category]													[varchar](500),
[dim_ent_risk_opportunity_category_sk] 							[int] NULL,
[dim_ent_risk_opportunity_category_nk] 							[int] NULL,
[opportunity_title]												[varchar](1000),
[drivers_causes]												[varchar](8000),
[description]													[varchar](8000),
[record_date]													[datetime],
[probability_range_percentage] 									[varchar](500),
[probability_range_percentage_description] 						[varchar](500),
[probability_range_percentage_display_order] 					[varchar](10) NULL,
[dim_ent_probability_range_percentage_sk] 						[int] NULL,
[dim_ent_probability_range_percentage_nk] 						[int] NULL,
[environment] 													[varchar](500),
[environment_description] 										[varchar](500),
[dim_ent_environment_sk] 										[int] NULL,
[dim_ent_environment_nk] 										[int] NULL,
[health_safety_security] 										[varchar](500),
[health_safety_security_description] 							[varchar](500),
[dim_ent_health_safety_security_sk] 							[int] NULL,
[dim_ent_health_safety_security_nk] 							[int] NULL,
[quality] 														[varchar](500),
[quality_description] 											[varchar](500),
[dim_ent_quality_sk] 											[int] NULL,
[dim_ent_quality_nk] 											[int] NULL,
[reputation] 													[varchar](500),
[reputation_description] 										[varchar](500),
[dim_ent_reputation_sk] 										[int] NULL,
[dim_ent_reputation_nk] 										[int] NULL,
[social_culture] 												[varchar](500),
[social_culture_description] 									[varchar](500),
[dim_ent_social_culture_sk] 									[int] NULL,
[dim_ent_social_culture_nk] 									[int] NULL,
[cost_impact_tcv_percentage] 									[varchar](500),
[cost_impact_tcv_percentage_description] 						[varchar](500),
[dim_ent_cost_impact_tcv_percentage_sk] 						[int] NULL,
[dim_ent_cost_impact_tcv_percentage_nk] 						[int] NULL,
[schedule] 														[varchar](500),
[schedule_description] 											[varchar](500),
[dim_ent_schedule_sk] 											[int] NULL,
[dim_ent_schedule_nk] 											[int] NULL,
[overall_impact] 												[varchar](10),
[overall_impact_description] 									[varchar](500) NULL,
[overall_impact_display_sort_order] 							[varchar](10) NULL,
[dim_ent_overall_impact_sk] 									[int] NULL,
[dim_ent_overall_impact_nk] 									[int] NULL,
[severity_score] 												[int],
[hilp] 															[varchar](500),
[opportunity_owner]												[varchar](500),	
[opportunity_due_date]											[date],
[opportunity_status]											[varchar](500),
[opportunity_status_description]								[varchar](500),
[dim_ent_opportunity_status_sk] 								[int] NULL,
[dim_ent_opportunity_status_nk] 								[int] NULL,
[opportunity_closing_justification]								[varchar](500),
[opportunity_closing_justification_description]					[varchar](500),
[dim_ent_opportunity_closing_justification_sk] 					[int] NULL,
[dim_ent_opportunity_closing_justification_nk] 					[int] NULL,
[actions]														[varchar](8000),
[opportunity_cost]												decimal(15,2),
[response_status]												[varchar](500),
[respose_status_description]									[varchar](500),
[dim_ent_response_status_sk] 									[int] NULL,
[dim_ent_response_status_nk] 									[int] NULL,
[action_due_date]												[date],
[probability]													decimal(15,2),
[best_case]                                                     decimal(15,2),
[worst_case]                                                    decimal(15,2),
[discrete_value]                                                decimal(15,2),
[bottom_value]                                                  decimal(15,2),
[top_value]                                                     decimal(15,2),
[lower_probability]                                             decimal(15,2),
[min_value]                                                     decimal(15,2),
[max_value]                                                     decimal(15,2),
[distribution_type]												[varchar](500),
[distribution_type_description]									[varchar](500),
[dim_ent_distribution_type_sk] 									[int] NULL,
[dim_ent_distribution_type_nk] 									[int] NULL,
[risk_function]													decimal(15,2),
[risk_modeling_tech]											[varchar](500),
[risk_modeling_tech_description]								[varchar](500),
[dim_ent_risk_modeling_tech_sk] 								[int] NULL,
[dim_ent_risk_modeling_tech_nk] 								[int] NULL,
[most_likely]													decimal(15,2),
[t_project_id]													[int],
[active_flag]													[varchar](1),
[created_by]													[varchar](500),
[created_dtm]													[datetime],
[version_no]													[int],
[cost_impact_ranging_basis]										[varchar](8000),
[dim_ent_promt_project_sk] 										[int] NULL,
[dim_ent_promt_project_nk] 										[int] NULL,
[project_no]													[varchar](120) NULL,
[project_pc_code]												[varchar](120) NULL,
[project_pc_code_description]									[varchar](500) NULL,
[project_bid_project_id]										[int] NULL,         
[project_project_title]											[varchar](500) NULL,
[project_client_name]											[varchar](500) NULL,
[project_business_line]											[varchar](120) NULL,
[project_business_line_description]								[varchar](500) NULL,
[project_country]												[varchar](500) NULL,
[project_manager]												[varchar](500) NULL,
[project_prom_lead]												[varchar](500) NULL,
[project_category]												[varchar](120) NULL,
[project_category_description]									[varchar](500) NULL,
[project_total_contract_value]									[decimal](15, 2) NULL,
[project_estimated_cost]										[decimal](15, 2) NULL,
[project_currency_code]											[varchar](120) NULL,
[project_currency_code_description]								[varchar](500) NULL,
[project_contract_type]											[varchar](120) NULL,
[project_contract_type_description]								[varchar](500) NULL,
[project_total_duration]										[decimal](15, 2) NULL,
[project_document_revision_no]									[varchar](120) NULL,
[project_document_revision_date]								[datetime] NULL,
[project_revisied_by]											[varchar](120) NULL,
[project_approved_by]											[varchar](120) NULL,
[project_award_date]											[datetime] NULL,
[project_active_flag]											[varchar](1) NULL,
[project_project_type]											[varchar](120) NULL,
[project_project_type_description]								[varchar](500) NULL,
[project_duration_type]											[varchar](120) NULL,
[project_version_no]											[int] NULL,
[project_status]												[varchar](20) NULL,
[project_status_description]									[varchar](500) NULL,
dl_touched_dtm													datetime NULL,
[process_date] 													[datetime],
[rk_failure_info] 												[varchar](5000) NULL

)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO

