CREATE TABLE [promt].[fact_promt_opportunity_snapshot]
(
[fact_promt_opportunity_id] [int] IDENTITY(1,1) NOT NULL,
[dim_ent_risk_opportunity_category_sk]  [int] NULL,
[dim_ent_risk_opportunity_category_nk]  [int] NULL,
[dim_ent_probability_range_percentage_sk]  [int] NULL,
[dim_ent_probability_range_percentage_nk] [int] NULL,
[dim_ent_environment_sk] [int] NULL,
[dim_ent_environment_nk] [int] NULL,
[dim_ent_health_safety_security_sk] [int] NULL,
[dim_ent_health_safety_security_nk] [int] NULL,
[dim_ent_quality_sk] [int] NULL,
[dim_ent_quality_nk] [int] NULL,
[dim_ent_reputation_sk] [int] NULL,
[dim_ent_reputation_nk] [int] NULL,
[dim_ent_social_culture_sk] [int] NULL,
[dim_ent_social_culture_nk] [int] NULL,
[dim_ent_cost_impact_tcv_percentage_sk] [int] NULL,
[dim_ent_cost_impact_tcv_percentage_nk] [int] NULL,
[dim_ent_schedule_sk] [int] NULL,
[dim_ent_schedule_nk] [int] NULL,
[dim_ent_opportunity_status_sk] [int] NULL,
[dim_ent_opportunity_status_nk] [int] NULL,
[dim_ent_opportunity_closing_justification_sk] [int] NULL,
[dim_ent_opportunity_closing_justification_nk] [int] NULL,
[dim_ent_response_status_sk] [int] NULL,
[dim_ent_response_status_nk] [int] NULL,
[dim_ent_distribution_type_sk] [int] NULL,
[dim_ent_distribution_type_nk] [int] NULL,
[dim_ent_risk_modeling_tech_sk] [int] NULL,
[dim_ent_risk_modeling_tech_nk] [int] NULL,
[dim_ent_promt_project_sk] [int] NULL,
[dim_ent_promt_project_nk] [int] NULL,
[dim_ent_overall_impact_sk] [int] NULL,
[dim_ent_overall_impact_nk] [int] NULL,
[ssoi_id] [int] NULL,
[ss_id] [int] NULL,
[period_date] [date] NULL,
[opportunity_id] [int] NULL,
[opportunity_no] [int] NULL,
[opportunity_title] [varchar](1000) NULL,
[drivers_causes] [varchar](8000) NULL,
[description] [varchar](8000) NULL,
[record_date] [datetime] NULL,
[overall_impact] [varchar](10) NULL,
[severity_score] [int] NULL,
[hilp] [varchar](50) NULL,
[opportunity_owner] [varchar](150) NULL,
[opportunity_due_date] [date] NULL,
[actions] [varchar](8000) NULL,
[opportunity_cost] [decimal](15, 2) NULL,
[response_status] [varchar](120) NULL,
[respose_status_description] [varchar](500) NULL,
[action_due_date] [date] NULL,
[probability] [decimal](15, 2) NULL,
[best_case] [decimal](15, 2) NULL,
[worst_case] [decimal](15, 2) NULL,
[discrete_value] [decimal](15, 2) NULL,
[bottom_value] [decimal](15, 2) NULL,
[top_value] [decimal](15, 2) NULL,
[lower_probability] [decimal](15, 2) NULL,
[min_value] [decimal](15, 2) NULL,
[max_value] [decimal](15, 2) NULL,
[risk_function] [decimal](15, 2) NULL,
[most_likely] [decimal](15, 2) NULL,
[t_project_id] [int] NULL,
[active_flag] [varchar](1) NULL,
[created_by] [varchar](120) NULL,
[created_dtm] [datetime] NULL,
[version_no] [int] NULL,
[cost_impact_ranging_basis] [varchar](8000) NULL,
[dl_touched_dtm] [datetime] NULL,
[process_date] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO
