--Update Stage table name from NCSA_Activity to NCSA_Activity_v in generic_load_header

update dbo.generic_load_header
set stage_table_name = 'gpd.NCSA_Activity_v'
where load_name = 'dim_entp_activity';

--Insert additional entries into generic_load_detail for the new 19 columns for DIM_ENTP_ACTIVITY

INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','actual_duration','int','NUMBER','OA','actual_duration',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'270','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','remaining_late_start','date','DATE','OA','remaining_late_start',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'280','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','remaining_late_finish','date','DATE','OA','remaining_late_finish',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'290','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','calendar','varchar(200)','TEXT','OA','calendar',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'300','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','budgeted_units','varchar(30)','TEXT','OA','budgeted_units',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'310','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','actual_units','varchar(30)','TEXT','OA','actual_units',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'320','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','remaining_units','varchar(30)','TEXT','OA','remaining_units',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'330','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','wbs','varchar(100)','TEXT','OA','wbs',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'340','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','wbs_name','varchar(200)','TEXT','OA','wbs_name',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'350','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','cost_account','varchar(100)','TEXT','OA','cost_account',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'360','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','role_is','varchar(100)','TEXT','OA','role_is',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'370','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','change_management','varchar(50)','TEXT','OA','change_management',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'380','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','funct','varchar(50)','TEXT','OA','funct',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'390','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','milestones','varchar(50)','TEXT','OA','milestones',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'400','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','office','varchar(50)','TEXT','OA','office',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'410','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','dim_entp_phase_nk','int','NUMBER','OA','dim_entp_phase_nk',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'420','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','region','varchar(50)','TEXT','OA','region',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'430','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','schedule_risk_assessment','varchar(50)','TEXT','OA','schedule_risk_assessment',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'440','Y',NULL)	;
INSERT INTO [dbo].[generic_load_detail]
           ([load_name]
           ,[stage_column_name]
           ,[stage_column_data_type]
           ,[stage_column_data_type_category]
           ,[stage_column_key_type]
           ,[target_column_name]
           ,[ref_table_name]
           ,[ref_gnk_name]
           ,[ref_target_column_name1]
           ,[ref_source_column_name1]
           ,[ref_target_column_name2]
           ,[ref_source_column_name2]
           ,[ref_target_column_name3]
           ,[ref_source_column_name3]
           ,[ref_target_column_name4]
           ,[ref_source_column_name4]
           ,[ref_target_column_name5]
           ,[ref_source_column_name5]
           ,[sl_no]
           ,[active_flag]
           ,[skip_rk_validation])
     VALUES 	('dim_entp_activity','supply_chain','varchar(50)','TEXT','OA','supply_chain',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'450','Y',NULL)	;
