CREATE VIEW [epr].[R2P_PO_Commitment_Details_v]
AS SELECT 

[AMOUNT_ORDERED] as [amount_ordered]
,[AREA] as [area]
,[CONTRACTID] as [contractid]
,[CONVERSION_RATE] as [conversion_rate]
,[COSTOBJECTID] as [costobjectid]
,[DISTRIBUTION_NUM] as [distribution_num]
,[ENTITYID] as [entityid]
,[EXPENDITURETYPE] as [expendituretype]
,[FEATURECODE] as [featurecode]
,[ITEM_DESCRIPTION] as [item_description]
,[ITEM_ID] as [item_id]
,[ITEM_NUMBER] as [item_number]
,[JOBNUMBERID] as [jobnumberid]
,[LATEST_STATUS] as [latest_status]
,[LEDGERAMOUNTINVOICED] as [ledgeramountinvoiced]
,[LEDGERAMOUNTOPEN] as [ledgeramountopen]
,[LEDGERCURRENCY] as [ledgercurrency]
,[LEDGERCURRENCYAMOUNT] as [ledgercurrencyamount]
,[LINE_AMOUNT_RECEIVED] as [line_amount_received]
,[MPP_PO] as [mpp_po]
,[MRRINVOICEAMOUNT] as [mrrinvoiceamount]
,[ONEMDRCOSTTYPE] as [onemdrcosttype]
,[OPENCOMMITMENTAMOUNT] as [opencommitmentamount]
,[POCLOSEDDATE] as [pocloseddate]
,[PODESCRIPTION] as [podescription]
,[PONUMBER] as [ponumber]
,[POPROJECT] as [poproject]
,[POREV] as [porev]
,[POREVCOUNT] as [porevcount]
,[POTITLE] as [potitle]
,[POVENDOR1] as [povendor1]
,[PO_LINE_NUM] as [po_line_num]
,[PO_MATCH_APPROVAL_LEVEL] as [po_match_approval_level]
,[PURCHASE_BASIS] as [purchase_basis]
,[QUANTITY] as [quantity]
,[RATE] as [rate]
,[REFERENCE] as [reference]
,[REQUISTIONNUMBER] as [requistionnumber]
,[STATUS] as [status]
,[SUBFUNCTIONID] as [subfunctionid]
,[TASKNAME] as [taskname]
,[TASKNUMBER] as [tasknumber]
,[TASKORGAREA] as [taskorgarea]
,[TASKORGLE] as [taskorgle]
,[TRANSACTIONAMOUNT] as [transactionamount]
,[TRANSACTIONAMOUNTUSD] as [transactionamountusd]
,[TRANSACTIONCURRENCY] as [transactioncurrency]
,[UNITOFMEASUREID] as [unitofmeasureid]
,[USD_RATE] as [usd_rate]
,[CURRDATE] as [currdate]
,[PO] as [po]
,[P_PROJECT] as [p_project]
,[P_RUN_DATE] as [p_run_date]
,[P_START_DATE] as [p_start_date]
,[source_name] as [source_name]
,[sub_source_name] as [sub_source_name]
,[created_date_time] as [Created Date Time]

FROM [epr].[R2P_PO_Commitment_Details]




