drop VIEW [epr].[BIR_Global_Expediting_Report_Direct_New_All_Projects_V]


CREATE VIEW [epr].[BIR_Global_Expediting_Report_Direct_New_All_Projects_V]
AS select
Project,
Discipline,
"Requisition No",
"PO No" as "Purchase Order No",
"PO Rev No" as "Purchase Order Revision No",
Issued as "Po Issue Date",
"PO Status" as "Po Status",
Description as "Package Description",
"Ident Short Description" as "Item Description",
"Ident Code" as "Ident Number",
Pos as "Po Line Item Number",
Sub as "Po Item Sub",
"Order Qty" as "Quantity Ordered",
"Qty Unit" as Uom,
"Expediting Level" as "Expediting Criticality Level",
"Inspection Level" as "Inspection Criticality Level",
"IS Sub" as "Item Shipment Sub",
"Item Ship Qty" as "Item Shipment Quantity",
"Item Ship Weight" as "ISH Weight",
"Pred On Site" as "Pred On Site Date",
"Arr On Site Fcst" as "Arvl On Site Forecasted Date",
"Arr On Site Act" as "Actual Rpt Date At Whs/Site",
"Req On Site" as "Ros Date",
"ROS Float" as Float,
"IRC Nr" as "Irc No",
"IRC Qty" as "Irc Qty",
"IRC Approved Date" as "Irc Approved Date",
"Release Note Nr" as "Release Note No",
"RN Qty" as "Release Note Qty",
"RN Approved Date" as "Release Approved Date",
"Balance IRC Qty" as "Balance Irc Qty",
"MRR Number" as "Mrr Number",
"MRR Created Date" as "Mrr Created Date",
"MRR Posted Date" as "Mrr Posted Date",
"MRR Quantity" as "Mrr Quantity",
"OSD Number" as "Osd Number",
"OSD Created Date" as "Osd Created Date",
"OSD Qty" as "Osd Qty",
"OSD Type" as "Osd Type",
"OSD Request Action" as "Osd Request Action",
"OSD Action Taken" as "Osd Action Taken",
"OSD Closed Date" as "Osd Closed Date",
"Balance RN Qty" as "Balance Rn Qty",
"Balance MRR Qty" as "Balance Mrr Qty",
"Supplier Name",
"Tag Number",
"Total ISH Weight",
"Weight Unit",
"Delivery Designation",
"Routing Method",
Incoterm,
"Forecasted Delivery Date",
Buyer,
Expeditor,
"Package Manager",
"Item Comments",
"Header Comment",
Color,
"MTO Discipline",
"Req Supp",
"Req LI",
"Req Sub LI",
"Approved Date",
"Supplier",
"Supplier City",
"Country of Origin",
"Supplier Country",
"IS Pos",
"Client Ident Code",
"Commodity Code",
"Size1",
"Size2",
"Size3",
"Size4",
"Received Qty",
"Unit Price",
"Extended Price",
"Currency",
"Charge/Account Code",
"Transit Days",
"Delivery Place",
"Prom Contract",
"Contractual Float",
"NOI Nr",
"NOI Date",
"NOI Qty",
"NOI Destination",
"NOI Plan",
"NOI Fcst",
"NOI Act",
"Act Insp Date",
"IRC Destination",
"IRC Plan",
"IRC Fcst",
"IRC Act",
"RN Date",
"RN Delivery Date",
"RN Ready Date",
"Hand Over Destination",
"Hand Over Plan",
"Hand Over Fcst",
"Hand Over Act",
"1ST Ship Destination",
"1ST Ship Plan",
"1ST Ship Fcst",
"1ST Ship Act",
"2ND Ship Destination",
"2ND Ship Plan",
"2ND Ship Fcst",
"2ND Ship Act",
"3RD Ship Destination",
"3RD Ship Plan",
"3RD Ship Fcst",
"3RD Ship Act",
"Traffic Arr Destination",
"Traffic Arr Plan",
"Traffic Arr Fcst",
"Traffic Arr Act",
"Arr On Site Destination",
"Arr On Site Plan",
"Shipment Number",
"MOC",
"Transport No",
"Departure Point",
"Arrival Point",
"Shipment ETD",
"Shipment ATD",
"Shipment ETA",
"Shipment ATA",
"No of Cont",
"Pre-Ship MOC",
"Pre-Ship Transport No",
"Pre-Ship Dept Point",
"Pre-Ship Arr Point",
"Pre-Ship ETD",
"Pre-Ship ATD",
"Pre-Ship ETA",
"Pre-Ship ATA",
"Pre-Ship Freight Ton",
"Pre-Ship No of Pack",
"Post-Ship MOC",
"Post-Ship Transport No",
"Post-Ship Dept Point",
"Post-Ship Arr Point",
"Post-Ship ETD",
"Post-Ship ATD",
"Post-Ship ETA",
"Post-Ship ATA",
"Post-Ship Freight Ton",
"Post-Ship No of Pack",
"MRR Rev Nr",
"Earliest Matl Recv Date",
"IS Master Tag",
"Manufacturer",
CreatedDateTime,
week_end_date
from [epr].[BIR_Global_Expediting_Report_Direct_New_All_Projects];
GO



alter table epr.BIR_Global_Expediting_Report_Direct_New_All_Projects
add "MTO Discipline" varchar(500)


alter table epr.BIR_Global_Expediting_Report_Direct_New_All_Projects
add week_end_date varchar (200)

CREATE TABLE [epr].[BIR_Global_Expediting_Report_Direct_New_All_Projects]
(
[Project]   [varchar](100)  NULL,
[Discipline]   [varchar](100)  NULL,
[Requisition No]   [varchar](100)  NULL,
[Req Supp]   [varchar](100)  NULL,
[Req LI]   [varchar](100)  NULL,
[Req Sub LI]   [varchar](100)  NULL,
[PO No]   [varchar](500)  NULL,
[PO Rev No]   [varchar](100)  NULL,
[Description]   [varchar](4000)  NULL,
[Issued]   [varchar](500)  NULL,
[Approved Date]   [varchar](500)  NULL,
[PO Status]   [varchar](500)  NULL,
[Supplier]   [varchar](500)  NULL,
[Supplier Name]   [varchar](2000)  NULL,
[Supplier City]   [varchar](100)  NULL,
[Country of Origin]   [varchar](100)  NULL,
[Supplier Country]   [varchar](100)  NULL,
[Expediting Level]   [varchar](100)  NULL,
[Inspection Level]   [varchar](100)  NULL,
[Pos]   [varchar](100)  NULL,
[Sub]   [varchar](100)  NULL,
[IS Pos]   [varchar](100)  NULL,
[IS Sub]   [varchar](100)  NULL,
[Ident Short Description]   [varchar](6000)  NULL,
[Ident Code]   [varchar](500)  NULL,
[Client Ident Code]   [varchar](500)  NULL,
[Tag Number]   [varchar](500)  NULL,
[Commodity Code]   [varchar](500)  NULL,
[Size1]   [varchar](200)  NULL,
[Size2]   [varchar](200)  NULL,
[Size3]   [varchar](200)  NULL,
[Size4]   [varchar](200)  NULL,
[Order Qty]   [varchar](200)  NULL,
[Item Ship Qty]   [varchar](200)  NULL,
[Received Qty]   [varchar](200)  NULL,
[Balance MRR Qty]   [varchar](200)  NULL,
[Qty Unit]   [varchar](200)  NULL,
[Item Ship Weight]   [varchar](200)  NULL,
[Total ISH Weight]   [varchar](200)  NULL,
[Weight Unit]   [varchar](200)  NULL,
[Unit Price]   [varchar](200)  NULL,
[Extended Price]   [varchar](200)  NULL,
[Currency]   [varchar](200)  NULL,
[Charge/Account Code]   [varchar](500)  NULL,
[Delivery Designation]   [varchar](200)  NULL,
[Routing Method]   [varchar](200)  NULL,
[Transit Days]   [varchar](200)  NULL,
[Incoterm]   [varchar](200)  NULL,
[Delivery Place]   [varchar](200)  NULL,
[Prom Contract]   [varchar](200)  NULL,
[Forecasted Delivery Date]   [varchar](200)  NULL,
[Contractual Float]   [varchar](200)  NULL,
[Pred On Site]   [varchar](200)  NULL,
[Req On Site]   [varchar](200)  NULL,
[ROS Float]   [varchar](200)  NULL,
[NOI Nr]   [varchar](200)  NULL,
[NOI Date]   [varchar](200)  NULL,
[NOI Qty]   [varchar](200)  NULL,
[NOI Destination]   [varchar](200)  NULL,
[NOI Plan]   [varchar](200)  NULL,
[NOI Fcst]   [varchar](200)  NULL,
[NOI Act]   [varchar](200)  NULL,
[IRC Nr]   [varchar](200)  NULL,
[IRC Approved Date]   [varchar](200)  NULL,
[IRC Qty]   [varchar](200)  NULL,
[Balance IRC Qty]   [varchar](200)  NULL,
[Act Insp Date]   [varchar](200)  NULL,
[IRC Destination]   [varchar](200)  NULL,
[IRC Plan]   [varchar](200)  NULL,
[IRC Fcst]   [varchar](200)  NULL,
[IRC Act]   [varchar](200)  NULL,
[Release Note Nr]   [varchar](2000)  NULL,
[RN Date]   [varchar](200)  NULL,
[RN Qty]   [varchar](200)  NULL,
[Balance RN Qty]   [varchar](200)  NULL,
[RN Approved Date]   [varchar](200)  NULL,
[RN Delivery Date]   [varchar](200)  NULL,
[RN Ready Date]   [varchar](200)  NULL,
[Hand Over Destination]   [varchar](200)  NULL,
[Hand Over Plan]   [varchar](200)  NULL,
[Hand Over Fcst]   [varchar](200)  NULL,
[Hand Over Act]   [varchar](200)  NULL,
[1ST Ship Destination]   [varchar](200)  NULL,
[1ST Ship Plan]   [varchar](200)  NULL,
[1ST Ship Fcst]   [varchar](200)  NULL,
[1ST Ship Act]   [varchar](200)  NULL,
[2ND Ship Destination]   [varchar](200)  NULL,
[2ND Ship Plan]   [varchar](200)  NULL,
[2ND Ship Fcst]   [varchar](200)  NULL,
[2ND Ship Act]   [varchar](200)  NULL,
[3RD Ship Destination]   [varchar](200)  NULL,
[3RD Ship Plan]   [varchar](200)  NULL,
[3RD Ship Fcst]   [varchar](200)  NULL,
[3RD Ship Act]   [varchar](200)  NULL,
[Traffic Arr Destination]   [varchar](200)  NULL,
[Traffic Arr Plan]   [varchar](200)  NULL,
[Traffic Arr Fcst]   [varchar](200)  NULL,
[Traffic Arr Act]   [varchar](200)  NULL,
[Arr On Site Destination]   [varchar](200)  NULL,
[Arr On Site Plan]   [varchar](200)  NULL,
[Arr On Site Fcst]   [varchar](200)  NULL,
[Arr On Site Act]   [varchar](200)  NULL,
[Shipment Number]   [varchar](200)  NULL,
[MOC]   [varchar](200)  NULL,
[Transport No]   [varchar](200)  NULL,
[Departure Point]   [varchar](200)  NULL,
[Arrival Point]   [varchar](200)  NULL,
[Shipment ETD]   [varchar](200)  NULL,
[Shipment ATD]   [varchar](200)  NULL,
[Shipment ETA]   [varchar](200)  NULL,
[Shipment ATA]   [varchar](200)  NULL,
[No of Cont]   [varchar](200)  NULL,
[Pre-Ship MOC]   [varchar](200)  NULL,
[Pre-Ship Transport No]   [varchar](200)  NULL,
[Pre-Ship Dept Point]   [varchar](200)  NULL,
[Pre-Ship Arr Point]   [varchar](200)  NULL,
[Pre-Ship ETD]   [varchar](200)  NULL,
[Pre-Ship ATD]   [varchar](200)  NULL,
[Pre-Ship ETA]   [varchar](200)  NULL,
[Pre-Ship ATA]   [varchar](200)  NULL,
[Pre-Ship Freight Ton]   [varchar](200)  NULL,
[Pre-Ship No of Pack]   [varchar](200)  NULL,
[Post-Ship MOC]   [varchar](200)  NULL,
[Post-Ship Transport No]   [varchar](200)  NULL,
[Post-Ship Dept Point]   [varchar](200)  NULL,
[Post-Ship Arr Point]   [varchar](200)  NULL,
[Post-Ship ETD]   [varchar](200)  NULL,
[Post-Ship ATD]   [varchar](200)  NULL,
[Post-Ship ETA]   [varchar](200)  NULL,
[Post-Ship ATA]   [varchar](200)  NULL,
[Post-Ship Freight Ton]   [varchar](200)  NULL,
[Post-Ship No of Pack]   [varchar](200)  NULL,
[MRR Number]   [varchar](200)  NULL,
[MRR Rev Nr]   [varchar](200)  NULL,
[MRR Created Date]   [varchar](200)  NULL,
[Earliest Matl Recv Date]   [varchar](200)  NULL,
[MRR Posted Date]   [varchar](200)  NULL,
[MRR Quantity]   [varchar](200)  NULL,
[OSD Number]   [varchar](200)  NULL,
[OSD Created Date]   [varchar](200)  NULL,
[OSD Qty]   [varchar](200)  NULL,
[OSD Type]   [varchar](200)  NULL,
[OSD Request Action]   [varchar](4000)  NULL,
[OSD Action Taken]   [varchar](8000)  NULL,
[OSD Closed Date]   [varchar](8000)  NULL,
[Buyer]   [varchar](4000)  NULL,
[Expeditor]   [varchar](4000)  NULL,
[Package Manager]   [varchar](200)  NULL,
[Item Comments]   [varchar](8000)  NULL,
[Header Comment]   [varchar](8000)  NULL,
[Color]   [varchar](8000)  NULL,
[IS Master Tag]   [varchar](8000)  NULL,
[Manufacturer]   [varchar](2000)  NULL,
[CreatedDateTime]   [datetime] NULL

)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


insert into [dbo].[plp_pipeline] (pipeline_code,subject_area_code,description,comment,active,touched_by,touched_dtm,sec_sa_id) values ('pl_BIR_Global_Expediting_Report_Direct_New_All_Projects','NCSA','SMAT Data Extract','NULL','1','sundararaju.batta@mcdermott.com','2025-10-09 13:42:58.820','9')
GO

insert into [dbo].[plp_pipeline_parameter] (pipeline_code,pipeline_sub_code,parameter_code,display_order,source_column_name,source_operator,comment,active,touched_by,touched_dtm) values ('pl_BIR_Global_Expediting_Report_Direct_New_All_Projects','NetworkFolder','table_name','1','table_name','IN','table_name with schema e.g. gpd.scm_procurement','1','sundararaju.batta@mcdermott.com','2025-10-09 13:42:58.820')
GO

insert into [dbo].[plp_pipeline_parameter] (pipeline_code,pipeline_sub_code,parameter_code,display_order,source_column_name,source_operator,comment,active,touched_by,touched_dtm) values ('pl_BIR_Global_Expediting_Report_Direct_New_All_Projects','NetworkFolder','logicapp_url','2','logicapp_url','IN','NULL','1','sundararaju.batta@mcdermott.com','2025-10-09 13:42:58.820')
GO


insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('logicapp_url','https://prod-56.eastus.logic.azure.com:443/workflows/3cff41a53ba14a82a9b7cc8d6d2bfe56/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=c7BCbv69x4tk7w5oqGQNOPlpIXvqBQi_Zwm8wkww0WQ','1','sundararaju.batta@mcdermott.com','2025-10-09 13:42:58.820','pl_BIR_Global_Expediting_Report_Direct_New_All_Projects','NetworkFolder')
GO

insert into [dbo].[plp_parameter_value] (parameter_code,parameter_value,active,touched_by,touched_dtm,pipeline_code,pipeline_sub_code) values ('table_name','BIR_Global_Expediting_Report_Direct_New_All_Projects','1','sundararaju.batta@mcdermott.com','2025-10-09 13:42:58.820','pl_BIR_Global_Expediting_Report_Direct_New_All_Projects','NetworkFolder')
GO






