drop table epr.iDocs_Vendor_Data_Ruya11_D7507

update plp_parameter_value
set parameter_value='A1:EP500000' where parameter_code='range' and pipeline_code='pl_iDocs_Vendor_Data_Ruya11_D7507'

update plp_parameter_value
set parameter_value='PS04 - SMDR.xlsx' where parameter_code='file_name' and pipeline_code='pl_iDocs_Vendor_Data_Ruya11_D7507'

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [epr].[iDocs_Vendor_Data_Ruya11_D7507]
(
	[DOC_ID] [varchar](5000) NULL,
	[DELIVERABLE] [varchar](2000) NULL,
	[OFFICE LOCATION] [varchar](2000) NULL,
	[POREQNO] [varchar](2000) NULL,
	[PO DESCRIPTION] [varchar](2000) NULL,
	[SELLER] [varchar](2000) NULL,
	[ENGR/QA FOCAL] [varchar](2000) NULL,
	[DOCNUMBER] [varchar](2000) NULL,
	[COMPANY DOCUMENT NUMBER] [varchar](2000) NULL,
	[REVISION] [varchar](2000) NULL,
	[TITLE] [varchar](8000) NULL,
	[DOCSTATUS] [varchar](2000) NULL,
	[LAST RTV STATUS] [varchar](2000) NULL,
	[DISTRIBUTION PURPOSE CLIENT] [varchar](2000) NULL,
	[DISTRIBUTION PURPOSE SUPPLIER] [varchar](2000) NULL,
	[DISTRIBUTION PURPOSE EMPLOYEE] [varchar](2000) NULL,
	[Package Manager] [varchar](2000) NULL,
	[VERSION] [varchar](2000) NULL,
	[VENDOR DISCIPLINE] [varchar](2000) NULL,
	[CLIENT DOC. TYPE] [varchar](2000) NULL,
	[CLIENT DISCIPLINE] [varchar](2000) NULL,
	[SYSTEM CODE] [varchar](2000) NULL,
	[SUB-SYSTEM] [varchar](2000) NULL,
	[COUNTRY] [varchar](2000) NULL,
	[SITE] [varchar](2000) NULL,
	[SECTOR] [varchar](2000) NULL,
	[ORIGINATOR] [varchar](2000) NULL,
	[SEQUENTIAL NUMBER] [varchar](2000) NULL,
	[PROJECT CODE] [varchar](2000) NULL,
	[CONTRACTOR] [varchar](2000) NULL,
	[DOCUMENT GROUP] [varchar](2000) NULL,
	[SDR CODE] [varchar](5000) NULL,
	[PRIORITY LEVEL] [varchar](1000) NULL,
	[PRIORITY OVERRIDE] [varchar](1000) NULL,
	[% COMPLETION] [varchar](1000) NULL,
	[TOTAL PROGRESS] [varchar](1000) NULL,
	[DOC WEIGHT] [varchar](1000) NULL,
	[DATE RECEIVED RECEIPT] [varchar](1000) NULL,
	[IFR Internal Review Plan] [varchar](1000) NULL,
	[IFR Internal Review Forecast] [varchar](1000) NULL,
	[IFR Internal Review Actual] [varchar](1000) NULL,
	[IFR - Client Plan] [varchar](1000) NULL,
	[IFR - Client Forecast] [varchar](1000) NULL,
	[IFR - Client Actual] [varchar](1000) NULL,
	[IFR - RCA Plan] [varchar](1000) NULL,
	[IFR - RCA Forecast] [varchar](1000) NULL,
	[IFR - RCA Actual] [varchar](1000) NULL,
	[IFR - RTV Plan] [varchar](1000) NULL,
	[IFR - RTV Forecast] [varchar](1000) NULL,
	[IFR - RTV Actual] [varchar](1000) NULL,
	[IFA Internal Review Plan] [varchar](1000) NULL,
	[IFA Internal Review Forecast] [varchar](1000) NULL,
	[IFA Internal Review Actual] [varchar](1000) NULL,
	[IFA - Client Plan] [varchar](1000) NULL,
	[IFA - Client Forecast] [varchar](1000) NULL,
	[IFA - Client Actual] [varchar](1000) NULL,
	[IFA - RCA Plan] [varchar](1000) NULL,
	[IFA - RCA Forecast] [varchar](1000) NULL,
	[IFA - RCA Actual] [varchar](1000) NULL,
	[IFA - RTV Plan] [varchar](1000) NULL,
	[IFA - RTV Forecast] [varchar](1000) NULL,
	[IFA - RTV Actual] [varchar](1000) NULL,
	[AFC Internal Review Plan] [varchar](1000) NULL,
	[AFC Internal Review Forecast] [varchar](1000) NULL,
	[AFC Internal Review Actual] [varchar](1000) NULL,
	[AFC - Client Plan] [varchar](1000) NULL,
	[AFC - Client Forecast] [varchar](1000) NULL,
	[AFC - Client Actual] [varchar](1000) NULL,
	[AFC - RCA Plan] [varchar](1000) NULL,
	[AFC - RCA Forecast] [varchar](1000) NULL,
	[AFC - RCA Actual] [varchar](1000) NULL,
	[AFC - RTV Plan] [varchar](1000) NULL,
	[AFC - RTV Forecast] [varchar](1000) NULL,
	[AFC - RTV Actual] [varchar](1000) NULL,
	[AB Internal Review Plan] [varchar](1000) NULL,
	[AB Internal Review Forecast] [varchar](1000) NULL,
	[AB Internal Review Actual] [varchar](1000) NULL,
	[AB - Client Plan] [varchar](1000) NULL,
	[AB - Client Forecast] [varchar](1000) NULL,
	[AB - Client Actual] [varchar](1000) NULL,
	[AB - RCA Plan] [varchar](1000) NULL,
	[AB - RCA Forecast] [varchar](1000) NULL,
	[AB - RCA Actual] [varchar](1000) NULL,
	[AB - RTV Plan] [varchar](1000) NULL,
	[AB - RTV Forecast] [varchar](1000) NULL,
	[AB - RTV Actual] [varchar](1000) NULL,
	[IFI Internal Review Plan] [varchar](1000) NULL,
	[IFI Internal Review Forecast] [varchar](1000) NULL,
	[IFI Internal Review Actual] [varchar](1000) NULL,
	[IFI - Client Plan] [varchar](1000) NULL,
	[IFI - Client Forecast] [varchar](1000) NULL,
	[IFI - Client Actual] [varchar](1000) NULL,
	[IFI - RCA Plan] [varchar](1000) NULL,
	[IFI - RCA Forecast] [varchar](1000) NULL,
	[IFI - RCA Actual] [varchar](1000) NULL,
	[IFI - RTV Plan] [varchar](1000) NULL,
	[IFI - RTV Forecast] [varchar](1000) NULL,
	[IFI - RTV Actual] [varchar](1000) NULL,
	[TRANSMITTAL NUMBER (E)] [varchar](2000) NULL,
	[TRANSMITTAL DATE (E)] [varchar](2000) NULL,
	[INTERNAL EXP DATE] [varchar](2000) NULL,
	[DAYS OVERDUE (EMPLOYER)] [varchar](2000) NULL,
	[CLIENT TRANSMITTAL NUMBER] [varchar](2000) NULL,
	[CLIENT TRANSMITTAL DATE] [varchar](2000) NULL,
	[CLIENT EXPECTED RETURN DATE] [varchar](2000) NULL,
	[DAYS OVERDUE (CLIENT)] [varchar](2000) NULL,
	[CLIENT TRANSNO (INCOMING)] [varchar](2000) NULL,
	[CLIENT TRANSDATE (INCOMING)] [varchar](2000) NULL,
	[CLIENT CODE] [varchar](2000) NULL,
	[TRANSMITTAL NUMBER (S)/(X)] [varchar](2000) NULL,
	[TRANSMITTAL Date (S)/(X)] [varchar](2000) NULL,
	[RETURN DATE TO SUPPLIER] [varchar](2000) NULL,
	[DAYS OVERDUE (S)] [varchar](2000) NULL,
	[SUPPLIER DOCNUMBER] [varchar](2000) NULL,
	[SUPPLIER REVISION] [varchar](2000) NULL,
	[EXPEDITOR COMMENTS] [varchar](2000) NULL,
	[REQORIGINATOR] [varchar](2000) NULL,
	[EXPEDITOR] [varchar](2000) NULL,
	[DELIVERABLE TYPE] [varchar](2000) NULL,
	[DOCUMENT CLASSIFICATION] [varchar](2000) NULL,
	[INITIAL PLAN SUBMITTAL DATE] [varchar](2000) NULL,
	[INITIAL FORECAST SUBM DATE] [varchar](2000) NULL,
	[OVERDUE DAYS] [varchar](2000) NULL,
	[Native file req. Hand-over] [varchar](5000) NULL,
	[3RD PARTY COMPANY] [varchar](5000) NULL,
	[3RD PARTY TRANSMITTAL NO] [varchar](5000) NULL,
	[3RD PARTY TRANSMITTAL DATE] [varchar](5000) NULL,
	[TRANSMITTAL NUMBER (P)] [varchar](5000) NULL,
	[TRANSMITTAL DATE (P)] [varchar](5000) NULL,
	[RETURN DATE FROM PARTNER] [varchar](2000) NULL,
	[DAYS OVERDUE (P)] [varchar](2000) NULL,
	[FOLDER NUMBER] [varchar](8000) NULL,
	[AS BUILT REQUIRED] [varchar](2000) NULL,
	[LAST CLIENT CODE RECEIVED] [varchar](2000) NULL,
	[Review Case] [varchar](2000) NULL,
	[Planned Start] [varchar](2000) NULL,
    [Planned Finish] [varchar](2000) NULL,
    [SD_Facility No.] [varchar](2000) NULL,
 [Campaign Name] [varchar](2000) NULL,
  [Doc to be issued to] [varchar](2000) NULL,
 [Assignment Number Code-Planning] [varchar](2000) NULL,
 [MOPEX-Planning] [varchar](2000) NULL,
 [Discipline-Planning] [varchar](2000) NULL,
  [Priority Progress-Planning] [varchar](2000) NULL,
 [Manhours Progress-Planning] [varchar](2000) NULL,
 [Interface] [varchar](2000) NULL,
 [project_number] [varchar](2000) NULL,
 [file_name] [varchar](2000) NULL,
 [CreatedDateTime] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


