drop table [epr].[MDR_Data_Ruya11_D7507]

CREATE TABLE [epr].[MDR_Data_Ruya11_D7507]
(
	[File Name] [varchar](500) NULL,
	[SFN Description] [varchar](500) NULL,
	[PCM Input] [varchar](500) NULL,
	[3rd Party ID] [varchar](500) NULL,
	[Doc. Type] [varchar](500) NULL,
	[Discipline] [varchar](500) NULL,
	[CRS No.] [varchar](500) NULL,
	[Yard Flag ID] [varchar](500) NULL,
	[Profile Type] [varchar](500) NULL,
	[Name] [varchar](500) NULL,
	[Revision] [varchar](500) NULL,
	[Revision Date] [varchar](500) NULL,
	[State] [varchar](500) NULL,
	[Deliverable Type] [varchar](500) NULL,
	[Project Doc Type] [varchar](500) NULL,
	[Project Doc Name] [varchar](500) NULL,
	[Status] [varchar](500) NULL,
	[Client Discipline] [varchar](500) NULL,
	[Client Document Type] [varchar](500) NULL,
	[Title] [varchar](6000) NULL,
	[Facility] [varchar](500) NULL,
	[Client Completion Percentage] [varchar](500) NULL,
	[Client Earned Value] [varchar](500) NULL,
	[Completion Percentage] [varchar](500) NULL,
	[Earned Value] [varchar](500) NULL,
	[Client Return Code] [varchar](500) NULL,
	[Client Return Date] [varchar](500) NULL,
	[Client Expected Return] [varchar](500) NULL,
	[Comments] [varchar](6000) NULL,
	[Location] [varchar](500) NULL,
	[Voided Reason] [varchar](500) NULL,
	[Thirty Percent Design Review] [varchar](500) NULL,
	[Sixty Percent Design Review] [varchar](500) NULL,
	[Ninety Percent Design Review] [varchar](500) NULL,
	[Original Weight] [varchar](500) NULL,
	[Planned Weight] [varchar](500) NULL,
	[Forecast Weight] [varchar](500) NULL,
	[Weighting 1] [varchar](500) NULL,
	[Start Activity Id] [varchar](500) NULL,
	[IDC Activity Id] [varchar](500) NULL,
	[IDC Completed Activity ID] [varchar](500) NULL,
	[IFR Activity ID] [varchar](500) NULL,
	[IFR RCA Activity ID] [varchar](500) NULL,
	[IFA Activity ID] [varchar](500) NULL,
	[IFA RCA Activity ID] [varchar](500) NULL,
	[IFA/IFR Activity Id] [varchar](500) NULL,
	[CA Activity Id] [varchar](500) NULL,
	[IFH Activity Id] [varchar](500) NULL,
	[AFD Activity Id] [varchar](500) NULL,
	[IFB Activity Id] [varchar](500) NULL,
	[AFC(H) Activity Id] [varchar](500) NULL,
	[AFC Activity Id] [varchar](500) NULL,
	[AFC RCA Activity ID] [varchar](500) NULL,
	[AFF Activity Id] [varchar](500) NULL,
	[AFH Activity Id] [varchar](500) NULL,
	[IFI Activity Id] [varchar](500) NULL,
	[IFP Activity Id] [varchar](500) NULL,
	[AFU Activity Id] [varchar](500) NULL,
	[As-Built Activity Id] [varchar](500) NULL,
	[Start Original] [varchar](500) NULL,
	[Start Plan] [varchar](500) NULL,
	[Start Forecast] [varchar](500) NULL,
	[Start Actual] [varchar](500) NULL,
	[IDC Original] [varchar](500) NULL,
	[IDC Plan] [varchar](500) NULL,
	[IDC Forecast] [varchar](500) NULL,
	[IDC Actual] [varchar](500) NULL,
	[IDC Complete Original] [varchar](500) NULL,
	[IDC Complete Plan] [varchar](500) NULL,
	[IDC Complete Forecast] [varchar](500) NULL,
	[IDC Complete Actual] [varchar](500) NULL,
	[IFR Original] [varchar](500) NULL,
	[IFR Plan] [varchar](500) NULL,
	[IFR Forecast] [varchar](500) NULL,
	[IFR Actual] [varchar](500) NULL,
	[RCA - IFR Original] [varchar](500) NULL,
	[RCA - IFR Plan] [varchar](500) NULL,
	[RCA - IFR Forecast] [varchar](500) NULL,
	[RCA - IFR Actual] [varchar](500) NULL,
	[IFA Original] [varchar](500) NULL,
	[IFA Plan] [varchar](500) NULL,
	[IFA Forecast] [varchar](500) NULL,
	[IFA Actual] [varchar](500) NULL,
	[RCA - IFA Original] [varchar](500) NULL,
	[RCA - IFA Plan] [varchar](500) NULL,
	[RCA - IFA Forecast] [varchar](500) NULL,
	[RCA - IFA Actual] [varchar](500) NULL,
	[AFD Original] [varchar](500) NULL,
	[AFD Plan] [varchar](500) NULL,
	[AFD Forecast] [varchar](500) NULL,
	[AFD Actual] [varchar](500) NULL,
	[IFB Original] [varchar](500) NULL,
	[IFB Plan] [varchar](500) NULL,
	[IFB Forecast] [varchar](500) NULL,
	[IFB Actual] [varchar](500) NULL,
	[AFC(H) Original] [varchar](500) NULL,
	[AFC(H) Plan] [varchar](500) NULL,
	[AFC(H) Forecast] [varchar](500) NULL,
	[AFC(H) Actual] [varchar](500) NULL,
	[AFC Original] [varchar](500) NULL,
	[AFC Plan] [varchar](500) NULL,
	[AFC Forecast] [varchar](500) NULL,
	[AFC Actual] [varchar](500) NULL,
	[RCA1 Code-2 - AFC Original] [varchar](500) NULL,
	[RCA1 Code-2 - AFC Plan] [varchar](500) NULL,
	[RCA1 Code-2 - AFC Forecast] [varchar](500) NULL,
	[RCA1 Code-2 - AFC Actual] [varchar](500) NULL,
	[RCA2 - AFC (Code 1) Original] [varchar](500) NULL,
	[RCA2 - AFC (Code 1) Plan] [varchar](500) NULL,
	[RCA2 - AFC (Code 1) Forecast] [varchar](500) NULL,
	[RCA2 - AFC (Code 1) Actual] [varchar](500) NULL,
	[IFI Original] [varchar](500) NULL,
	[IFI Plan] [varchar](500) NULL,
	[IFI Forecast] [varchar](500) NULL,
	[IFI Actual] [varchar](500) NULL,
	[RCA1 Code-2 - IFI Original] [varchar](500) NULL,
	[RCA1 Code-2 - IFI Plan] [varchar](500) NULL,
	[RCA1 Code-2 - IFI Forecast] [varchar](500) NULL,
	[RCA1 Code-2 - IFI Actual] [varchar](500) NULL,
	[RCA2 Code-1 - IFI Original] [varchar](500) NULL,
	[RCA2 Code-1 - IFI Plan] [varchar](500) NULL,
	[RCA2 Code-1 - IFI Forecast] [varchar](500) NULL,
	[RCA2 Code-1 - IFI Actual] [varchar](500) NULL,
	[IFP Original] [varchar](500) NULL,
	[IFP Plan] [varchar](500) NULL,
	[IFP Forecast] [varchar](500) NULL,
	[IFP Actual] [varchar](500) NULL,
	[As Built Original] [varchar](500) NULL,
	[As Built Plan] [varchar](500) NULL,
	[As Built Forecast] [varchar](500) NULL,
	[As Built Actual] [varchar](500) NULL,
	[Company Transmittal Number] [varchar](4000) NULL,
	[Company Return Date] [varchar](500) NULL,
	[Review Return code] [varchar](500) NULL,
	[Transmittal Number] [varchar](1000) NULL,
	[Transmittal Date] [varchar](500) NULL,
	[Interface Document] [varchar](500) NULL,
	[Originator] [varchar](500) NULL,
	[Contract Code] [varchar](500) NULL,
	[Contractor Originator Code] [varchar](500) NULL,
	[Country] [varchar](500) NULL,
	[Client Document Classification] [varchar](500) NULL,
	[Equipment Class] [varchar](500) NULL,
	[Equipment SubClass] [varchar](500) NULL,
	[Field Operation Deliverable] [varchar](500) NULL,
	[MDR Update Information] [varchar](500) NULL,
	[Project Code] [varchar](500) NULL,
	[Reason for Change-Engineering] [varchar](500) NULL,
	[Recipient] [varchar](500) NULL,
	[Sector Code] [varchar](500) NULL,
	[Site Code] [varchar](500) NULL,
	[Superseded by] [varchar](500) NULL,
	[System Code] [varchar](500) NULL,
	[Tag/Equipment No.] [varchar](500) NULL,
	[Unique ID] [varchar](500) NULL,
	[Sub-System] [varchar](500) NULL,
	[Greenfield / Brownfield] [varchar](500) NULL,
	[Work Unit] [varchar](500) NULL,
	[Work Pack] [varchar](500) NULL,
	[Put in iDocs] [varchar](500) NULL,
	[Internal Transmittal No.] [varchar](500) NULL,
	[Internal Transmittal Date] [varchar](500) NULL,
	[Distribution Q Status] [varchar](500) NULL,
	[DM Queue Date] [varchar](500) NULL,
	[DM Queue Release Date] [varchar](500) NULL,
	[Days Variance] [varchar](500) NULL,
	[Published Revision] [varchar](500) NULL,
	[Document Status] [varchar](4000) NULL,
	[HHI Transmittal No.] [varchar](500) NULL,
	[HHI Transmittal Date] [varchar](500) NULL,
	[Expediting Status] [varchar](4000) NULL,
	[UserType] [varchar](500) NULL,
	[MOPEX Location] [varchar](500) NULL,
	[As Built Required] [varchar](500) NULL,
	[AWP Type] [varchar](500) NULL,
	[AWP Applicable] [varchar](500) NULL,
	[AWP Assigned Platform] [varchar](500) NULL,
	[AWP Deck] [varchar](500) NULL,
	[AWP CWA] [varchar](500) NULL,
	[AWP Package] [varchar](500) NULL,
	[EWP] [varchar](500) NULL,
	[PWP] [varchar](500) NULL,
	[CWP] [varchar](500) NULL,
	[IWP] [varchar](500) NULL,
	[GPCA Cost Code] [varchar](500) NULL,
	[GPCA Cost Code Description] [varchar](500) NULL,
	[GPCA Prime Description] [varchar](500) NULL,
	[GPCA Sub Prime Description] [varchar](500) NULL,
	[SourceFileName] [varchar](5000) NULL,
	[project_number] [varchar](100) NULL,
	[CreatedDateTime] [datetime] NULL,
	[Draft IFR(Planning)] [varchar](500) NULL,
	[Draft IFA(Planning)] [varchar](500) NULL,
	[Draft AFC(Planning)] [varchar](500) NULL,
	[Draft IFI(Planning)] [varchar](500) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO